#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H

#include "constants/global.h"
#include "constants/map_event_ids.h"

#define OBJ_EVENT_GFX_BRENDAN_NORMAL               0
#define OBJ_EVENT_GFX_BRENDAN_MACH_BIKE            1
#define OBJ_EVENT_GFX_BRENDAN_SURFING              2
#define OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE           3
#define OBJ_EVENT_GFX_QUINTY_PLUMP                 4
#define OBJ_EVENT_GFX_NINJA_BOY                    5
#define OBJ_EVENT_GFX_TWIN                         6
#define OBJ_EVENT_GFX_BOY_1                        7
#define OBJ_EVENT_GFX_GIRL_1                       8
#define OBJ_EVENT_GFX_BOY_2                        9
#define OBJ_EVENT_GFX_GIRL_2                      10
#define OBJ_EVENT_GFX_LITTLE_BOY                  11
#define OBJ_EVENT_GFX_LITTLE_GIRL                 12
#define OBJ_EVENT_GFX_BOY_3                       13
#define OBJ_EVENT_GFX_GIRL_3                      14
#define OBJ_EVENT_GFX_RICH_BOY                    15
#define OBJ_EVENT_GFX_WOMAN_1                     16
#define OBJ_EVENT_GFX_FAT_MAN                     17
#define OBJ_EVENT_GFX_POKEFAN_F                   18
#define OBJ_EVENT_GFX_MAN_1                       19
#define OBJ_EVENT_GFX_WOMAN_2                     20
#define OBJ_EVENT_GFX_EXPERT_M                    21
#define OBJ_EVENT_GFX_EXPERT_F                    22
#define OBJ_EVENT_GFX_MAN_2                       23
#define OBJ_EVENT_GFX_WOMAN_3                     24
#define OBJ_EVENT_GFX_POKEFAN_M                   25
#define OBJ_EVENT_GFX_WOMAN_4                     26
#define OBJ_EVENT_GFX_COOK                        27
#define OBJ_EVENT_GFX_LINK_RECEPTIONIST           28
#define OBJ_EVENT_GFX_OLD_MAN                     29
#define OBJ_EVENT_GFX_OLD_WOMAN                   30
#define OBJ_EVENT_GFX_CAMPER                      31
#define OBJ_EVENT_GFX_PICNICKER                   32
#define OBJ_EVENT_GFX_MAN_3                       33
#define OBJ_EVENT_GFX_WOMAN_5                     34
#define OBJ_EVENT_GFX_YOUNGSTER                   35
#define OBJ_EVENT_GFX_BUG_CATCHER                 36
#define OBJ_EVENT_GFX_PSYCHIC_M                   37
#define OBJ_EVENT_GFX_SCHOOL_KID_M                38
#define OBJ_EVENT_GFX_MANIAC                      39
#define OBJ_EVENT_GFX_HEX_MANIAC                  40
#define OBJ_EVENT_GFX_RAYQUAZA_STILL              41
#define OBJ_EVENT_GFX_SWIMMER_M                   42
#define OBJ_EVENT_GFX_SWIMMER_F                   43
#define OBJ_EVENT_GFX_BLACK_BELT                  44
#define OBJ_EVENT_GFX_BEAUTY                      45
#define OBJ_EVENT_GFX_SCIENTIST_1                 46
#define OBJ_EVENT_GFX_LASS                        47
#define OBJ_EVENT_GFX_GENTLEMAN                   48
#define OBJ_EVENT_GFX_SAILOR                      49
#define OBJ_EVENT_GFX_FISHERMAN                   50
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_M        51
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_F        52
#define OBJ_EVENT_GFX_TUBER_F                     53
#define OBJ_EVENT_GFX_TUBER_M                     54
#define OBJ_EVENT_GFX_HIKER                       55
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_M        56
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_F        57
#define OBJ_EVENT_GFX_NURSE                       58
#define OBJ_EVENT_GFX_ITEM_BALL                   59
#define OBJ_EVENT_GFX_BERRY_TREE                  60
#define OBJ_EVENT_GFX_BERRY_TREE_EARLY_STAGES     61
#define OBJ_EVENT_GFX_BERRY_TREE_LATE_STAGES      62
#define OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE           63
#define OBJ_EVENT_GFX_PROF_BIRCH                  64
#define OBJ_EVENT_GFX_MAN_4                       65
#define OBJ_EVENT_GFX_MAN_5                       66
#define OBJ_EVENT_GFX_REPORTER_M                  67
#define OBJ_EVENT_GFX_REPORTER_F                  68
#define OBJ_EVENT_GFX_BARD                        69
#define OBJ_EVENT_GFX_ANABEL                      70
#define OBJ_EVENT_GFX_TUCKER                      71
#define OBJ_EVENT_GFX_GRETA                       72
#define OBJ_EVENT_GFX_SPENSER                     73
#define OBJ_EVENT_GFX_NOLAND                      74
#define OBJ_EVENT_GFX_LUCY                        75
#define OBJ_EVENT_GFX_UNUSED_NATU_DOLL            76
#define OBJ_EVENT_GFX_UNUSED_MAGNEMITE_DOLL       77
#define OBJ_EVENT_GFX_UNUSED_SQUIRTLE_DOLL        78
#define OBJ_EVENT_GFX_UNUSED_WOOPER_DOLL          79
#define OBJ_EVENT_GFX_UNUSED_PIKACHU_DOLL         80
#define OBJ_EVENT_GFX_UNUSED_PORYGON2_DOLL        81
#define OBJ_EVENT_GFX_CUTTABLE_TREE               82
#define OBJ_EVENT_GFX_MART_EMPLOYEE               83
#define OBJ_EVENT_GFX_ROOFTOP_SALE_WOMAN          84
#define OBJ_EVENT_GFX_TEALA                       85
#define OBJ_EVENT_GFX_BREAKABLE_ROCK              86
#define OBJ_EVENT_GFX_PUSHABLE_BOULDER            87
#define OBJ_EVENT_GFX_MR_BRINEYS_BOAT             88
#define OBJ_EVENT_GFX_MAY_NORMAL                  89
#define OBJ_EVENT_GFX_MAY_MACH_BIKE               90
#define OBJ_EVENT_GFX_MAY_ACRO_BIKE               91
#define OBJ_EVENT_GFX_MAY_SURFING                 92
#define OBJ_EVENT_GFX_MAY_FIELD_MOVE              93
#define OBJ_EVENT_GFX_TRUCK                       94
#define OBJ_EVENT_GFX_VIGOROTH_CARRYING_BOX       95
#define OBJ_EVENT_GFX_VIGOROTH_FACING_AWAY        96
#define OBJ_EVENT_GFX_BIRCHS_BAG                  97
#define OBJ_EVENT_GFX_ZIGZAGOON_1                 98
#define OBJ_EVENT_GFX_ARTIST                      99
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_NORMAL       100
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_MACH_BIKE    101
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_ACRO_BIKE    102
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_SURFING      103
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_FIELD_MOVE   104
#define OBJ_EVENT_GFX_RIVAL_MAY_NORMAL           105
#define OBJ_EVENT_GFX_RIVAL_MAY_MACH_BIKE        106
#define OBJ_EVENT_GFX_RIVAL_MAY_ACRO_BIKE        107
#define OBJ_EVENT_GFX_RIVAL_MAY_SURFING          108
#define OBJ_EVENT_GFX_RIVAL_MAY_FIELD_MOVE       109
#define OBJ_EVENT_GFX_CAMERAMAN                  110
#define OBJ_EVENT_GFX_BRENDAN_UNDERWATER         111
#define OBJ_EVENT_GFX_MAY_UNDERWATER             112
#define OBJ_EVENT_GFX_MOVING_BOX                 113
#define OBJ_EVENT_GFX_CABLE_CAR                  114
#define OBJ_EVENT_GFX_SCIENTIST_2                115
#define OBJ_EVENT_GFX_DEVON_EMPLOYEE             116
#define OBJ_EVENT_GFX_AQUA_MEMBER_M              117
#define OBJ_EVENT_GFX_AQUA_MEMBER_F              118
#define OBJ_EVENT_GFX_MAGMA_MEMBER_M             119
#define OBJ_EVENT_GFX_MAGMA_MEMBER_F             120
#define OBJ_EVENT_GFX_SIDNEY                     121
#define OBJ_EVENT_GFX_PHOEBE                     122
#define OBJ_EVENT_GFX_GLACIA                     123
#define OBJ_EVENT_GFX_DRAKE                      124
#define OBJ_EVENT_GFX_ROXANNE                    125
#define OBJ_EVENT_GFX_BRAWLY                     126
#define OBJ_EVENT_GFX_WATTSON                    127
#define OBJ_EVENT_GFX_FLANNERY                   128
#define OBJ_EVENT_GFX_NORMAN                     129
#define OBJ_EVENT_GFX_WINONA                     130
#define OBJ_EVENT_GFX_LIZA                       131
#define OBJ_EVENT_GFX_TATE                       132
#define OBJ_EVENT_GFX_WALLACE                    133
#define OBJ_EVENT_GFX_STEVEN                     134
#define OBJ_EVENT_GFX_WALLY                      135
#define OBJ_EVENT_GFX_LITTLE_BOY_3               136
#define OBJ_EVENT_GFX_BRENDAN_FISHING            137
#define OBJ_EVENT_GFX_MAY_FISHING                138
#define OBJ_EVENT_GFX_HOT_SPRINGS_OLD_WOMAN      139
#define OBJ_EVENT_GFX_SS_TIDAL                   140
#define OBJ_EVENT_GFX_SUBMARINE_SHADOW           141
#define OBJ_EVENT_GFX_PICHU_DOLL                 142
#define OBJ_EVENT_GFX_PIKACHU_DOLL               143
#define OBJ_EVENT_GFX_MARILL_DOLL                144
#define OBJ_EVENT_GFX_TOGEPI_DOLL                145
#define OBJ_EVENT_GFX_CYNDAQUIL_DOLL             146
#define OBJ_EVENT_GFX_CHIKORITA_DOLL             147
#define OBJ_EVENT_GFX_TOTODILE_DOLL              148
#define OBJ_EVENT_GFX_JIGGLYPUFF_DOLL            149
#define OBJ_EVENT_GFX_MEOWTH_DOLL                150
#define OBJ_EVENT_GFX_CLEFAIRY_DOLL              151
#define OBJ_EVENT_GFX_DITTO_DOLL                 152
#define OBJ_EVENT_GFX_SMOOCHUM_DOLL              153
#define OBJ_EVENT_GFX_TREECKO_DOLL               154
#define OBJ_EVENT_GFX_TORCHIC_DOLL               155
#define OBJ_EVENT_GFX_MUDKIP_DOLL                156
#define OBJ_EVENT_GFX_DUSKULL_DOLL               157
#define OBJ_EVENT_GFX_WYNAUT_DOLL                158
#define OBJ_EVENT_GFX_BALTOY_DOLL                159
#define OBJ_EVENT_GFX_KECLEON_DOLL               160
#define OBJ_EVENT_GFX_AZURILL_DOLL               161
#define OBJ_EVENT_GFX_SKITTY_DOLL                162
#define OBJ_EVENT_GFX_SWABLU_DOLL                163
#define OBJ_EVENT_GFX_GULPIN_DOLL                164
#define OBJ_EVENT_GFX_LOTAD_DOLL                 165
#define OBJ_EVENT_GFX_SEEDOT_DOLL                166
#define OBJ_EVENT_GFX_PIKA_CUSHION               167
#define OBJ_EVENT_GFX_ROUND_CUSHION              168
#define OBJ_EVENT_GFX_KISS_CUSHION               169
#define OBJ_EVENT_GFX_ZIGZAG_CUSHION             170
#define OBJ_EVENT_GFX_SPIN_CUSHION               171
#define OBJ_EVENT_GFX_DIAMOND_CUSHION            172
#define OBJ_EVENT_GFX_BALL_CUSHION               173
#define OBJ_EVENT_GFX_GRASS_CUSHION              174
#define OBJ_EVENT_GFX_FIRE_CUSHION               175
#define OBJ_EVENT_GFX_WATER_CUSHION              176
#define OBJ_EVENT_GFX_BIG_SNORLAX_DOLL           177
#define OBJ_EVENT_GFX_BIG_RHYDON_DOLL            178
#define OBJ_EVENT_GFX_BIG_LAPRAS_DOLL            179
#define OBJ_EVENT_GFX_BIG_VENUSAUR_DOLL          180
#define OBJ_EVENT_GFX_BIG_CHARIZARD_DOLL         181
#define OBJ_EVENT_GFX_BIG_BLASTOISE_DOLL         182
#define OBJ_EVENT_GFX_BIG_WAILMER_DOLL           183
#define OBJ_EVENT_GFX_BIG_REGIROCK_DOLL          184
#define OBJ_EVENT_GFX_BIG_REGICE_DOLL            185
#define OBJ_EVENT_GFX_BIG_REGISTEEL_DOLL         186
#define OBJ_EVENT_GFX_LATIAS                     187
#define OBJ_EVENT_GFX_LATIOS                     188
#define OBJ_EVENT_GFX_GAMEBOY_KID                189
#define OBJ_EVENT_GFX_CONTEST_JUDGE              190
#define OBJ_EVENT_GFX_BRENDAN_WATERING           191
#define OBJ_EVENT_GFX_MAY_WATERING               192
#define OBJ_EVENT_GFX_BRENDAN_DECORATING         193
#define OBJ_EVENT_GFX_MAY_DECORATING             194
#define OBJ_EVENT_GFX_ARCHIE                     195
#define OBJ_EVENT_GFX_MAXIE                      196
#define OBJ_EVENT_GFX_KYOGRE_FRONT               197
#define OBJ_EVENT_GFX_GROUDON_FRONT              198
#define OBJ_EVENT_GFX_FOSSIL                     199
#define OBJ_EVENT_GFX_REGIROCK                   200
#define OBJ_EVENT_GFX_REGICE                     201
#define OBJ_EVENT_GFX_REGISTEEL                  202
#define OBJ_EVENT_GFX_SKITTY                     203
#define OBJ_EVENT_GFX_KECLEON                    204
#define OBJ_EVENT_GFX_KYOGRE_ASLEEP              205
#define OBJ_EVENT_GFX_GROUDON_ASLEEP             206
#define OBJ_EVENT_GFX_RAYQUAZA                   207
#define OBJ_EVENT_GFX_ZIGZAGOON_2                208
#define OBJ_EVENT_GFX_PIKACHU                    209
#define OBJ_EVENT_GFX_AZUMARILL                  210
#define OBJ_EVENT_GFX_WINGULL                    211
#define OBJ_EVENT_GFX_KECLEON_BRIDGE_SHADOW      212
#define OBJ_EVENT_GFX_TUBER_M_SWIMMING           213
#define OBJ_EVENT_GFX_AZURILL                    214
#define OBJ_EVENT_GFX_MOM                        215
#define OBJ_EVENT_GFX_LINK_BRENDAN               216
#define OBJ_EVENT_GFX_LINK_MAY                   217
#define OBJ_EVENT_GFX_JUAN                       218
#define OBJ_EVENT_GFX_SCOTT                      219
#define OBJ_EVENT_GFX_POOCHYENA                  220
#define OBJ_EVENT_GFX_KYOGRE_SIDE                221
#define OBJ_EVENT_GFX_GROUDON_SIDE               222
#define OBJ_EVENT_GFX_MYSTERY_GIFT_MAN           223
#define OBJ_EVENT_GFX_TRICK_HOUSE_STATUE         224
#define OBJ_EVENT_GFX_KIRLIA                     225
#define OBJ_EVENT_GFX_DUSCLOPS                   226
#define OBJ_EVENT_GFX_UNION_ROOM_NURSE           227
#define OBJ_EVENT_GFX_SUDOWOODO                  228
#define OBJ_EVENT_GFX_MEW                        229
#define OBJ_EVENT_GFX_RED                        230
#define OBJ_EVENT_GFX_LEAF                       231
#define OBJ_EVENT_GFX_DEOXYS                     232
#define OBJ_EVENT_GFX_DEOXYS_TRIANGLE            233
#define OBJ_EVENT_GFX_BRANDON                    234
#define OBJ_EVENT_GFX_LINK_RS_BRENDAN            235
#define OBJ_EVENT_GFX_LINK_RS_MAY                236
#define OBJ_EVENT_GFX_LUGIA                      237
#define OBJ_EVENT_GFX_HOOH                       238
#define OBJ_EVENT_GFX_MEOWTH                     239
#define OBJ_EVENT_GFX_PERSIAN                    240
#define OBJ_EVENT_GFX_POKE_BALL                  OBJ_EVENT_GFX_ITEM_BALL // replaces ITEM_BALL
#define OBJ_EVENT_GFX_OW_MON                     OBJ_EVENT_GFX_REGICE
#define OBJ_EVENT_GFX_LIGHT_SPRITE               OBJ_EVENT_GFX_QUINTY_PLUMP

// NOTE: graphicsId has been widened to u16. The dynamic graphics ids

// that start after NUM_OBJ_EVENT_GFX are well within the u16 range.

// Pokemon follower object event graphics (auto-generated, one per species)
#define OBJ_EVENT_GFX_MON_BULBASAUR                   241
#define OBJ_EVENT_GFX_MON_IVYSAUR                     242
#define OBJ_EVENT_GFX_MON_VENUSAUR                    243
#define OBJ_EVENT_GFX_MON_CHARMANDER                  244
#define OBJ_EVENT_GFX_MON_CHARMELEON                  245
#define OBJ_EVENT_GFX_MON_CHARIZARD                   246
#define OBJ_EVENT_GFX_MON_SQUIRTLE                    247
#define OBJ_EVENT_GFX_MON_WARTORTLE                   248
#define OBJ_EVENT_GFX_MON_BLASTOISE                   249
#define OBJ_EVENT_GFX_MON_CATERPIE                    250
#define OBJ_EVENT_GFX_MON_METAPOD                     251
#define OBJ_EVENT_GFX_MON_BUTTERFREE                  252
#define OBJ_EVENT_GFX_MON_WEEDLE                      253
#define OBJ_EVENT_GFX_MON_KAKUNA                      254
#define OBJ_EVENT_GFX_MON_BEEDRILL                    255
#define OBJ_EVENT_GFX_MON_PIDGEY                      256
#define OBJ_EVENT_GFX_MON_PIDGEOTTO                   257
#define OBJ_EVENT_GFX_MON_PIDGEOT                     258
#define OBJ_EVENT_GFX_MON_RATTATA                     259
#define OBJ_EVENT_GFX_MON_RATICATE                    260
#define OBJ_EVENT_GFX_MON_SPEAROW                     261
#define OBJ_EVENT_GFX_MON_FEAROW                      262
#define OBJ_EVENT_GFX_MON_EKANS                       263
#define OBJ_EVENT_GFX_MON_ARBOK                       264
#define OBJ_EVENT_GFX_MON_PIKACHU                     265
#define OBJ_EVENT_GFX_MON_RAICHU                      266
#define OBJ_EVENT_GFX_MON_SANDSHREW                   267
#define OBJ_EVENT_GFX_MON_SANDSLASH                   268
#define OBJ_EVENT_GFX_MON_NIDORAN_F                   269
#define OBJ_EVENT_GFX_MON_NIDORINA                    270
#define OBJ_EVENT_GFX_MON_NIDOQUEEN                   271
#define OBJ_EVENT_GFX_MON_NIDORAN_M                   272
#define OBJ_EVENT_GFX_MON_NIDORINO                    273
#define OBJ_EVENT_GFX_MON_NIDOKING                    274
#define OBJ_EVENT_GFX_MON_CLEFAIRY                    275
#define OBJ_EVENT_GFX_MON_CLEFABLE                    276
#define OBJ_EVENT_GFX_MON_VULPIX                      277
#define OBJ_EVENT_GFX_MON_NINETALES                   278
#define OBJ_EVENT_GFX_MON_JIGGLYPUFF                  279
#define OBJ_EVENT_GFX_MON_WIGGLYTUFF                  280
#define OBJ_EVENT_GFX_MON_ZUBAT                       281
#define OBJ_EVENT_GFX_MON_GOLBAT                      282
#define OBJ_EVENT_GFX_MON_ODDISH                      283
#define OBJ_EVENT_GFX_MON_GLOOM                       284
#define OBJ_EVENT_GFX_MON_VILEPLUME                   285
#define OBJ_EVENT_GFX_MON_PARAS                       286
#define OBJ_EVENT_GFX_MON_PARASECT                    287
#define OBJ_EVENT_GFX_MON_VENONAT                     288
#define OBJ_EVENT_GFX_MON_VENOMOTH                    289
#define OBJ_EVENT_GFX_MON_DIGLETT                     290
#define OBJ_EVENT_GFX_MON_DUGTRIO                     291
#define OBJ_EVENT_GFX_MON_MEOWTH                      292
#define OBJ_EVENT_GFX_MON_PERSIAN                     293
#define OBJ_EVENT_GFX_MON_PSYDUCK                     294
#define OBJ_EVENT_GFX_MON_GOLDUCK                     295
#define OBJ_EVENT_GFX_MON_MANKEY                      296
#define OBJ_EVENT_GFX_MON_PRIMEAPE                    297
#define OBJ_EVENT_GFX_MON_GROWLITHE                   298
#define OBJ_EVENT_GFX_MON_ARCANINE                    299
#define OBJ_EVENT_GFX_MON_POLIWAG                     300
#define OBJ_EVENT_GFX_MON_POLIWHIRL                   301
#define OBJ_EVENT_GFX_MON_POLIWRATH                   302
#define OBJ_EVENT_GFX_MON_ABRA                        303
#define OBJ_EVENT_GFX_MON_KADABRA                     304
#define OBJ_EVENT_GFX_MON_ALAKAZAM                    305
#define OBJ_EVENT_GFX_MON_MACHOP                      306
#define OBJ_EVENT_GFX_MON_MACHOKE                     307
#define OBJ_EVENT_GFX_MON_MACHAMP                     308
#define OBJ_EVENT_GFX_MON_BELLSPROUT                  309
#define OBJ_EVENT_GFX_MON_WEEPINBELL                  310
#define OBJ_EVENT_GFX_MON_VICTREEBEL                  311
#define OBJ_EVENT_GFX_MON_TENTACOOL                   312
#define OBJ_EVENT_GFX_MON_TENTACRUEL                  313
#define OBJ_EVENT_GFX_MON_GEODUDE                     314
#define OBJ_EVENT_GFX_MON_GRAVELER                    315
#define OBJ_EVENT_GFX_MON_GOLEM                       316
#define OBJ_EVENT_GFX_MON_PONYTA                      317
#define OBJ_EVENT_GFX_MON_RAPIDASH                    318
#define OBJ_EVENT_GFX_MON_SLOWPOKE                    319
#define OBJ_EVENT_GFX_MON_SLOWBRO                     320
#define OBJ_EVENT_GFX_MON_MAGNEMITE                   321
#define OBJ_EVENT_GFX_MON_MAGNETON                    322
#define OBJ_EVENT_GFX_MON_FARFETCHD                   323
#define OBJ_EVENT_GFX_MON_DODUO                       324
#define OBJ_EVENT_GFX_MON_DODRIO                      325
#define OBJ_EVENT_GFX_MON_SEEL                        326
#define OBJ_EVENT_GFX_MON_DEWGONG                     327
#define OBJ_EVENT_GFX_MON_GRIMER                      328
#define OBJ_EVENT_GFX_MON_MUK                         329
#define OBJ_EVENT_GFX_MON_SHELLDER                    330
#define OBJ_EVENT_GFX_MON_CLOYSTER                    331
#define OBJ_EVENT_GFX_MON_GASTLY                      332
#define OBJ_EVENT_GFX_MON_HAUNTER                     333
#define OBJ_EVENT_GFX_MON_GENGAR                      334
#define OBJ_EVENT_GFX_MON_ONIX                        335
#define OBJ_EVENT_GFX_MON_DROWZEE                     336
#define OBJ_EVENT_GFX_MON_HYPNO                       337
#define OBJ_EVENT_GFX_MON_KRABBY                      338
#define OBJ_EVENT_GFX_MON_KINGLER                     339
#define OBJ_EVENT_GFX_MON_VOLTORB                     340
#define OBJ_EVENT_GFX_MON_ELECTRODE                   341
#define OBJ_EVENT_GFX_MON_EXEGGCUTE                   342
#define OBJ_EVENT_GFX_MON_EXEGGUTOR                   343
#define OBJ_EVENT_GFX_MON_CUBONE                      344
#define OBJ_EVENT_GFX_MON_MAROWAK                     345
#define OBJ_EVENT_GFX_MON_HITMONLEE                   346
#define OBJ_EVENT_GFX_MON_HITMONCHAN                  347
#define OBJ_EVENT_GFX_MON_LICKITUNG                   348
#define OBJ_EVENT_GFX_MON_KOFFING                     349
#define OBJ_EVENT_GFX_MON_WEEZING                     350
#define OBJ_EVENT_GFX_MON_RHYHORN                     351
#define OBJ_EVENT_GFX_MON_RHYDON                      352
#define OBJ_EVENT_GFX_MON_CHANSEY                     353
#define OBJ_EVENT_GFX_MON_TANGELA                     354
#define OBJ_EVENT_GFX_MON_KANGASKHAN                  355
#define OBJ_EVENT_GFX_MON_HORSEA                      356
#define OBJ_EVENT_GFX_MON_SEADRA                      357
#define OBJ_EVENT_GFX_MON_GOLDEEN                     358
#define OBJ_EVENT_GFX_MON_SEAKING                     359
#define OBJ_EVENT_GFX_MON_STARYU                      360
#define OBJ_EVENT_GFX_MON_STARMIE                     361
#define OBJ_EVENT_GFX_MON_MR_MIME                     362
#define OBJ_EVENT_GFX_MON_SCYTHER                     363
#define OBJ_EVENT_GFX_MON_JYNX                        364
#define OBJ_EVENT_GFX_MON_ELECTABUZZ                  365
#define OBJ_EVENT_GFX_MON_MAGMAR                      366
#define OBJ_EVENT_GFX_MON_PINSIR                      367
#define OBJ_EVENT_GFX_MON_TAUROS                      368
#define OBJ_EVENT_GFX_MON_MAGIKARP                    369
#define OBJ_EVENT_GFX_MON_GYARADOS                    370
#define OBJ_EVENT_GFX_MON_LAPRAS                      371
#define OBJ_EVENT_GFX_MON_DITTO                       372
#define OBJ_EVENT_GFX_MON_EEVEE                       373
#define OBJ_EVENT_GFX_MON_VAPOREON                    374
#define OBJ_EVENT_GFX_MON_JOLTEON                     375
#define OBJ_EVENT_GFX_MON_FLAREON                     376
#define OBJ_EVENT_GFX_MON_PORYGON                     377
#define OBJ_EVENT_GFX_MON_OMANYTE                     378
#define OBJ_EVENT_GFX_MON_OMASTAR                     379
#define OBJ_EVENT_GFX_MON_KABUTO                      380
#define OBJ_EVENT_GFX_MON_KABUTOPS                    381
#define OBJ_EVENT_GFX_MON_AERODACTYL                  382
#define OBJ_EVENT_GFX_MON_SNORLAX                     383
#define OBJ_EVENT_GFX_MON_ARTICUNO                    384
#define OBJ_EVENT_GFX_MON_ZAPDOS                      385
#define OBJ_EVENT_GFX_MON_MOLTRES                     386
#define OBJ_EVENT_GFX_MON_DRATINI                     387
#define OBJ_EVENT_GFX_MON_DRAGONAIR                   388
#define OBJ_EVENT_GFX_MON_DRAGONITE                   389
#define OBJ_EVENT_GFX_MON_MEWTWO                      390
#define OBJ_EVENT_GFX_MON_MEW                         391
#define OBJ_EVENT_GFX_MON_CHIKORITA                   392
#define OBJ_EVENT_GFX_MON_BAYLEEF                     393
#define OBJ_EVENT_GFX_MON_MEGANIUM                    394
#define OBJ_EVENT_GFX_MON_CYNDAQUIL                   395
#define OBJ_EVENT_GFX_MON_QUILAVA                     396
#define OBJ_EVENT_GFX_MON_TYPHLOSION                  397
#define OBJ_EVENT_GFX_MON_TOTODILE                    398
#define OBJ_EVENT_GFX_MON_CROCONAW                    399
#define OBJ_EVENT_GFX_MON_FERALIGATR                  400
#define OBJ_EVENT_GFX_MON_SENTRET                     401
#define OBJ_EVENT_GFX_MON_FURRET                      402
#define OBJ_EVENT_GFX_MON_HOOTHOOT                    403
#define OBJ_EVENT_GFX_MON_NOCTOWL                     404
#define OBJ_EVENT_GFX_MON_LEDYBA                      405
#define OBJ_EVENT_GFX_MON_LEDIAN                      406
#define OBJ_EVENT_GFX_MON_SPINARAK                    407
#define OBJ_EVENT_GFX_MON_ARIADOS                     408
#define OBJ_EVENT_GFX_MON_CROBAT                      409
#define OBJ_EVENT_GFX_MON_CHINCHOU                    410
#define OBJ_EVENT_GFX_MON_LANTURN                     411
#define OBJ_EVENT_GFX_MON_PICHU                       412
#define OBJ_EVENT_GFX_MON_CLEFFA                      413
#define OBJ_EVENT_GFX_MON_IGGLYBUFF                   414
#define OBJ_EVENT_GFX_MON_TOGEPI                      415
#define OBJ_EVENT_GFX_MON_TOGETIC                     416
#define OBJ_EVENT_GFX_MON_NATU                        417
#define OBJ_EVENT_GFX_MON_XATU                        418
#define OBJ_EVENT_GFX_MON_MAREEP                      419
#define OBJ_EVENT_GFX_MON_FLAAFFY                     420
#define OBJ_EVENT_GFX_MON_AMPHAROS                    421
#define OBJ_EVENT_GFX_MON_BELLOSSOM                   422
#define OBJ_EVENT_GFX_MON_MARILL                      423
#define OBJ_EVENT_GFX_MON_AZUMARILL                   424
#define OBJ_EVENT_GFX_MON_SUDOWOODO                   425
#define OBJ_EVENT_GFX_MON_POLITOED                    426
#define OBJ_EVENT_GFX_MON_HOPPIP                      427
#define OBJ_EVENT_GFX_MON_SKIPLOOM                    428
#define OBJ_EVENT_GFX_MON_JUMPLUFF                    429
#define OBJ_EVENT_GFX_MON_AIPOM                       430
#define OBJ_EVENT_GFX_MON_SUNKERN                     431
#define OBJ_EVENT_GFX_MON_SUNFLORA                    432
#define OBJ_EVENT_GFX_MON_YANMA                       433
#define OBJ_EVENT_GFX_MON_WOOPER                      434
#define OBJ_EVENT_GFX_MON_QUAGSIRE                    435
#define OBJ_EVENT_GFX_MON_ESPEON                      436
#define OBJ_EVENT_GFX_MON_UMBREON                     437
#define OBJ_EVENT_GFX_MON_MURKROW                     438
#define OBJ_EVENT_GFX_MON_SLOWKING                    439
#define OBJ_EVENT_GFX_MON_MISDREAVUS                  440
#define OBJ_EVENT_GFX_MON_UNOWN                       441
#define OBJ_EVENT_GFX_MON_WOBBUFFET                   442
#define OBJ_EVENT_GFX_MON_GIRAFARIG                   443
#define OBJ_EVENT_GFX_MON_PINECO                      444
#define OBJ_EVENT_GFX_MON_FORRETRESS                  445
#define OBJ_EVENT_GFX_MON_DUNSPARCE                   446
#define OBJ_EVENT_GFX_MON_GLIGAR                      447
#define OBJ_EVENT_GFX_MON_STEELIX                     448
#define OBJ_EVENT_GFX_MON_SNUBBULL                    449
#define OBJ_EVENT_GFX_MON_GRANBULL                    450
#define OBJ_EVENT_GFX_MON_QWILFISH                    451
#define OBJ_EVENT_GFX_MON_SCIZOR                      452
#define OBJ_EVENT_GFX_MON_SHUCKLE                     453
#define OBJ_EVENT_GFX_MON_HERACROSS                   454
#define OBJ_EVENT_GFX_MON_SNEASEL                     455
#define OBJ_EVENT_GFX_MON_TEDDIURSA                   456
#define OBJ_EVENT_GFX_MON_URSARING                    457
#define OBJ_EVENT_GFX_MON_SLUGMA                      458
#define OBJ_EVENT_GFX_MON_MAGCARGO                    459
#define OBJ_EVENT_GFX_MON_SWINUB                      460
#define OBJ_EVENT_GFX_MON_PILOSWINE                   461
#define OBJ_EVENT_GFX_MON_CORSOLA                     462
#define OBJ_EVENT_GFX_MON_REMORAID                    463
#define OBJ_EVENT_GFX_MON_OCTILLERY                   464
#define OBJ_EVENT_GFX_MON_DELIBIRD                    465
#define OBJ_EVENT_GFX_MON_MANTINE                     466
#define OBJ_EVENT_GFX_MON_SKARMORY                    467
#define OBJ_EVENT_GFX_MON_HOUNDOUR                    468
#define OBJ_EVENT_GFX_MON_HOUNDOOM                    469
#define OBJ_EVENT_GFX_MON_KINGDRA                     470
#define OBJ_EVENT_GFX_MON_PHANPY                      471
#define OBJ_EVENT_GFX_MON_DONPHAN                     472
#define OBJ_EVENT_GFX_MON_PORYGON2                    473
#define OBJ_EVENT_GFX_MON_STANTLER                    474
#define OBJ_EVENT_GFX_MON_SMEARGLE                    475
#define OBJ_EVENT_GFX_MON_TYROGUE                     476
#define OBJ_EVENT_GFX_MON_HITMONTOP                   477
#define OBJ_EVENT_GFX_MON_SMOOCHUM                    478
#define OBJ_EVENT_GFX_MON_ELEKID                      479
#define OBJ_EVENT_GFX_MON_MAGBY                       480
#define OBJ_EVENT_GFX_MON_MILTANK                     481
#define OBJ_EVENT_GFX_MON_BLISSEY                     482
#define OBJ_EVENT_GFX_MON_RAIKOU                      483
#define OBJ_EVENT_GFX_MON_ENTEI                       484
#define OBJ_EVENT_GFX_MON_SUICUNE                     485
#define OBJ_EVENT_GFX_MON_LARVITAR                    486
#define OBJ_EVENT_GFX_MON_PUPITAR                     487
#define OBJ_EVENT_GFX_MON_TYRANITAR                   488
#define OBJ_EVENT_GFX_MON_LUGIA                       489
#define OBJ_EVENT_GFX_MON_HO_OH                       490
#define OBJ_EVENT_GFX_MON_CELEBI                      491
#define OBJ_EVENT_GFX_MON_TREECKO                     492
#define OBJ_EVENT_GFX_MON_GROVYLE                     493
#define OBJ_EVENT_GFX_MON_SCEPTILE                    494
#define OBJ_EVENT_GFX_MON_TORCHIC                     495
#define OBJ_EVENT_GFX_MON_COMBUSKEN                   496
#define OBJ_EVENT_GFX_MON_BLAZIKEN                    497
#define OBJ_EVENT_GFX_MON_MUDKIP                      498
#define OBJ_EVENT_GFX_MON_MARSHTOMP                   499
#define OBJ_EVENT_GFX_MON_SWAMPERT                    500
#define OBJ_EVENT_GFX_MON_POOCHYENA                   501
#define OBJ_EVENT_GFX_MON_MIGHTYENA                   502
#define OBJ_EVENT_GFX_MON_ZIGZAGOON                   503
#define OBJ_EVENT_GFX_MON_LINOONE                     504
#define OBJ_EVENT_GFX_MON_WURMPLE                     505
#define OBJ_EVENT_GFX_MON_SILCOON                     506
#define OBJ_EVENT_GFX_MON_BEAUTIFLY                   507
#define OBJ_EVENT_GFX_MON_CASCOON                     508
#define OBJ_EVENT_GFX_MON_DUSTOX                      509
#define OBJ_EVENT_GFX_MON_LOTAD                       510
#define OBJ_EVENT_GFX_MON_LOMBRE                      511
#define OBJ_EVENT_GFX_MON_LUDICOLO                    512
#define OBJ_EVENT_GFX_MON_SEEDOT                      513
#define OBJ_EVENT_GFX_MON_NUZLEAF                     514
#define OBJ_EVENT_GFX_MON_SHIFTRY                     515
#define OBJ_EVENT_GFX_MON_NINCADA                     516
#define OBJ_EVENT_GFX_MON_NINJASK                     517
#define OBJ_EVENT_GFX_MON_SHEDINJA                    518
#define OBJ_EVENT_GFX_MON_TAILLOW                     519
#define OBJ_EVENT_GFX_MON_SWELLOW                     520
#define OBJ_EVENT_GFX_MON_SHROOMISH                   521
#define OBJ_EVENT_GFX_MON_BRELOOM                     522
#define OBJ_EVENT_GFX_MON_SPINDA                      523
#define OBJ_EVENT_GFX_MON_WINGULL                     524
#define OBJ_EVENT_GFX_MON_PELIPPER                    525
#define OBJ_EVENT_GFX_MON_SURSKIT                     526
#define OBJ_EVENT_GFX_MON_MASQUERAIN                  527
#define OBJ_EVENT_GFX_MON_WAILMER                     528
#define OBJ_EVENT_GFX_MON_WAILORD                     529
#define OBJ_EVENT_GFX_MON_SKITTY                      530
#define OBJ_EVENT_GFX_MON_DELCATTY                    531
#define OBJ_EVENT_GFX_MON_KECLEON                     532
#define OBJ_EVENT_GFX_MON_BALTOY                      533
#define OBJ_EVENT_GFX_MON_CLAYDOL                     534
#define OBJ_EVENT_GFX_MON_NOSEPASS                    535
#define OBJ_EVENT_GFX_MON_TORKOAL                     536
#define OBJ_EVENT_GFX_MON_SABLEYE                     537
#define OBJ_EVENT_GFX_MON_BARBOACH                    538
#define OBJ_EVENT_GFX_MON_WHISCASH                    539
#define OBJ_EVENT_GFX_MON_LUVDISC                     540
#define OBJ_EVENT_GFX_MON_CORPHISH                    541
#define OBJ_EVENT_GFX_MON_CRAWDAUNT                   542
#define OBJ_EVENT_GFX_MON_FEEBAS                      543
#define OBJ_EVENT_GFX_MON_MILOTIC                     544
#define OBJ_EVENT_GFX_MON_CARVANHA                    545
#define OBJ_EVENT_GFX_MON_SHARPEDO                    546
#define OBJ_EVENT_GFX_MON_TRAPINCH                    547
#define OBJ_EVENT_GFX_MON_VIBRAVA                     548
#define OBJ_EVENT_GFX_MON_FLYGON                      549
#define OBJ_EVENT_GFX_MON_MAKUHITA                    550
#define OBJ_EVENT_GFX_MON_HARIYAMA                    551
#define OBJ_EVENT_GFX_MON_ELECTRIKE                   552
#define OBJ_EVENT_GFX_MON_MANECTRIC                   553
#define OBJ_EVENT_GFX_MON_NUMEL                       554
#define OBJ_EVENT_GFX_MON_CAMERUPT                    555
#define OBJ_EVENT_GFX_MON_SPHEAL                      556
#define OBJ_EVENT_GFX_MON_SEALEO                      557
#define OBJ_EVENT_GFX_MON_WALREIN                     558
#define OBJ_EVENT_GFX_MON_CACNEA                      559
#define OBJ_EVENT_GFX_MON_CACTURNE                    560
#define OBJ_EVENT_GFX_MON_SNORUNT                     561
#define OBJ_EVENT_GFX_MON_GLALIE                      562
#define OBJ_EVENT_GFX_MON_LUNATONE                    563
#define OBJ_EVENT_GFX_MON_SOLROCK                     564
#define OBJ_EVENT_GFX_MON_AZURILL                     565
#define OBJ_EVENT_GFX_MON_SPOINK                      566
#define OBJ_EVENT_GFX_MON_GRUMPIG                     567
#define OBJ_EVENT_GFX_MON_PLUSLE                      568
#define OBJ_EVENT_GFX_MON_MINUN                       569
#define OBJ_EVENT_GFX_MON_MAWILE                      570
#define OBJ_EVENT_GFX_MON_MEDITITE                    571
#define OBJ_EVENT_GFX_MON_MEDICHAM                    572
#define OBJ_EVENT_GFX_MON_SWABLU                      573
#define OBJ_EVENT_GFX_MON_ALTARIA                     574
#define OBJ_EVENT_GFX_MON_WYNAUT                      575
#define OBJ_EVENT_GFX_MON_DUSKULL                     576
#define OBJ_EVENT_GFX_MON_DUSCLOPS                    577
#define OBJ_EVENT_GFX_MON_ROSELIA                     578
#define OBJ_EVENT_GFX_MON_SLAKOTH                     579
#define OBJ_EVENT_GFX_MON_VIGOROTH                    580
#define OBJ_EVENT_GFX_MON_SLAKING                     581
#define OBJ_EVENT_GFX_MON_GULPIN                      582
#define OBJ_EVENT_GFX_MON_SWALOT                      583
#define OBJ_EVENT_GFX_MON_TROPIUS                     584
#define OBJ_EVENT_GFX_MON_WHISMUR                     585
#define OBJ_EVENT_GFX_MON_LOUDRED                     586
#define OBJ_EVENT_GFX_MON_EXPLOUD                     587
#define OBJ_EVENT_GFX_MON_CLAMPERL                    588
#define OBJ_EVENT_GFX_MON_HUNTAIL                     589
#define OBJ_EVENT_GFX_MON_GOREBYSS                    590
#define OBJ_EVENT_GFX_MON_ABSOL                       591
#define OBJ_EVENT_GFX_MON_SHUPPET                     592
#define OBJ_EVENT_GFX_MON_BANETTE                     593
#define OBJ_EVENT_GFX_MON_SEVIPER                     594
#define OBJ_EVENT_GFX_MON_ZANGOOSE                    595
#define OBJ_EVENT_GFX_MON_RELICANTH                   596
#define OBJ_EVENT_GFX_MON_ARON                        597
#define OBJ_EVENT_GFX_MON_LAIRON                      598
#define OBJ_EVENT_GFX_MON_AGGRON                      599
#define OBJ_EVENT_GFX_MON_CASTFORM                    600
#define OBJ_EVENT_GFX_MON_VOLBEAT                     601
#define OBJ_EVENT_GFX_MON_ILLUMISE                    602
#define OBJ_EVENT_GFX_MON_LILEEP                      603
#define OBJ_EVENT_GFX_MON_CRADILY                     604
#define OBJ_EVENT_GFX_MON_ANORITH                     605
#define OBJ_EVENT_GFX_MON_ARMALDO                     606
#define OBJ_EVENT_GFX_MON_RALTS                       607
#define OBJ_EVENT_GFX_MON_KIRLIA                      608
#define OBJ_EVENT_GFX_MON_GARDEVOIR                   609
#define OBJ_EVENT_GFX_MON_BAGON                       610
#define OBJ_EVENT_GFX_MON_SHELGON                     611
#define OBJ_EVENT_GFX_MON_SALAMENCE                   612
#define OBJ_EVENT_GFX_MON_BELDUM                      613
#define OBJ_EVENT_GFX_MON_METANG                      614
#define OBJ_EVENT_GFX_MON_METAGROSS                   615
#define OBJ_EVENT_GFX_MON_REGIROCK                    616
#define OBJ_EVENT_GFX_MON_REGICE                      617
#define OBJ_EVENT_GFX_MON_REGISTEEL                   618
#define OBJ_EVENT_GFX_MON_KYOGRE                      619
#define OBJ_EVENT_GFX_MON_GROUDON                     620
#define OBJ_EVENT_GFX_MON_RAYQUAZA                    621
#define OBJ_EVENT_GFX_MON_LATIAS                      622
#define OBJ_EVENT_GFX_MON_LATIOS                      623
#define OBJ_EVENT_GFX_MON_JIRACHI                     624
#define OBJ_EVENT_GFX_MON_DEOXYS                      625
#define OBJ_EVENT_GFX_MON_CHIMECHO                    626
#define OBJ_EVENT_GFX_MON_UNOWN_B                     627
#define OBJ_EVENT_GFX_MON_UNOWN_C                     628
#define OBJ_EVENT_GFX_MON_UNOWN_D                     629
#define OBJ_EVENT_GFX_MON_UNOWN_E                     630
#define OBJ_EVENT_GFX_MON_UNOWN_F                     631
#define OBJ_EVENT_GFX_MON_UNOWN_G                     632
#define OBJ_EVENT_GFX_MON_UNOWN_H                     633
#define OBJ_EVENT_GFX_MON_UNOWN_I                     634
#define OBJ_EVENT_GFX_MON_UNOWN_J                     635
#define OBJ_EVENT_GFX_MON_UNOWN_K                     636
#define OBJ_EVENT_GFX_MON_UNOWN_L                     637
#define OBJ_EVENT_GFX_MON_UNOWN_M                     638
#define OBJ_EVENT_GFX_MON_UNOWN_N                     639
#define OBJ_EVENT_GFX_MON_UNOWN_O                     640
#define OBJ_EVENT_GFX_MON_UNOWN_P                     641
#define OBJ_EVENT_GFX_MON_UNOWN_Q                     642
#define OBJ_EVENT_GFX_MON_UNOWN_R                     643
#define OBJ_EVENT_GFX_MON_UNOWN_S                     644
#define OBJ_EVENT_GFX_MON_UNOWN_T                     645
#define OBJ_EVENT_GFX_MON_UNOWN_U                     646
#define OBJ_EVENT_GFX_MON_UNOWN_V                     647
#define OBJ_EVENT_GFX_MON_UNOWN_W                     648
#define OBJ_EVENT_GFX_MON_UNOWN_X                     649
#define OBJ_EVENT_GFX_MON_UNOWN_Y                     650
#define OBJ_EVENT_GFX_MON_UNOWN_Z                     651
#define OBJ_EVENT_GFX_MON_UNOWN_EMARK                 652
#define OBJ_EVENT_GFX_MON_UNOWN_QMARK                 653

// Shiny Pokemon follower object event graphics (auto-generated, one per species)
#define OBJ_EVENT_GFX_SHINY_MON_BULBASAUR               654
#define OBJ_EVENT_GFX_SHINY_MON_IVYSAUR                 655
#define OBJ_EVENT_GFX_SHINY_MON_VENUSAUR                656
#define OBJ_EVENT_GFX_SHINY_MON_CHARMANDER              657
#define OBJ_EVENT_GFX_SHINY_MON_CHARMELEON              658
#define OBJ_EVENT_GFX_SHINY_MON_CHARIZARD               659
#define OBJ_EVENT_GFX_SHINY_MON_SQUIRTLE                660
#define OBJ_EVENT_GFX_SHINY_MON_WARTORTLE               661
#define OBJ_EVENT_GFX_SHINY_MON_BLASTOISE               662
#define OBJ_EVENT_GFX_SHINY_MON_CATERPIE                663
#define OBJ_EVENT_GFX_SHINY_MON_METAPOD                 664
#define OBJ_EVENT_GFX_SHINY_MON_BUTTERFREE              665
#define OBJ_EVENT_GFX_SHINY_MON_WEEDLE                  666
#define OBJ_EVENT_GFX_SHINY_MON_KAKUNA                  667
#define OBJ_EVENT_GFX_SHINY_MON_BEEDRILL                668
#define OBJ_EVENT_GFX_SHINY_MON_PIDGEY                  669
#define OBJ_EVENT_GFX_SHINY_MON_PIDGEOTTO               670
#define OBJ_EVENT_GFX_SHINY_MON_PIDGEOT                 671
#define OBJ_EVENT_GFX_SHINY_MON_RATTATA                 672
#define OBJ_EVENT_GFX_SHINY_MON_RATICATE                673
#define OBJ_EVENT_GFX_SHINY_MON_SPEAROW                 674
#define OBJ_EVENT_GFX_SHINY_MON_FEAROW                  675
#define OBJ_EVENT_GFX_SHINY_MON_EKANS                   676
#define OBJ_EVENT_GFX_SHINY_MON_ARBOK                   677
#define OBJ_EVENT_GFX_SHINY_MON_PIKACHU                 678
#define OBJ_EVENT_GFX_SHINY_MON_RAICHU                  679
#define OBJ_EVENT_GFX_SHINY_MON_SANDSHREW               680
#define OBJ_EVENT_GFX_SHINY_MON_SANDSLASH               681
#define OBJ_EVENT_GFX_SHINY_MON_NIDORAN_F               682
#define OBJ_EVENT_GFX_SHINY_MON_NIDORINA                683
#define OBJ_EVENT_GFX_SHINY_MON_NIDOQUEEN               684
#define OBJ_EVENT_GFX_SHINY_MON_NIDORAN_M               685
#define OBJ_EVENT_GFX_SHINY_MON_NIDORINO                686
#define OBJ_EVENT_GFX_SHINY_MON_NIDOKING                687
#define OBJ_EVENT_GFX_SHINY_MON_CLEFAIRY                688
#define OBJ_EVENT_GFX_SHINY_MON_CLEFABLE                689
#define OBJ_EVENT_GFX_SHINY_MON_VULPIX                  690
#define OBJ_EVENT_GFX_SHINY_MON_NINETALES               691
#define OBJ_EVENT_GFX_SHINY_MON_JIGGLYPUFF              692
#define OBJ_EVENT_GFX_SHINY_MON_WIGGLYTUFF              693
#define OBJ_EVENT_GFX_SHINY_MON_ZUBAT                   694
#define OBJ_EVENT_GFX_SHINY_MON_GOLBAT                  695
#define OBJ_EVENT_GFX_SHINY_MON_ODDISH                  696
#define OBJ_EVENT_GFX_SHINY_MON_GLOOM                   697
#define OBJ_EVENT_GFX_SHINY_MON_VILEPLUME               698
#define OBJ_EVENT_GFX_SHINY_MON_PARAS                   699
#define OBJ_EVENT_GFX_SHINY_MON_PARASECT                700
#define OBJ_EVENT_GFX_SHINY_MON_VENONAT                 701
#define OBJ_EVENT_GFX_SHINY_MON_VENOMOTH                702
#define OBJ_EVENT_GFX_SHINY_MON_DIGLETT                 703
#define OBJ_EVENT_GFX_SHINY_MON_DUGTRIO                 704
#define OBJ_EVENT_GFX_SHINY_MON_MEOWTH                  705
#define OBJ_EVENT_GFX_SHINY_MON_PERSIAN                 706
#define OBJ_EVENT_GFX_SHINY_MON_PSYDUCK                 707
#define OBJ_EVENT_GFX_SHINY_MON_GOLDUCK                 708
#define OBJ_EVENT_GFX_SHINY_MON_MANKEY                  709
#define OBJ_EVENT_GFX_SHINY_MON_PRIMEAPE                710
#define OBJ_EVENT_GFX_SHINY_MON_GROWLITHE               711
#define OBJ_EVENT_GFX_SHINY_MON_ARCANINE                712
#define OBJ_EVENT_GFX_SHINY_MON_POLIWAG                 713
#define OBJ_EVENT_GFX_SHINY_MON_POLIWHIRL               714
#define OBJ_EVENT_GFX_SHINY_MON_POLIWRATH               715
#define OBJ_EVENT_GFX_SHINY_MON_ABRA                    716
#define OBJ_EVENT_GFX_SHINY_MON_KADABRA                 717
#define OBJ_EVENT_GFX_SHINY_MON_ALAKAZAM                718
#define OBJ_EVENT_GFX_SHINY_MON_MACHOP                  719
#define OBJ_EVENT_GFX_SHINY_MON_MACHOKE                 720
#define OBJ_EVENT_GFX_SHINY_MON_MACHAMP                 721
#define OBJ_EVENT_GFX_SHINY_MON_BELLSPROUT              722
#define OBJ_EVENT_GFX_SHINY_MON_WEEPINBELL              723
#define OBJ_EVENT_GFX_SHINY_MON_VICTREEBEL              724
#define OBJ_EVENT_GFX_SHINY_MON_TENTACOOL               725
#define OBJ_EVENT_GFX_SHINY_MON_TENTACRUEL              726
#define OBJ_EVENT_GFX_SHINY_MON_GEODUDE                 727
#define OBJ_EVENT_GFX_SHINY_MON_GRAVELER                728
#define OBJ_EVENT_GFX_SHINY_MON_GOLEM                   729
#define OBJ_EVENT_GFX_SHINY_MON_PONYTA                  730
#define OBJ_EVENT_GFX_SHINY_MON_RAPIDASH                731
#define OBJ_EVENT_GFX_SHINY_MON_SLOWPOKE                732
#define OBJ_EVENT_GFX_SHINY_MON_SLOWBRO                 733
#define OBJ_EVENT_GFX_SHINY_MON_MAGNEMITE               734
#define OBJ_EVENT_GFX_SHINY_MON_MAGNETON                735
#define OBJ_EVENT_GFX_SHINY_MON_FARFETCHD               736
#define OBJ_EVENT_GFX_SHINY_MON_DODUO                   737
#define OBJ_EVENT_GFX_SHINY_MON_DODRIO                  738
#define OBJ_EVENT_GFX_SHINY_MON_SEEL                    739
#define OBJ_EVENT_GFX_SHINY_MON_DEWGONG                 740
#define OBJ_EVENT_GFX_SHINY_MON_GRIMER                  741
#define OBJ_EVENT_GFX_SHINY_MON_MUK                     742
#define OBJ_EVENT_GFX_SHINY_MON_SHELLDER                743
#define OBJ_EVENT_GFX_SHINY_MON_CLOYSTER                744
#define OBJ_EVENT_GFX_SHINY_MON_GASTLY                  745
#define OBJ_EVENT_GFX_SHINY_MON_HAUNTER                 746
#define OBJ_EVENT_GFX_SHINY_MON_GENGAR                  747
#define OBJ_EVENT_GFX_SHINY_MON_ONIX                    748
#define OBJ_EVENT_GFX_SHINY_MON_DROWZEE                 749
#define OBJ_EVENT_GFX_SHINY_MON_HYPNO                   750
#define OBJ_EVENT_GFX_SHINY_MON_KRABBY                  751
#define OBJ_EVENT_GFX_SHINY_MON_KINGLER                 752
#define OBJ_EVENT_GFX_SHINY_MON_VOLTORB                 753
#define OBJ_EVENT_GFX_SHINY_MON_ELECTRODE               754
#define OBJ_EVENT_GFX_SHINY_MON_EXEGGCUTE               755
#define OBJ_EVENT_GFX_SHINY_MON_EXEGGUTOR               756
#define OBJ_EVENT_GFX_SHINY_MON_CUBONE                  757
#define OBJ_EVENT_GFX_SHINY_MON_MAROWAK                 758
#define OBJ_EVENT_GFX_SHINY_MON_HITMONLEE               759
#define OBJ_EVENT_GFX_SHINY_MON_HITMONCHAN              760
#define OBJ_EVENT_GFX_SHINY_MON_LICKITUNG               761
#define OBJ_EVENT_GFX_SHINY_MON_KOFFING                 762
#define OBJ_EVENT_GFX_SHINY_MON_WEEZING                 763
#define OBJ_EVENT_GFX_SHINY_MON_RHYHORN                 764
#define OBJ_EVENT_GFX_SHINY_MON_RHYDON                  765
#define OBJ_EVENT_GFX_SHINY_MON_CHANSEY                 766
#define OBJ_EVENT_GFX_SHINY_MON_TANGELA                 767
#define OBJ_EVENT_GFX_SHINY_MON_KANGASKHAN              768
#define OBJ_EVENT_GFX_SHINY_MON_HORSEA                  769
#define OBJ_EVENT_GFX_SHINY_MON_SEADRA                  770
#define OBJ_EVENT_GFX_SHINY_MON_GOLDEEN                 771
#define OBJ_EVENT_GFX_SHINY_MON_SEAKING                 772
#define OBJ_EVENT_GFX_SHINY_MON_STARYU                  773
#define OBJ_EVENT_GFX_SHINY_MON_STARMIE                 774
#define OBJ_EVENT_GFX_SHINY_MON_MR_MIME                 775
#define OBJ_EVENT_GFX_SHINY_MON_SCYTHER                 776
#define OBJ_EVENT_GFX_SHINY_MON_JYNX                    777
#define OBJ_EVENT_GFX_SHINY_MON_ELECTABUZZ              778
#define OBJ_EVENT_GFX_SHINY_MON_MAGMAR                  779
#define OBJ_EVENT_GFX_SHINY_MON_PINSIR                  780
#define OBJ_EVENT_GFX_SHINY_MON_TAUROS                  781
#define OBJ_EVENT_GFX_SHINY_MON_MAGIKARP                782
#define OBJ_EVENT_GFX_SHINY_MON_GYARADOS                783
#define OBJ_EVENT_GFX_SHINY_MON_LAPRAS                  784
#define OBJ_EVENT_GFX_SHINY_MON_DITTO                   785
#define OBJ_EVENT_GFX_SHINY_MON_EEVEE                   786
#define OBJ_EVENT_GFX_SHINY_MON_VAPOREON                787
#define OBJ_EVENT_GFX_SHINY_MON_JOLTEON                 788
#define OBJ_EVENT_GFX_SHINY_MON_FLAREON                 789
#define OBJ_EVENT_GFX_SHINY_MON_PORYGON                 790
#define OBJ_EVENT_GFX_SHINY_MON_OMANYTE                 791
#define OBJ_EVENT_GFX_SHINY_MON_OMASTAR                 792
#define OBJ_EVENT_GFX_SHINY_MON_KABUTO                  793
#define OBJ_EVENT_GFX_SHINY_MON_KABUTOPS                794
#define OBJ_EVENT_GFX_SHINY_MON_AERODACTYL              795
#define OBJ_EVENT_GFX_SHINY_MON_SNORLAX                 796
#define OBJ_EVENT_GFX_SHINY_MON_ARTICUNO                797
#define OBJ_EVENT_GFX_SHINY_MON_ZAPDOS                  798
#define OBJ_EVENT_GFX_SHINY_MON_MOLTRES                 799
#define OBJ_EVENT_GFX_SHINY_MON_DRATINI                 800
#define OBJ_EVENT_GFX_SHINY_MON_DRAGONAIR               801
#define OBJ_EVENT_GFX_SHINY_MON_DRAGONITE               802
#define OBJ_EVENT_GFX_SHINY_MON_MEWTWO                  803
#define OBJ_EVENT_GFX_SHINY_MON_MEW                     804
#define OBJ_EVENT_GFX_SHINY_MON_CHIKORITA               805
#define OBJ_EVENT_GFX_SHINY_MON_BAYLEEF                 806
#define OBJ_EVENT_GFX_SHINY_MON_MEGANIUM                807
#define OBJ_EVENT_GFX_SHINY_MON_CYNDAQUIL               808
#define OBJ_EVENT_GFX_SHINY_MON_QUILAVA                 809
#define OBJ_EVENT_GFX_SHINY_MON_TYPHLOSION              810
#define OBJ_EVENT_GFX_SHINY_MON_TOTODILE                811
#define OBJ_EVENT_GFX_SHINY_MON_CROCONAW                812
#define OBJ_EVENT_GFX_SHINY_MON_FERALIGATR              813
#define OBJ_EVENT_GFX_SHINY_MON_SENTRET                 814
#define OBJ_EVENT_GFX_SHINY_MON_FURRET                  815
#define OBJ_EVENT_GFX_SHINY_MON_HOOTHOOT                816
#define OBJ_EVENT_GFX_SHINY_MON_NOCTOWL                 817
#define OBJ_EVENT_GFX_SHINY_MON_LEDYBA                  818
#define OBJ_EVENT_GFX_SHINY_MON_LEDIAN                  819
#define OBJ_EVENT_GFX_SHINY_MON_SPINARAK                820
#define OBJ_EVENT_GFX_SHINY_MON_ARIADOS                 821
#define OBJ_EVENT_GFX_SHINY_MON_CROBAT                  822
#define OBJ_EVENT_GFX_SHINY_MON_CHINCHOU                823
#define OBJ_EVENT_GFX_SHINY_MON_LANTURN                 824
#define OBJ_EVENT_GFX_SHINY_MON_PICHU                   825
#define OBJ_EVENT_GFX_SHINY_MON_CLEFFA                  826
#define OBJ_EVENT_GFX_SHINY_MON_IGGLYBUFF               827
#define OBJ_EVENT_GFX_SHINY_MON_TOGEPI                  828
#define OBJ_EVENT_GFX_SHINY_MON_TOGETIC                 829
#define OBJ_EVENT_GFX_SHINY_MON_NATU                    830
#define OBJ_EVENT_GFX_SHINY_MON_XATU                    831
#define OBJ_EVENT_GFX_SHINY_MON_MAREEP                  832
#define OBJ_EVENT_GFX_SHINY_MON_FLAAFFY                 833
#define OBJ_EVENT_GFX_SHINY_MON_AMPHAROS                834
#define OBJ_EVENT_GFX_SHINY_MON_BELLOSSOM               835
#define OBJ_EVENT_GFX_SHINY_MON_MARILL                  836
#define OBJ_EVENT_GFX_SHINY_MON_AZUMARILL               837
#define OBJ_EVENT_GFX_SHINY_MON_SUDOWOODO               838
#define OBJ_EVENT_GFX_SHINY_MON_POLITOED                839
#define OBJ_EVENT_GFX_SHINY_MON_HOPPIP                  840
#define OBJ_EVENT_GFX_SHINY_MON_SKIPLOOM                841
#define OBJ_EVENT_GFX_SHINY_MON_JUMPLUFF                842
#define OBJ_EVENT_GFX_SHINY_MON_AIPOM                   843
#define OBJ_EVENT_GFX_SHINY_MON_SUNKERN                 844
#define OBJ_EVENT_GFX_SHINY_MON_SUNFLORA                845
#define OBJ_EVENT_GFX_SHINY_MON_YANMA                   846
#define OBJ_EVENT_GFX_SHINY_MON_WOOPER                  847
#define OBJ_EVENT_GFX_SHINY_MON_QUAGSIRE                848
#define OBJ_EVENT_GFX_SHINY_MON_ESPEON                  849
#define OBJ_EVENT_GFX_SHINY_MON_UMBREON                 850
#define OBJ_EVENT_GFX_SHINY_MON_MURKROW                 851
#define OBJ_EVENT_GFX_SHINY_MON_SLOWKING                852
#define OBJ_EVENT_GFX_SHINY_MON_MISDREAVUS              853
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN                   854
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_B                 855
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_C                 856
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_D                 857
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_E                 858
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_F                 859
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_G                 860
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_H                 861
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_I                 862
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_J                 863
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_K                 864
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_L                 865
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_M                 866
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_N                 867
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_O                 868
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_P                 869
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_Q                 870
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_R                 871
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_S                 872
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_T                 873
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_U                 874
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_V                 875
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_W                 876
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_X                 877
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_Y                 878
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_Z                 879
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_EMARK             880
#define OBJ_EVENT_GFX_SHINY_MON_UNOWN_QMARK             881
#define OBJ_EVENT_GFX_SHINY_MON_WOBBUFFET               882
#define OBJ_EVENT_GFX_SHINY_MON_GIRAFARIG               883
#define OBJ_EVENT_GFX_SHINY_MON_PINECO                  884
#define OBJ_EVENT_GFX_SHINY_MON_FORRETRESS              885
#define OBJ_EVENT_GFX_SHINY_MON_DUNSPARCE               886
#define OBJ_EVENT_GFX_SHINY_MON_GLIGAR                  887
#define OBJ_EVENT_GFX_SHINY_MON_STEELIX                 888
#define OBJ_EVENT_GFX_SHINY_MON_SNUBBULL                889
#define OBJ_EVENT_GFX_SHINY_MON_GRANBULL                890
#define OBJ_EVENT_GFX_SHINY_MON_QWILFISH                891
#define OBJ_EVENT_GFX_SHINY_MON_SCIZOR                  892
#define OBJ_EVENT_GFX_SHINY_MON_SHUCKLE                 893
#define OBJ_EVENT_GFX_SHINY_MON_HERACROSS               894
#define OBJ_EVENT_GFX_SHINY_MON_SNEASEL                 895
#define OBJ_EVENT_GFX_SHINY_MON_TEDDIURSA               896
#define OBJ_EVENT_GFX_SHINY_MON_URSARING                897
#define OBJ_EVENT_GFX_SHINY_MON_SLUGMA                  898
#define OBJ_EVENT_GFX_SHINY_MON_MAGCARGO                899
#define OBJ_EVENT_GFX_SHINY_MON_SWINUB                  900
#define OBJ_EVENT_GFX_SHINY_MON_PILOSWINE               901
#define OBJ_EVENT_GFX_SHINY_MON_CORSOLA                 902
#define OBJ_EVENT_GFX_SHINY_MON_REMORAID                903
#define OBJ_EVENT_GFX_SHINY_MON_OCTILLERY               904
#define OBJ_EVENT_GFX_SHINY_MON_DELIBIRD                905
#define OBJ_EVENT_GFX_SHINY_MON_MANTINE                 906
#define OBJ_EVENT_GFX_SHINY_MON_SKARMORY                907
#define OBJ_EVENT_GFX_SHINY_MON_HOUNDOUR                908
#define OBJ_EVENT_GFX_SHINY_MON_HOUNDOOM                909
#define OBJ_EVENT_GFX_SHINY_MON_KINGDRA                 910
#define OBJ_EVENT_GFX_SHINY_MON_PHANPY                  911
#define OBJ_EVENT_GFX_SHINY_MON_DONPHAN                 912
#define OBJ_EVENT_GFX_SHINY_MON_PORYGON2                913
#define OBJ_EVENT_GFX_SHINY_MON_STANTLER                914
#define OBJ_EVENT_GFX_SHINY_MON_SMEARGLE                915
#define OBJ_EVENT_GFX_SHINY_MON_TYROGUE                 916
#define OBJ_EVENT_GFX_SHINY_MON_HITMONTOP               917
#define OBJ_EVENT_GFX_SHINY_MON_SMOOCHUM                918
#define OBJ_EVENT_GFX_SHINY_MON_ELEKID                  919
#define OBJ_EVENT_GFX_SHINY_MON_MAGBY                   920
#define OBJ_EVENT_GFX_SHINY_MON_MILTANK                 921
#define OBJ_EVENT_GFX_SHINY_MON_BLISSEY                 922
#define OBJ_EVENT_GFX_SHINY_MON_RAIKOU                  923
#define OBJ_EVENT_GFX_SHINY_MON_ENTEI                   924
#define OBJ_EVENT_GFX_SHINY_MON_SUICUNE                 925
#define OBJ_EVENT_GFX_SHINY_MON_LARVITAR                926
#define OBJ_EVENT_GFX_SHINY_MON_PUPITAR                 927
#define OBJ_EVENT_GFX_SHINY_MON_TYRANITAR               928
#define OBJ_EVENT_GFX_SHINY_MON_LUGIA                   929
#define OBJ_EVENT_GFX_SHINY_MON_HO_OH                   930
#define OBJ_EVENT_GFX_SHINY_MON_CELEBI                  931
#define OBJ_EVENT_GFX_SHINY_MON_TREECKO                 932
#define OBJ_EVENT_GFX_SHINY_MON_GROVYLE                 933
#define OBJ_EVENT_GFX_SHINY_MON_SCEPTILE                934
#define OBJ_EVENT_GFX_SHINY_MON_TORCHIC                 935
#define OBJ_EVENT_GFX_SHINY_MON_COMBUSKEN               936
#define OBJ_EVENT_GFX_SHINY_MON_BLAZIKEN                937
#define OBJ_EVENT_GFX_SHINY_MON_MUDKIP                  938
#define OBJ_EVENT_GFX_SHINY_MON_MARSHTOMP               939
#define OBJ_EVENT_GFX_SHINY_MON_SWAMPERT                940
#define OBJ_EVENT_GFX_SHINY_MON_POOCHYENA               941
#define OBJ_EVENT_GFX_SHINY_MON_MIGHTYENA               942
#define OBJ_EVENT_GFX_SHINY_MON_ZIGZAGOON               943
#define OBJ_EVENT_GFX_SHINY_MON_LINOONE                 944
#define OBJ_EVENT_GFX_SHINY_MON_WURMPLE                 945
#define OBJ_EVENT_GFX_SHINY_MON_SILCOON                 946
#define OBJ_EVENT_GFX_SHINY_MON_BEAUTIFLY               947
#define OBJ_EVENT_GFX_SHINY_MON_CASCOON                 948
#define OBJ_EVENT_GFX_SHINY_MON_DUSTOX                  949
#define OBJ_EVENT_GFX_SHINY_MON_LOTAD                   950
#define OBJ_EVENT_GFX_SHINY_MON_LOMBRE                  951
#define OBJ_EVENT_GFX_SHINY_MON_LUDICOLO                952
#define OBJ_EVENT_GFX_SHINY_MON_SEEDOT                  953
#define OBJ_EVENT_GFX_SHINY_MON_NUZLEAF                 954
#define OBJ_EVENT_GFX_SHINY_MON_SHIFTRY                 955
#define OBJ_EVENT_GFX_SHINY_MON_TAILLOW                 956
#define OBJ_EVENT_GFX_SHINY_MON_SWELLOW                 957
#define OBJ_EVENT_GFX_SHINY_MON_WINGULL                 958
#define OBJ_EVENT_GFX_SHINY_MON_PELIPPER                959
#define OBJ_EVENT_GFX_SHINY_MON_RALTS                   960
#define OBJ_EVENT_GFX_SHINY_MON_KIRLIA                  961
#define OBJ_EVENT_GFX_SHINY_MON_GARDEVOIR               962
#define OBJ_EVENT_GFX_SHINY_MON_SURSKIT                 963
#define OBJ_EVENT_GFX_SHINY_MON_MASQUERAIN              964
#define OBJ_EVENT_GFX_SHINY_MON_SHROOMISH               965
#define OBJ_EVENT_GFX_SHINY_MON_BRELOOM                 966
#define OBJ_EVENT_GFX_SHINY_MON_SLAKOTH                 967
#define OBJ_EVENT_GFX_SHINY_MON_VIGOROTH                968
#define OBJ_EVENT_GFX_SHINY_MON_SLAKING                 969
#define OBJ_EVENT_GFX_SHINY_MON_NINCADA                 970
#define OBJ_EVENT_GFX_SHINY_MON_NINJASK                 971
#define OBJ_EVENT_GFX_SHINY_MON_SHEDINJA                972
#define OBJ_EVENT_GFX_SHINY_MON_WHISMUR                 973
#define OBJ_EVENT_GFX_SHINY_MON_LOUDRED                 974
#define OBJ_EVENT_GFX_SHINY_MON_EXPLOUD                 975
#define OBJ_EVENT_GFX_SHINY_MON_MAKUHITA                976
#define OBJ_EVENT_GFX_SHINY_MON_HARIYAMA                977
#define OBJ_EVENT_GFX_SHINY_MON_AZURILL                 978
#define OBJ_EVENT_GFX_SHINY_MON_NOSEPASS                979
#define OBJ_EVENT_GFX_SHINY_MON_SKITTY                  980
#define OBJ_EVENT_GFX_SHINY_MON_DELCATTY                981
#define OBJ_EVENT_GFX_SHINY_MON_SABLEYE                 982
#define OBJ_EVENT_GFX_SHINY_MON_MAWILE                  983
#define OBJ_EVENT_GFX_SHINY_MON_ARON                    984
#define OBJ_EVENT_GFX_SHINY_MON_LAIRON                  985
#define OBJ_EVENT_GFX_SHINY_MON_AGGRON                  986
#define OBJ_EVENT_GFX_SHINY_MON_MEDITITE                987
#define OBJ_EVENT_GFX_SHINY_MON_MEDICHAM                988
#define OBJ_EVENT_GFX_SHINY_MON_ELECTRIKE               989
#define OBJ_EVENT_GFX_SHINY_MON_MANECTRIC               990
#define OBJ_EVENT_GFX_SHINY_MON_PLUSLE                  991
#define OBJ_EVENT_GFX_SHINY_MON_MINUN                   992
#define OBJ_EVENT_GFX_SHINY_MON_VOLBEAT                 993
#define OBJ_EVENT_GFX_SHINY_MON_ILLUMISE                994
#define OBJ_EVENT_GFX_SHINY_MON_ROSELIA                 995
#define OBJ_EVENT_GFX_SHINY_MON_GULPIN                  996
#define OBJ_EVENT_GFX_SHINY_MON_SWALOT                  997
#define OBJ_EVENT_GFX_SHINY_MON_CARVANHA                998
#define OBJ_EVENT_GFX_SHINY_MON_SHARPEDO                999
#define OBJ_EVENT_GFX_SHINY_MON_WAILMER                 1000
#define OBJ_EVENT_GFX_SHINY_MON_WAILORD                 1001
#define OBJ_EVENT_GFX_SHINY_MON_NUMEL                   1002
#define OBJ_EVENT_GFX_SHINY_MON_CAMERUPT                1003
#define OBJ_EVENT_GFX_SHINY_MON_TORKOAL                 1004
#define OBJ_EVENT_GFX_SHINY_MON_SPOINK                  1005
#define OBJ_EVENT_GFX_SHINY_MON_GRUMPIG                 1006
#define OBJ_EVENT_GFX_SHINY_MON_SPINDA                  1007
#define OBJ_EVENT_GFX_SHINY_MON_TRAPINCH                1008
#define OBJ_EVENT_GFX_SHINY_MON_VIBRAVA                 1009
#define OBJ_EVENT_GFX_SHINY_MON_FLYGON                  1010
#define OBJ_EVENT_GFX_SHINY_MON_CACNEA                  1011
#define OBJ_EVENT_GFX_SHINY_MON_CACTURNE                1012
#define OBJ_EVENT_GFX_SHINY_MON_SWABLU                  1013
#define OBJ_EVENT_GFX_SHINY_MON_ALTARIA                 1014
#define OBJ_EVENT_GFX_SHINY_MON_ZANGOOSE                1015
#define OBJ_EVENT_GFX_SHINY_MON_SEVIPER                 1016
#define OBJ_EVENT_GFX_SHINY_MON_LUNATONE                1017
#define OBJ_EVENT_GFX_SHINY_MON_SOLROCK                 1018
#define OBJ_EVENT_GFX_SHINY_MON_BARBOACH                1019
#define OBJ_EVENT_GFX_SHINY_MON_WHISCASH                1020
#define OBJ_EVENT_GFX_SHINY_MON_CORPHISH                1021
#define OBJ_EVENT_GFX_SHINY_MON_CRAWDAUNT               1022
#define OBJ_EVENT_GFX_SHINY_MON_BALTOY                  1023
#define OBJ_EVENT_GFX_SHINY_MON_CLAYDOL                 1024
#define OBJ_EVENT_GFX_SHINY_MON_LILEEP                  1025
#define OBJ_EVENT_GFX_SHINY_MON_CRADILY                 1026
#define OBJ_EVENT_GFX_SHINY_MON_ANORITH                 1027
#define OBJ_EVENT_GFX_SHINY_MON_ARMALDO                 1028
#define OBJ_EVENT_GFX_SHINY_MON_FEEBAS                  1029
#define OBJ_EVENT_GFX_SHINY_MON_MILOTIC                 1030
#define OBJ_EVENT_GFX_SHINY_MON_CASTFORM                1031
#define OBJ_EVENT_GFX_SHINY_MON_KECLEON                 1032
#define OBJ_EVENT_GFX_SHINY_MON_SHUPPET                 1033
#define OBJ_EVENT_GFX_SHINY_MON_BANETTE                 1034
#define OBJ_EVENT_GFX_SHINY_MON_DUSKULL                 1035
#define OBJ_EVENT_GFX_SHINY_MON_DUSCLOPS                1036
#define OBJ_EVENT_GFX_SHINY_MON_TROPIUS                 1037
#define OBJ_EVENT_GFX_SHINY_MON_CHIMECHO                1038
#define OBJ_EVENT_GFX_SHINY_MON_ABSOL                   1039
#define OBJ_EVENT_GFX_SHINY_MON_WYNAUT                  1040
#define OBJ_EVENT_GFX_SHINY_MON_SNORUNT                 1041
#define OBJ_EVENT_GFX_SHINY_MON_GLALIE                  1042
#define OBJ_EVENT_GFX_SHINY_MON_SPHEAL                  1043
#define OBJ_EVENT_GFX_SHINY_MON_SEALEO                  1044
#define OBJ_EVENT_GFX_SHINY_MON_WALREIN                 1045
#define OBJ_EVENT_GFX_SHINY_MON_CLAMPERL                1046
#define OBJ_EVENT_GFX_SHINY_MON_HUNTAIL                 1047
#define OBJ_EVENT_GFX_SHINY_MON_GOREBYSS                1048
#define OBJ_EVENT_GFX_SHINY_MON_RELICANTH               1049
#define OBJ_EVENT_GFX_SHINY_MON_LUVDISC                 1050
#define OBJ_EVENT_GFX_SHINY_MON_BAGON                   1051
#define OBJ_EVENT_GFX_SHINY_MON_SHELGON                 1052
#define OBJ_EVENT_GFX_SHINY_MON_SALAMENCE               1053
#define OBJ_EVENT_GFX_SHINY_MON_BELDUM                  1054
#define OBJ_EVENT_GFX_SHINY_MON_METANG                  1055
#define OBJ_EVENT_GFX_SHINY_MON_METAGROSS               1056
#define OBJ_EVENT_GFX_SHINY_MON_REGIROCK                1057
#define OBJ_EVENT_GFX_SHINY_MON_REGICE                  1058
#define OBJ_EVENT_GFX_SHINY_MON_REGISTEEL               1059
#define OBJ_EVENT_GFX_SHINY_MON_LATIAS                  1060
#define OBJ_EVENT_GFX_SHINY_MON_LATIOS                  1061
#define OBJ_EVENT_GFX_SHINY_MON_KYOGRE                  1062
#define OBJ_EVENT_GFX_SHINY_MON_GROUDON                 1063
#define OBJ_EVENT_GFX_SHINY_MON_RAYQUAZA                1064
#define OBJ_EVENT_GFX_SHINY_MON_JIRACHI                 1065
#define OBJ_EVENT_GFX_SHINY_MON_DEOXYS                  1066

// ===== Kanto NPC Object Event Graphics =====
#define OBJ_EVENT_GFX_AGATHA                        1067
#define OBJ_EVENT_GFX_ARTICUNO                        1068
#define OBJ_EVENT_GFX_BALDING_MAN                        1069
#define OBJ_EVENT_GFX_BIKER                        1070
#define OBJ_EVENT_GFX_BILL                        1071
#define OBJ_EVENT_GFX_BLAINE                        1072
#define OBJ_EVENT_GFX_BLUE                        1073
#define OBJ_EVENT_GFX_BOY                        1074
#define OBJ_EVENT_GFX_BROCK                        1075
#define OBJ_EVENT_GFX_BRUNO                        1076
#define OBJ_EVENT_GFX_CABLE_CLUB_RECEPTIONIST                        1077
#define OBJ_EVENT_GFX_CAPTAIN                        1078
#define OBJ_EVENT_GFX_CELIO                        1079
#define OBJ_EVENT_GFX_CHANNELER                        1080
#define OBJ_EVENT_GFX_CHANSEY                        1081
#define OBJ_EVENT_GFX_CHEF                        1082
#define OBJ_EVENT_GFX_CLEFAIRY                        1083
#define OBJ_EVENT_GFX_CLERK                        1084
#define OBJ_EVENT_GFX_CLIPBOARD                        1085
#define OBJ_EVENT_GFX_COOLTRAINER_F                        1086
#define OBJ_EVENT_GFX_COOLTRAINER_M                        1087
#define OBJ_EVENT_GFX_CRUSH_GIRL                        1088
#define OBJ_EVENT_GFX_CUBONE                        1089
#define OBJ_EVENT_GFX_CUT_TREE                        1090
#define OBJ_EVENT_GFX_DAISY                        1091
#define OBJ_EVENT_GFX_DODUO                        1092
#define OBJ_EVENT_GFX_ERIKA                        1093
#define OBJ_EVENT_GFX_FEAROW                        1094
#define OBJ_EVENT_GFX_FISHER                        1095
#define OBJ_EVENT_GFX_GBA_KID                        1096
#define OBJ_EVENT_GFX_GIOVANNI                        1097
#define OBJ_EVENT_GFX_GYM_GUY                        1098
#define OBJ_EVENT_GFX_HO_OH                        1099
#define OBJ_EVENT_GFX_JIGGLYPUFF                        1100
#define OBJ_EVENT_GFX_KABUTO                        1101
#define OBJ_EVENT_GFX_KANGASKHAN                        1102
#define OBJ_EVENT_GFX_KOGA                        1103
#define OBJ_EVENT_GFX_LANCE                        1104
#define OBJ_EVENT_GFX_LAPRAS                        1105
#define OBJ_EVENT_GFX_LAPRAS_DOLL                        1106
#define OBJ_EVENT_GFX_LORELEI                        1107
#define OBJ_EVENT_GFX_LT_SURGE                        1108
#define OBJ_EVENT_GFX_MACHOKE                        1109
#define OBJ_EVENT_GFX_MACHOP                        1110
#define OBJ_EVENT_GFX_MAN                        1111
#define OBJ_EVENT_GFX_MEWTWO                        1112
#define OBJ_EVENT_GFX_MG_DELIVERYMAN                        1113
#define OBJ_EVENT_GFX_MISTY                        1114
#define OBJ_EVENT_GFX_MOLTRES                        1115
#define OBJ_EVENT_GFX_MR_FUJI                        1116
#define OBJ_EVENT_GFX_NIDORAN_F                        1117
#define OBJ_EVENT_GFX_NIDORAN_M                        1118
#define OBJ_EVENT_GFX_NIDORINO                        1119
#define OBJ_EVENT_GFX_OLD_AMBER                        1120
#define OBJ_EVENT_GFX_OLD_MAN_1                        1121
#define OBJ_EVENT_GFX_OLD_MAN_2                        1122
#define OBJ_EVENT_GFX_OLD_MAN_LYING_DOWN                        1123
#define OBJ_EVENT_GFX_OMANYTE                        1124
#define OBJ_EVENT_GFX_PIDGEOT                        1125
#define OBJ_EVENT_GFX_PIDGEY                        1126
#define OBJ_EVENT_GFX_POKEDEX                        1127
#define OBJ_EVENT_GFX_POKE_MANIAC                        1128
#define OBJ_EVENT_GFX_POLICEMAN                        1129
#define OBJ_EVENT_GFX_POLIWRATH                        1130
#define OBJ_EVENT_GFX_PROF_OAK                        1131
#define OBJ_EVENT_GFX_PSYDUCK                        1132
#define OBJ_EVENT_GFX_ROCKER                        1133
#define OBJ_EVENT_GFX_ROCKET_F                        1134
#define OBJ_EVENT_GFX_ROCKET_M                        1135
#define OBJ_EVENT_GFX_ROCK_SMASH_ROCK                        1136
#define OBJ_EVENT_GFX_RUBY                        1137
#define OBJ_EVENT_GFX_SABRINA                        1138
#define OBJ_EVENT_GFX_SAPPHIRE                        1139
#define OBJ_EVENT_GFX_SCIENTIST                        1140
#define OBJ_EVENT_GFX_SEAGALLOP                        1141
#define OBJ_EVENT_GFX_SEEL                        1142
#define OBJ_EVENT_GFX_SLOWBRO                        1143
#define OBJ_EVENT_GFX_SLOWPOKE                        1144
#define OBJ_EVENT_GFX_SNORLAX                        1145
#define OBJ_EVENT_GFX_SPEAROW                        1146
#define OBJ_EVENT_GFX_SS_ANNE                        1147
#define OBJ_EVENT_GFX_SWIMMER_F_LAND                        1148
#define OBJ_EVENT_GFX_SWIMMER_F_WATER                        1149
#define OBJ_EVENT_GFX_SWIMMER_M_LAND                        1150
#define OBJ_EVENT_GFX_SWIMMER_M_WATER                        1151
#define OBJ_EVENT_GFX_TOWN_MAP                        1152
#define OBJ_EVENT_GFX_TRAINER_TOWER_DUDE                        1153
#define OBJ_EVENT_GFX_TUBER_M_WATER                        1154
#define OBJ_EVENT_GFX_UNION_ROOM_RECEPTIONIST                        1155
#define OBJ_EVENT_GFX_VOLTORB                        1156
#define OBJ_EVENT_GFX_WIGGLYTUFF                        1157
#define OBJ_EVENT_GFX_WORKER_F                        1158
#define OBJ_EVENT_GFX_WORKER_M                        1159
#define OBJ_EVENT_GFX_ZAPDOS                        1160
#define NUM_OBJ_EVENT_GFX                        1161



// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define OBJ_EVENT_GFX_VARS   (NUM_OBJ_EVENT_GFX + 1)
#define OBJ_EVENT_GFX_VAR_0  (OBJ_EVENT_GFX_VARS + 0x0) // 240
#define OBJ_EVENT_GFX_VAR_1  (OBJ_EVENT_GFX_VARS + 0x1)
#define OBJ_EVENT_GFX_VAR_2  (OBJ_EVENT_GFX_VARS + 0x2)
#define OBJ_EVENT_GFX_VAR_3  (OBJ_EVENT_GFX_VARS + 0x3)
#define OBJ_EVENT_GFX_VAR_4  (OBJ_EVENT_GFX_VARS + 0x4)
#define OBJ_EVENT_GFX_VAR_5  (OBJ_EVENT_GFX_VARS + 0x5)
#define OBJ_EVENT_GFX_VAR_6  (OBJ_EVENT_GFX_VARS + 0x6)
#define OBJ_EVENT_GFX_VAR_7  (OBJ_EVENT_GFX_VARS + 0x7)
#define OBJ_EVENT_GFX_VAR_8  (OBJ_EVENT_GFX_VARS + 0x8)
#define OBJ_EVENT_GFX_VAR_9  (OBJ_EVENT_GFX_VARS + 0x9)
#define OBJ_EVENT_GFX_VAR_A  (OBJ_EVENT_GFX_VARS + 0xA)
#define OBJ_EVENT_GFX_VAR_B  (OBJ_EVENT_GFX_VARS + 0xB)
#define OBJ_EVENT_GFX_VAR_C  (OBJ_EVENT_GFX_VARS + 0xC)
#define OBJ_EVENT_GFX_VAR_D  (OBJ_EVENT_GFX_VARS + 0xD)
#define OBJ_EVENT_GFX_VAR_E  (OBJ_EVENT_GFX_VARS + 0xE)
#define OBJ_EVENT_GFX_VAR_F  (OBJ_EVENT_GFX_VARS + 0xF) // 255

// If true, follower pokemon will bob up and down
// during their idle & walking animations
#define OW_MON_BOBBING  TRUE

// If true, adds a small amount of overhead
// to OW code so that large (48x48, 64x64) OWs
// will display correctly under bridges, etc.
#define LARGE_OW_SUPPORT TRUE

// Followers will emerge from the pokeball they are stored in,
// instead of a normal pokeball
#define OW_MON_POKEBALLS TRUE

// New/old handling for followers during scripts;
// TRUE: Script collisions hide follower, FLAG_SAFE_FOLLOWER_MOVEMENT on by default
// (scripted player movement moves follower too!)
// FALSE: Script collisions unhandled, FLAG_SAFE_FOLLOWER_MOVEMENT off by default
#define OW_MON_SCRIPT_MOVEMENT TRUE

// If set, the only pokemon allowed to follow you
// will be those matching species, met location,
// and/or met level;
// These accept vars, too: VAR_TEMP_1, etc
#define OW_MON_ALLOWED_SPECIES (0)
#define OW_MON_ALLOWED_MET_LVL (0)
#define OW_MON_ALLOWED_MET_LOC (0)
// Examples:
// Yellow Pikachu:
// #define OW_MON_ALLOWED_SPECIES (SPECIES_PIKACHU)
// #define OW_MON_ALLOWED_MET_LVL (0)
// #define OW_MON_ALLOWED_MET_LOC (MAPSEC_PALLET_TOWN)
// Hoenn Starter:
// #define OW_MON_ALLOWED_SPECIES (0)
// #define OW_MON_ALLOWED_MET_LVL (5)
// #define OW_MON_ALLOWED_MET_LOC (MAPSEC_ROUTE_101)
// Species set in VAR_XXXX:
// #define OW_MON_ALLOWED_SPECIES (VAR_XXXX)
// #define OW_MON_ALLOWED_MET_LVL (0)
// #define OW_MON_ALLOWED_MET_LOC (0)

#define SHADOW_SIZE_S   0
#define SHADOW_SIZE_M   1
#define SHADOW_SIZE_L   2
#define SHADOW_SIZE_XL  3 // unused; repurposed to mean no shadow
#define SHADOW_SIZE_NONE 3

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2
#define TRACKS_SLITHER    3
#define TRACKS_SPOT       4
#define TRACKS_BUG        5

#define FIRST_DECORATION_SPRITE_GFX OBJ_EVENT_GFX_PICHU_DOLL

#define OBJ_KIND_NORMAL 0
#define OBJ_KIND_CLONE  255 // Exclusive to FRLG

// Each object event template gets an ID that can be used to refer to it in scripts and elsewhere.
// This is referred to as the "local id" (and it's really just 1 + its index in the templates array).
// There are a few special IDs reserved for objects that don't have templates in the map data -- one for the player
// in regular offline play, five for linked players while playing Berry Blender, and one for an invisible object that
// can be spawned for the camera to track instead of the player. Additionally, the value 0 is reserved as an "empty" indicator.
#define LOCALID_NONE                         0
#define LOCALID_CAMERA                     127
#define LOCALID_BERRY_BLENDER_PLAYER_END   240 // This will use 5 (MAX_RFU_PLAYERS) IDs ending at 240, i.e. 236-240
#define LOCALID_FOLLOWING_POKEMON          254
#define LOCALID_PLAYER                     255

// Aliases for old names. "object event id" normally refers to an index into gObjectEvents, which these are not.
// Used for link player OWs in CreateLinkPlayerSprite
#define OBJ_EVENT_ID_DYNAMIC_BASE 0xF0
#define OBJ_EVENT_ID_CAMERA LOCALID_CAMERA
#define OBJ_EVENT_ID_PLAYER LOCALID_PLAYER
#define OBJ_EVENT_ID_FOLLOWER LOCALID_FOLLOWING_POKEMON

#endif  // GUARD_CONSTANTS_EVENT_OBJECTS_H
