#ifndef GUARD_CONSTANTS_JOHTO_STUBS_H
#define GUARD_CONSTANTS_JOHTO_STUBS_H

// Stub constants for ported pokesequel Johto scripts.
// These values are placeholders so that scripts.inc files assemble cleanly.
// Replace 0 with proper values once the corresponding feature is fully ported.

// Missing species (defined here as 0 = SPECIES_NONE so any compare is harmless)
#define SPECIES_MUNCHLAX 0

// Pokesequel in-game trades (not yet ported to pokeemerald constants/trade.h)
// Note: INGAME_TRADE_{JYNX,NIDORAN,FARFETCHD,NIDORINOA,LICKITUNG,ELECTRODE,TANGELA,SEEL}
// are already defined via .equiv in asm/macros/frlg_compat.inc.
// INGAME_TRADE_{ONIX,MACHOP,VOLTORB} are now properly defined in constants/trade.h.

// Lake of Rage fisher / Magikarp size compare results
#define MON_SATISFACTORY   1
#define MON_UNSATISFACTORY 2

// Ruins of Alph sliding puzzle ids
#define SLIDING_PUZZLE_AERODACTYL 0
#define SLIDING_PUZZLE_HO_OH      1
#define SLIDING_PUZZLE_KABUTO     2
#define SLIDING_PUZZLE_OMANYTE    3

// Move tutor move ids (Headbutt tutor in Ilex Forest)
#define TUTOR_MOVE_HEADBUTT 0

// >>> AUTOGEN johto stub numeric symbols (do not edit by hand)
#define FLAG_BADGE09_GET 0
#define FLAG_BADGE10_GET 0
#define FLAG_BADGE11_GET 0
#define FLAG_BADGE12_GET 0
#define FLAG_BADGE13_GET 0
#define FLAG_BADGE14_GET 0
#define FLAG_BADGE15_GET 0
#define FLAG_BADGE16_GET 0
#define FLAG_DAILY_BUG_CONTEST_COMPLETED 0
#define FLAG_DAILY_HAIRCUT1_RECEIVED 0
#define FLAG_DAILY_HAIRCUT2_RECEIVED 0
#define FLAG_DAY_POKEMON 0
#define FLAG_GOT_ROUTE2_NUGGET 0
#define FLAG_GOT_ROUTE_14_AERIAL_ACE 0
#define FLAG_GOT_TM_PSYCHIC 0
#define FLAG_GOT_VERMILION_HP_UP 0
#define FLAG_GOT_VIRIDIAN_TM_SLUDGE_BOMB 0
#define FLAG_HIDE_CELADON_FALKNER 0
#define FLAG_HIDE_CERULEANCAVE_GUARD 0
#define FLAG_HIDE_CERULEAN_CAPE_ROCKET 0
#define FLAG_HIDE_CERULEAN_GYM_ROCKET 0
#define FLAG_HIDE_CERULEAN_GYM_TRAINERS 0
#define FLAG_HIDE_CINNABAR_BLUE 0
#define FLAG_HIDE_COPYCAT_CLEFAIRY_DOLL 0
#define FLAG_HIDE_FAN_CLUB_CLEFAIRY_DOLL 0
#define FLAG_HIDE_GROUDON 0
#define FLAG_HIDE_KYOGRE 0
#define FLAG_HIDE_LATIAS 0
#define FLAG_HIDE_LATIOS 0
#define FLAG_HIDE_OLIVINE_SABRINA 0
#define FLAG_HIDE_PEWTER_CLAW_FOSSIL 0
#define FLAG_HIDE_PEWTER_ROOT_FOSSIL 0
#define FLAG_HIDE_RAYQUAZA 0
#define FLAG_HIDE_ROUTE14_EUSINE 0
#define FLAG_HIDE_ROUTE14_SUICUNE 0
#define FLAG_HIDE_ROUTE22_JANINE 0
#define FLAG_HIDE_SEAFOAM_BLAINE 0
#define FLAG_HIDE_SEAFOAM_GYMGUY 0
#define FLAG_HIDE_VERMILION_SNORLAX 0
#define FLAG_HIDE_VIRIDIAN_BLUE 0
#define FLAG_HIDE_VIRIDIAN_BUGSY 0
#define FLAG_IN_KANTO_SAFARI_ZONE 0
#define FLAG_IS_KANTO_CHAMPION 0
#define FLAG_MINTS_CLERK 0
#define FLAG_MINTS_ENABLED 0
#define FLAG_NIGHT_POKEMON 0
#define FLAG_ROUTE25_GOT_NUGGET 0
#define FLAG_SYS_PC_BILL 0
#define FLAG_VISITED_KANTO 0
#define FLAG_VISITED_VERMILION_CITY 0
#define HEAL_LOCATION_AZALEA_TOWN 0
#define HEAL_LOCATION_BLACKTHORN_CITY 0
#define HEAL_LOCATION_CHERRYGROVE_CITY 0
#define HEAL_LOCATION_CIANWOOD_CITY 0
#define HEAL_LOCATION_ECRUTEAK_CITY 0
#define HEAL_LOCATION_GOLDENROD_CITY 0
#define HEAL_LOCATION_MAHOGANYTOWN 0
#define HEAL_LOCATION_MT_SILVER 0
#define HEAL_LOCATION_NEW_BARK_TOWN 0
#define HEAL_LOCATION_OLIVINE_CITY 0
#define HEAL_LOCATION_ROUTE_32 0
#define HEAL_LOCATION_SAFARI_ZONE_GATE 0
#define HEAL_LOCATION_VIOLET_CITY 0
#define ITEM_BIG_NUGGET 0
#define ITEM_EXP_SHARE_SMALL 0
#define ITEM_FAST_BALL 0
#define ITEM_FRIEND_BALL 0
#define ITEM_HEAVY_BALL 0
#define ITEM_LEVEL_BALL 0
#define ITEM_LOVE_BALL 0
#define ITEM_LURE_BALL 0
#define ITEM_MODEST_MINT 0
#define ITEM_MOON_BALL 0
#define ITEM_PASS 0
#define ITEM_RADIO 0
#define ITEM_RAGE_CANDY_BAR 0
#define ITEM_SECRET_POTION 0
#define ITEM_SQUIRT_BOTTLE 0
#define METATILE_R26_21_Broken_Window 0
#define MOVEMENT_TYPE_TOWER_BEAM 0
#define MULTI_5FLOORS 0
#define MULTI_7FLOORS 0
#define MULTI_DAYS_OF_WEEK 0
#define MULTI_ELDERQUIIZ1 0
#define MULTI_ELDERQUIIZ2 0
#define MULTI_ELDERQUIIZ3 0
#define MULTI_ELDERQUIIZ4 0
#define MULTI_ELDERQUIIZ5 0
#define MULTI_GOLDSILVER 0
#define MULTI_KURT_BALLS 0
#define MULTI_OLIVINE_HARBOR 0
#define MULTI_PRIZE_MONS 0
#define MUS_HG_ENCOUNTER_RIVAL 0
#define MUS_HG_EUSINE 0
#define MUS_HG_FOLLOW_ME_1 0
#define MUS_HG_GOLDENROD 0
#define MUS_HG_KIMONO_GIRL 0
#define MUS_HG_KIMONO_GIRL_DANCE 0
#define MUS_HG_OAK 0
#define MUS_HG_POKEGEAR_REGISTERED 0
#define MUS_HG_RADIO_ROCKET 0
#define MUS_HG_RIVAL_EXIT 0
#define MUS_HG_ROCKET_TAKEOVER 0
#define MUS_HG_TEAM_ROCKET_HQ 0
#define MUS_HG_VS_HO_OH 0
#define MUS_HG_VS_LUGIA 0
#define VAR_BAOBA_QUEST_STATE 0
#define VAR_BLACKTHORN_GYM_STATE 0
#define VAR_CINNABAR_ISLAND_STATE 0
#define VAR_DRAGONS_DEN_QUIZ 0
#define VAR_FAN_CLUB_GUY 0
#define VAR_KANTO_ROCKET_STORY_STATE 0
#define VAR_KANTO_SAFARI_ZONE_PROGRESS 0
#define VAR_PALLETTOWN_LABSTATE 0
#define VAR_ROUTE27_BAOBA_CALL 0
#define VAR_VERMILION_CITY_STATE 0
// <<< AUTOGEN johto stub numeric symbols

#endif // GUARD_CONSTANTS_JOHTO_STUBS_H
