// Johto Trainers (ported from pokesequel)
#define TRAINER_SAYO                             1600
#define TRAINER_SCOTT                            1601
#define TRAINER_SEAN                             1602
#define TRAINER_TROY                             1603
#define TRAINER_TULLY                            1604
#define TRAINER_ROD                              1605
#define TRAINER_VALERIE                          1606
#define TRAINER_JOYCE                            1607
#define TRAINER_ZUKI                             1608
#define TRAINER_FALKNER_1                        1609
#define TRAINER_TODD                             1610
#define TRAINER_TIMOTHY                          1611
#define TRAINER_STANLY                           1612
#define TRAINER_DEVIN                            1613
#define TRAINER_GRANT                            1614
#define TRAINER_CASSIE                           1615
#define TRAINER_JEFFREY                          1616
#define TRAINER_GRUNT_33                         1617
#define TRAINER_NORMAN                           1618
#define TRAINER_KRISE                            1619
#define TRAINER_RAYMOND                          1620
#define TRAINER_KUNI                             1621
#define TRAINER_LAO                              1622
#define TRAINER_LEA_AND_PIA                      1623
#define TRAINER_REENA                            1624
#define TRAINER_RICH                             1625
#define TRAINER_RICKY                            1626
#define TRAINER_CODY                             1627
#define TRAINER_ELAINE                           1628
#define TRAINER_EMMA                             1629
#define TRAINER_GIOVANNI                         1630
#define TRAINER_ERIK                             1631
#define TRAINER_ERIN                             1632
#define TRAINER_ERNEST                           1633
#define TRAINER_WAI                              1634
#define TRAINER_GRUNT_19                         1635
#define TRAINER_GRUNT_20                         1636
#define TRAINER_GRUNT_21                         1637
#define TRAINER_GRUNT_22                         1638
#define TRAINER_ARIANA_2                         1639
#define TRAINER_TERU                             1640
#define TRAINER_JASMINE_1_3                      1641
#define TRAINER_JENN                             1642
#define TRAINER_COREY                            1643
#define TRAINER_DENIS                            1644
#define TRAINER_DANIEL                           1645
#define TRAINER_NAOKO                            1646
#define TRAINER_NATHAN                           1647
#define TRAINER_NEAL                             1648
#define TRAINER_NICK                             1649
#define TRAINER_NICO                             1650
#define TRAINER_RED_2                            1651
#define TRAINER_GAVEN                            1652
#define TRAINER_GINA                             1653
#define TRAINER_GORDON                           1654
#define TRAINER_BENJAMIN                         1655
#define TRAINER_RIVAL_CHIKORITA_1                1656
#define TRAINER_RIVAL_CHIKORITA_2                1657
#define TRAINER_RIVAL_CHIKORITA_3                1658
#define TRAINER_PING                             1659
#define TRAINER_PETREL_2                         1660
#define TRAINER_PROTON_2                         1661
#define TRAINER_GRUNT_26                         1662
#define TRAINER_EUGENE                           1663
#define TRAINER_RIVAL_TOTODILE_3                 1664
#define TRAINER_KENNETH                          1665
#define TRAINER_FRAN                             1666
#define TRAINER_FRITZ                            1667
#define TRAINER_CYBIL                            1668
#define TRAINER_MATHEW                           1669
#define TRAINER_MEG_AND_PEG                      1670
#define TRAINER_MEGAN                            1671
#define TRAINER_MICHAEL                          1672
#define TRAINER_RIVAL_CYNDAQUIL_2                1673
#define TRAINER_ABE                              1674
#define TRAINER_AL                               1675
#define TRAINER_ALFRED                           1676
#define TRAINER_ANDRE                            1677
#define TRAINER_LI                               1678
#define TRAINER_LIZ                              1679
#define TRAINER_GARRETT                          1680
#define TRAINER_KIM                              1681
#define TRAINER_LOIS                             1682
#define TRAINER_KENJI                            1683
#define TRAINER_GRUNT_28                         1684
#define TRAINER_JAKE                             1685
#define TRAINER_CHUCK_1_2                        1686
#define TRAINER_ARCHER                           1687
#define TRAINER_DARIN                            1688
#define TRAINER_GRUNT_8                          1689
#define TRAINER_KEITH                            1690
#define TRAINER_KELLY                            1691
#define TRAINER_KEN                              1692
#define TRAINER_AMY_AND_MAY                      1693
#define TRAINER_ANN_AND_ANNE                     1694
#define TRAINER_RUTH                             1695
#define TRAINER_RYAN                             1696
#define TRAINER_MIKE                             1697
#define TRAINER_MIKEY                            1698
#define TRAINER_MIKI                             1699
#define TRAINER_MILLER                           1700
#define TRAINER_CARRIE                           1701
#define TRAINER_RIVAL_TOTODILE_4                 1702
#define TRAINER_CLYDE                            1703
#define TRAINER_CHUCK_1                          1704
#define TRAINER_GRUNT_27                         1705
#define TRAINER_LOLA                             1706
#define TRAINER_JASMINE_1                        1707
#define TRAINER_MARKUS                           1708
#define TRAINER_THOM_AND_KAE                     1709
#define TRAINER_DUFF_AND_EDA                     1710
#define TRAINER_CHUCK_1_3                        1711
#define TRAINER_CLAIR_1                          1712
#define TRAINER_PRYCE_1                          1713
#define TRAINER_RIVAL_CHIKORITA_4                1714
#define TRAINER_RIVAL_CYNDAQUIL_1                1715
#define TRAINER_GRUNT_3                          1716
#define TRAINER_EUSINE                           1717
#define TRAINER_GRUNT_4                          1718
#define TRAINER_GRUNT_5                          1719
#define TRAINER_GRUNT_6                          1720
#define TRAINER_GRUNT_7                          1721
#define TRAINER_VANCE                            1722
#define TRAINER_TOBY                             1723
#define TRAINER_TERRELL                          1724
#define TRAINER_CHOW                             1725
#define TRAINER_PRYCE_1_2                        1726
#define TRAINER_THEO                             1727
#define TRAINER_WALT                             1728
#define TRAINER_WILTON                           1729
#define TRAINER_YOSHI                            1730
#define TRAINER_ZACH                             1731
#define TRAINER_BUGSY_1                          1732
#define TRAINER_WHITNEY_1                        1733
#define TRAINER_RIVAL_TOTODILE_1                 1734
#define TRAINER_MORTY_1                          1735
#define TRAINER_JAMIE                            1736
#define TRAINER_BRIAN                            1737
#define TRAINER_HARRY                            1738
#define TRAINER_RIVAL_CYNDAQUIL_4                1739
#define TRAINER_RIVAL_TOTODILE_2                 1740
#define TRAINER_ELLIOT                           1741
#define TRAINER_RUSSELL                          1742
#define TRAINER_JASMINE_1_2                      1743
#define TRAINER_RAY                              1744
#define TRAINER_BAILEY                           1745
#define TRAINER_GRUNT_11                         1746
#define TRAINER_BRAD                             1747
#define TRAINER_GRUNT_10                         1748
#define TRAINER_PRYCE_1_3                        1749
#define TRAINER_CARA                             1750
#define TRAINER_RICHARDO                         1751
#define TRAINER_NARD                             1752
#define TRAINER_GRUNT_2                          1753
#define TRAINER_MARVIN                           1754
#define TRAINER_GRUNT_9                          1755
#define TRAINER_ETHAN                            1756
#define TRAINER_RIVAL_CYNDAQUIL_3                1757
#define TRAINER_BILL                             1758
#define TRAINER_KATE                             1759
#define TRAINER_ARNIE                            1760
#define TRAINER_NOB                              1761
#define TRAINER_ETO                              1762
#define TRAINER_DIRK                             1763
#define TRAINER_DON                              1764
#define TRAINER_ETO_3                            1765
#define TRAINER_QUENTIN                          1766
#define TRAINER_RALPH                            1767
#define TRAINER_JIN                              1768
#define TRAINER_BROOKE                           1769
#define TRAINER_CALVIN                           1770
#define TRAINER_IAN                              1771
#define TRAINER_IRWIN                            1772
#define TRAINER_ISSAC                            1773
#define TRAINER_PARRY                            1774
#define TRAINER_PETER                            1775
#define TRAINER_RON                              1776
#define TRAINER_ROXANNE                          1777
#define TRAINER_GRUNT_12                         1778
#define TRAINER_PROTON_1                         1779

// Johto trainers reusing vanilla names (separate ids, Hoenn preserved)
#define TRAINER_JOHTO_AARON                      1780
#define TRAINER_JOHTO_ALAN                       1781
#define TRAINER_JOHTO_ALBERT                     1782
#define TRAINER_JOHTO_ALLEN                      1783
#define TRAINER_JOHTO_ANDREW                     1784
#define TRAINER_JOHTO_ANTHONY                    1785
#define TRAINER_JOHTO_BEN                        1786
#define TRAINER_JOHTO_BENNY                      1787
#define TRAINER_JOHTO_BERKE                      1788
#define TRAINER_JOHTO_BETH                       1789
#define TRAINER_JOHTO_BEVERLY                    1790
#define TRAINER_JOHTO_BLAKE                      1791
#define TRAINER_JOHTO_BRANDON                    1792
#define TRAINER_JOHTO_BRENT                      1793
#define TRAINER_JOHTO_BRIDGET                    1794
#define TRAINER_JOHTO_BRYAN                      1795
#define TRAINER_JOHTO_CAROL                      1796
#define TRAINER_JOHTO_CHAD                       1797
#define TRAINER_JOHTO_CHARLIE                    1798
#define TRAINER_JOHTO_CLARISSA                   1799
#define TRAINER_JOHTO_COLIN                      1800
#define TRAINER_JOHTO_CONNIE                     1801
#define TRAINER_JOHTO_DANA                       1802
#define TRAINER_JOHTO_DEBRA                      1803
#define TRAINER_JOHTO_DENISE                     1804
#define TRAINER_JOHTO_DEREK                      1805
#define TRAINER_JOHTO_DOUGLAS                    1806
#define TRAINER_JOHTO_EDGAR                      1807
#define TRAINER_JOHTO_EDMOND                     1808
#define TRAINER_JOHTO_EDWARD                     1809
#define TRAINER_JOHTO_GEORGE                     1810
#define TRAINER_JOHTO_GILBERT                    1811
#define TRAINER_JOHTO_GRACE                      1812
#define TRAINER_JOHTO_GREG                       1813
#define TRAINER_JOHTO_GWEN                       1814
#define TRAINER_JOHTO_HENRY                      1815
#define TRAINER_JOHTO_HUEY                       1816
#define TRAINER_JOHTO_HUGH                       1817
#define TRAINER_JOHTO_IRENE                      1818
#define TRAINER_JOHTO_IVAN                       1819
#define TRAINER_JOHTO_JACK                       1820
#define TRAINER_JOHTO_JEFF                       1821
#define TRAINER_JOHTO_JOEY                       1822
#define TRAINER_JOHTO_JONAH                      1823
#define TRAINER_JOHTO_JOSE                       1824
#define TRAINER_JOHTO_JOSH                       1825
#define TRAINER_JOHTO_JUSTIN                     1826
#define TRAINER_JOHTO_KARA                       1827
#define TRAINER_JOHTO_KAYLEE                     1828
#define TRAINER_JOHTO_KENT                       1829
#define TRAINER_JOHTO_KIRK                       1830
#define TRAINER_JOHTO_KIYO                       1831
#define TRAINER_JOHTO_LARRY                      1832
#define TRAINER_JOHTO_LEONARD                    1833
#define TRAINER_JOHTO_LUNG                       1834
#define TRAINER_JOHTO_LYLE                       1835
#define TRAINER_JOHTO_MARC                       1836
#define TRAINER_JOHTO_MARK                       1837
#define TRAINER_JOHTO_MARTHA                     1838
#define TRAINER_JOHTO_NATE                       1839
#define TRAINER_JOHTO_NOLAND                     1840
#define TRAINER_JOHTO_OLIVIA                     1841
#define TRAINER_JOHTO_PAUL                       1842
#define TRAINER_JOHTO_PAULA                      1843
#define TRAINER_JOHTO_PHIL                       1844
#define TRAINER_JOHTO_PHILLIP                    1845
#define TRAINER_JOHTO_PRESTON                    1846
#define TRAINER_JOHTO_RANDALL                    1847
#define TRAINER_JOHTO_RICHARD                    1848
#define TRAINER_JOHTO_ROLAND                     1849
#define TRAINER_JOHTO_RONALD                     1850
#define TRAINER_JOHTO_SAMANTHA                   1851
#define TRAINER_JOHTO_SAMUEL                     1852
#define TRAINER_JOHTO_SHANE                      1853
#define TRAINER_JOHTO_SHIRLEY                    1854
#define TRAINER_JOHTO_SIMON                      1855
#define TRAINER_JOHTO_SPENCER                    1856
#define TRAINER_JOHTO_STAN                       1857
#define TRAINER_JOHTO_SUSIE                      1858
#define TRAINER_JOHTO_TED                        1859
#define TRAINER_JOHTO_TIFFANY                    1860
#define TRAINER_JOHTO_VICTORIA                   1861
#define TRAINER_JOHTO_WADE                       1862
#define TRAINER_JOHTO_WAYNE                      1863
#define TRAINER_JOHTO_WENDY                      1864
#define TRAINER_JOHTO_WILLIAM                    1865

#define TRAINERS_COUNT                      1866
#define MAX_TRAINERS_COUNT                  1866
