// Kanto Trainers
#define TRAINER_BEAUTY_BRIDGET                             858
#define TRAINER_BEAUTY_LORI                                859
#define TRAINER_BEAUTY_TAMIA                               860
#define TRAINER_BIKER_GOON                                 861
#define TRAINER_BIKER_GOON_2                               862
#define TRAINER_BIKER_GOON_3                               863
#define TRAINER_BLACK_BELT_AARON                           864
#define TRAINER_BLACK_BELT_ATSUSHI                         865
#define TRAINER_BLACK_BELT_DAISUKE                         866
#define TRAINER_BLACK_BELT_HIDEKI                          867
#define TRAINER_BLACK_BELT_HITOSHI                         868
#define TRAINER_BLACK_BELT_KIYO                            869
#define TRAINER_BLACK_BELT_KOICHI                          870
#define TRAINER_BLACK_BELT_MIKE                            871
#define TRAINER_BLACK_BELT_TAKASHI                         872
#define TRAINER_BOSS_GIOVANNI                              873
#define TRAINER_BOSS_GIOVANNI_2                            874
#define TRAINER_BUG_CATCHER_ANTHONY                        875
#define TRAINER_BUG_CATCHER_CHARLIE                        876
#define TRAINER_BUG_CATCHER_DOUG                           877
#define TRAINER_BUG_CATCHER_GARRET                         878
#define TRAINER_BUG_CATCHER_JONAH                          879
#define TRAINER_BUG_CATCHER_KENT                           880
#define TRAINER_BUG_CATCHER_RICK                           881
#define TRAINER_BUG_CATCHER_ROBBY                          882
#define TRAINER_BUG_CATCHER_SAMMY                          883
#define TRAINER_BUG_CATCHER_VANCE                          884
#define TRAINER_BURGLAR_ARNIE                              885
#define TRAINER_BURGLAR_DUSTY                              886
#define TRAINER_BURGLAR_LEWIS                              887
#define TRAINER_BURGLAR_QUINN                              888
#define TRAINER_BURGLAR_RAMON                              889
#define TRAINER_BURGLAR_SIMON                              890
#define TRAINER_CAMPER_LIAM                                891
#define TRAINER_CAMPER_RILEY                               892
#define TRAINER_CHAMPION_FIRST_BULBASAUR                   893
#define TRAINER_CHAMPION_FIRST_CHARMANDER                  894
#define TRAINER_CHAMPION_FIRST_SQUIRTLE                    895
#define TRAINER_CHAMPION_REMATCH_BULBASAUR                 896
#define TRAINER_CHAMPION_REMATCH_CHARMANDER                897
#define TRAINER_CHAMPION_REMATCH_SQUIRTLE                  898
#define TRAINER_CHANNELER_AMANDA                           899
#define TRAINER_CHANNELER_ANGELICA                         900
#define TRAINER_CHANNELER_CARLY                            901
#define TRAINER_CHANNELER_EMILIA                           902
#define TRAINER_CHANNELER_HOPE                             903
#define TRAINER_CHANNELER_JANAE                            904
#define TRAINER_CHANNELER_JENNIFER                         905
#define TRAINER_CHANNELER_JODY                             906
#define TRAINER_CHANNELER_KARINA                           907
#define TRAINER_CHANNELER_LAUREL                           908
#define TRAINER_CHANNELER_PATRICIA                         909
#define TRAINER_CHANNELER_PAULA                            910
#define TRAINER_CHANNELER_RUTH                             911
#define TRAINER_CHANNELER_STACY                            912
#define TRAINER_CHANNELER_TAMMY                            913
#define TRAINER_CHANNELER_TASHA                            914
#define TRAINER_COOLTRAINER_ALEXA                          915
#define TRAINER_COOLTRAINER_CAROLINE                       916
#define TRAINER_COOLTRAINER_COLBY                          917
#define TRAINER_COOLTRAINER_GEORGE                         918
#define TRAINER_COOLTRAINER_MARY                           919
#define TRAINER_COOLTRAINER_SAMUEL                         920
#define TRAINER_COOLTRAINER_WARREN                         921
#define TRAINER_COOLTRAINER_YUJI                           922
#define TRAINER_COOL_COUPLE_RAY_TYRA                       923
#define TRAINER_CRUSH_GIRL_JOCELYN                         924
#define TRAINER_CUE_BALL_PAXTON                            925
#define TRAINER_ELITE_FOUR_AGATHA                          926
#define TRAINER_ELITE_FOUR_AGATHA_2                        927
#define TRAINER_ELITE_FOUR_BRUNO                           928
#define TRAINER_ELITE_FOUR_BRUNO_2                         929
#define TRAINER_ELITE_FOUR_LANCE                           930
#define TRAINER_ELITE_FOUR_LANCE_2                         931
#define TRAINER_ELITE_FOUR_LORELEI                         932
#define TRAINER_ELITE_FOUR_LORELEI_2                       933
#define TRAINER_ENGINEER_BAILY                             934
#define TRAINER_FISHERMAN_BARNY                            935
#define TRAINER_FISHERMAN_DALE                             936
#define TRAINER_GENTLEMAN_ARTHUR                           937
#define TRAINER_GENTLEMAN_BROOKS                           938
#define TRAINER_GENTLEMAN_LAMAR                            939
#define TRAINER_GENTLEMAN_THOMAS                           940
#define TRAINER_GENTLEMAN_TUCKER                           941
#define TRAINER_HIKER_ALLEN                                942
#define TRAINER_HIKER_DUDLEY                               943
#define TRAINER_HIKER_ERIC                                 944
#define TRAINER_HIKER_LENNY                                945
#define TRAINER_HIKER_LUCAS                                946
#define TRAINER_HIKER_MARCOS                               947
#define TRAINER_HIKER_OLIVER                               948
#define TRAINER_JUGGLER_DALTON                             949
#define TRAINER_JUGGLER_GREGORY                            950
#define TRAINER_JUGGLER_KAYDEN                             951
#define TRAINER_JUGGLER_KIRK                               952
#define TRAINER_JUGGLER_NATE                               953
#define TRAINER_JUGGLER_NELSON                             954
#define TRAINER_JUGGLER_SHAWN                              955
#define TRAINER_LADY_SELPHY                                956
#define TRAINER_LASS_ANN                                   957
#define TRAINER_LASS_DALIA                                 958
#define TRAINER_LASS_DAWN                                  959
#define TRAINER_LASS_IRIS                                  960
#define TRAINER_LASS_JOANA                                 961
#define TRAINER_LASS_KAY                                   962
#define TRAINER_LASS_LISA                                  963
#define TRAINER_LASS_MIRIAM                                964
#define TRAINER_LEADER_BLAINE                              965
#define TRAINER_LEADER_BROCK                               966
#define TRAINER_LEADER_ERIKA                               967
#define TRAINER_LEADER_GIOVANNI                            968
#define TRAINER_LEADER_KOGA                                969
#define TRAINER_LEADER_LT_SURGE                            970
#define TRAINER_LEADER_MISTY                               971
#define TRAINER_LEADER_SABRINA                             972
#define TRAINER_PICNICKER_ARIANA                           973
#define TRAINER_PICNICKER_DANA                             974
#define TRAINER_PICNICKER_DIANA                            975
#define TRAINER_PICNICKER_LEAH                             976
#define TRAINER_PICNICKER_MARCY                            977
#define TRAINER_PICNICKER_MARTHA                           978
#define TRAINER_PICNICKER_SOFIA                            979
#define TRAINER_PICNICKER_TINA                             980
#define TRAINER_PKMN_BREEDER_ALLISON                       981
#define TRAINER_PKMN_BREEDER_BETHANY                       982
#define TRAINER_PKMN_RANGER_BETH                           983
#define TRAINER_PKMN_RANGER_LOGAN                          984
#define TRAINER_POKEMANIAC_ASHTON                          985
#define TRAINER_POKEMANIAC_COOPER                          986
#define TRAINER_POKEMANIAC_DAWSON                          987
#define TRAINER_POKEMANIAC_STEVE                           988
#define TRAINER_POKEMANIAC_WINSTON                         989
#define TRAINER_PSYCHIC_CAMERON                            990
#define TRAINER_PSYCHIC_JOHAN                              991
#define TRAINER_PSYCHIC_LAURA                              992
#define TRAINER_PSYCHIC_PRESTON                            993
#define TRAINER_PSYCHIC_TYRON                              994
#define TRAINER_RIVAL_CERULEAN_BULBASAUR                   995
#define TRAINER_RIVAL_CERULEAN_CHARMANDER                  996
#define TRAINER_RIVAL_CERULEAN_SQUIRTLE                    997
#define TRAINER_RIVAL_OAKS_LAB_BULBASAUR                   998
#define TRAINER_RIVAL_OAKS_LAB_CHARMANDER                  999
#define TRAINER_RIVAL_OAKS_LAB_SQUIRTLE                    1000
#define TRAINER_RIVAL_POKEMON_TOWER_BULBASAUR              1001
#define TRAINER_RIVAL_POKEMON_TOWER_CHARMANDER             1002
#define TRAINER_RIVAL_POKEMON_TOWER_SQUIRTLE               1003
#define TRAINER_RIVAL_ROUTE22_EARLY_BULBASAUR              1004
#define TRAINER_RIVAL_ROUTE22_EARLY_CHARMANDER             1005
#define TRAINER_RIVAL_ROUTE22_EARLY_SQUIRTLE               1006
#define TRAINER_RIVAL_ROUTE22_LATE_BULBASAUR               1007
#define TRAINER_RIVAL_ROUTE22_LATE_CHARMANDER              1008
#define TRAINER_RIVAL_ROUTE22_LATE_SQUIRTLE                1009
#define TRAINER_RIVAL_SILPH_BULBASAUR                      1010
#define TRAINER_RIVAL_SILPH_CHARMANDER                     1011
#define TRAINER_RIVAL_SILPH_SQUIRTLE                       1012
#define TRAINER_RIVAL_SS_ANNE_BULBASAUR                    1013
#define TRAINER_RIVAL_SS_ANNE_CHARMANDER                   1014
#define TRAINER_RIVAL_SS_ANNE_SQUIRTLE                     1015
#define TRAINER_RUIN_MANIAC_LAWSON                         1016
#define TRAINER_RUIN_MANIAC_LAYTON                         1017
#define TRAINER_SAILOR_DUNCAN                              1018
#define TRAINER_SAILOR_DWAYNE                              1019
#define TRAINER_SAILOR_DYLAN                               1020
#define TRAINER_SAILOR_EDMOND                              1021
#define TRAINER_SAILOR_HUEY                                1022
#define TRAINER_SAILOR_LEONARD                             1023
#define TRAINER_SAILOR_PHILLIP                             1024
#define TRAINER_SAILOR_TREVOR                              1025
#define TRAINER_SCIENTIST_BEAU                             1026
#define TRAINER_SCIENTIST_BRAYDON                          1027
#define TRAINER_SCIENTIST_CONNOR                           1028
#define TRAINER_SCIENTIST_ED                               1029
#define TRAINER_SCIENTIST_GIDEON                           1030
#define TRAINER_SCIENTIST_IVAN                             1031
#define TRAINER_SCIENTIST_JERRY                            1032
#define TRAINER_SCIENTIST_JOSE                             1033
#define TRAINER_SCIENTIST_JOSHUA                           1034
#define TRAINER_SCIENTIST_PARKER                           1035
#define TRAINER_SCIENTIST_RODNEY                           1036
#define TRAINER_SCIENTIST_TAYLOR                           1037
#define TRAINER_SCIENTIST_TED                              1038
#define TRAINER_SCIENTIST_TRAVIS                           1039
#define TRAINER_SUPER_NERD_AVERY                           1040
#define TRAINER_SUPER_NERD_DEREK                           1041
#define TRAINER_SUPER_NERD_ERIK                            1042
#define TRAINER_SUPER_NERD_JOVAN                           1043
#define TRAINER_SUPER_NERD_MIGUEL                          1044
#define TRAINER_SUPER_NERD_ZAC                             1045
#define TRAINER_SWIMMER_MALE_LUIS                          1046
#define TRAINER_TAMER_COLE                                 1047
#define TRAINER_TAMER_EDGAR                                1048
#define TRAINER_TAMER_JASON                                1049
#define TRAINER_TAMER_PHIL                                 1050
#define TRAINER_TAMER_VINCENT                              1051
#define TRAINER_TEAM_ROCKET_ADMIN                          1052
#define TRAINER_TEAM_ROCKET_ADMIN_2                        1053
#define TRAINER_TEAM_ROCKET_GRUNT                          1054
#define TRAINER_TEAM_ROCKET_GRUNT_10                       1055
#define TRAINER_TEAM_ROCKET_GRUNT_11                       1056
#define TRAINER_TEAM_ROCKET_GRUNT_12                       1057
#define TRAINER_TEAM_ROCKET_GRUNT_13                       1058
#define TRAINER_TEAM_ROCKET_GRUNT_14                       1059
#define TRAINER_TEAM_ROCKET_GRUNT_15                       1060
#define TRAINER_TEAM_ROCKET_GRUNT_16                       1061
#define TRAINER_TEAM_ROCKET_GRUNT_17                       1062
#define TRAINER_TEAM_ROCKET_GRUNT_18                       1063
#define TRAINER_TEAM_ROCKET_GRUNT_19                       1064
#define TRAINER_TEAM_ROCKET_GRUNT_2                        1065
#define TRAINER_TEAM_ROCKET_GRUNT_20                       1066
#define TRAINER_TEAM_ROCKET_GRUNT_21                       1067
#define TRAINER_TEAM_ROCKET_GRUNT_23                       1068
#define TRAINER_TEAM_ROCKET_GRUNT_24                       1069
#define TRAINER_TEAM_ROCKET_GRUNT_25                       1070
#define TRAINER_TEAM_ROCKET_GRUNT_26                       1071
#define TRAINER_TEAM_ROCKET_GRUNT_27                       1072
#define TRAINER_TEAM_ROCKET_GRUNT_28                       1073
#define TRAINER_TEAM_ROCKET_GRUNT_29                       1074
#define TRAINER_TEAM_ROCKET_GRUNT_3                        1075
#define TRAINER_TEAM_ROCKET_GRUNT_30                       1076
#define TRAINER_TEAM_ROCKET_GRUNT_31                       1077
#define TRAINER_TEAM_ROCKET_GRUNT_32                       1078
#define TRAINER_TEAM_ROCKET_GRUNT_33                       1079
#define TRAINER_TEAM_ROCKET_GRUNT_34                       1080
#define TRAINER_TEAM_ROCKET_GRUNT_35                       1081
#define TRAINER_TEAM_ROCKET_GRUNT_36                       1082
#define TRAINER_TEAM_ROCKET_GRUNT_37                       1083
#define TRAINER_TEAM_ROCKET_GRUNT_38                       1084
#define TRAINER_TEAM_ROCKET_GRUNT_39                       1085
#define TRAINER_TEAM_ROCKET_GRUNT_4                        1086
#define TRAINER_TEAM_ROCKET_GRUNT_40                       1087
#define TRAINER_TEAM_ROCKET_GRUNT_41                       1088
#define TRAINER_TEAM_ROCKET_GRUNT_42                       1089
#define TRAINER_TEAM_ROCKET_GRUNT_43                       1090
#define TRAINER_TEAM_ROCKET_GRUNT_44                       1091
#define TRAINER_TEAM_ROCKET_GRUNT_45                       1092
#define TRAINER_TEAM_ROCKET_GRUNT_46                       1093
#define TRAINER_TEAM_ROCKET_GRUNT_47                       1094
#define TRAINER_TEAM_ROCKET_GRUNT_48                       1095
#define TRAINER_TEAM_ROCKET_GRUNT_49                       1096
#define TRAINER_TEAM_ROCKET_GRUNT_5                        1097
#define TRAINER_TEAM_ROCKET_GRUNT_50                       1098
#define TRAINER_TEAM_ROCKET_GRUNT_51                       1099
#define TRAINER_TEAM_ROCKET_GRUNT_6                        1100
#define TRAINER_TEAM_ROCKET_GRUNT_7                        1101
#define TRAINER_TEAM_ROCKET_GRUNT_8                        1102
#define TRAINER_TEAM_ROCKET_GRUNT_9                        1103
#define TRAINER_YOUNGSTER_CORDELL                          1104
#define TRAINER_YOUNGSTER_JOHNSON                          1105
#define TRAINER_YOUNGSTER_JOSH                             1106
#define TRAINER_YOUNGSTER_NASH                             1107
#define TRAINER_YOUNGSTER_TYLER                            1108

#define TRAINERS_COUNT                      1597
#define MAX_TRAINERS_COUNT                  1700
// Additional pokeorigin trainers
#define TRAINER_AQUA_ADMIN_MATT                            1109
#define TRAINER_AQUA_ADMIN_SHELLY                          1110
#define TRAINER_AQUA_GRUNT_F                               1111
#define TRAINER_AQUA_GRUNT_M                               1112
#define TRAINER_AQUA_LEADER                                1113
#define TRAINER_AROMA_LADY_MIAH                            1114
#define TRAINER_AROMA_LADY_NIKKI                           1115
#define TRAINER_AROMA_LADY_ROSE                            1116
#define TRAINER_AROMA_LADY_VIOLET                          1117
#define TRAINER_BATTLE_GIRL                                1118
#define TRAINER_BEAUTY_GRACE                               1119
#define TRAINER_BEAUTY_GRACE_2                             1120
#define TRAINER_BEAUTY_LAUREN                              1121
#define TRAINER_BEAUTY_LOLA                                1122
#define TRAINER_BEAUTY_OLIVIA                              1123
#define TRAINER_BEAUTY_SHEILA                              1124
#define TRAINER_BEAUTY_SHEILA_2                            1125
#define TRAINER_BIKER_1                                    1126
#define TRAINER_BIKER_2                                    1127
#define TRAINER_BIKER_ALEX                                 1128
#define TRAINER_BIKER_BILLY                                1129
#define TRAINER_BIKER_ERNEST                               1130
#define TRAINER_BIKER_GERALD                               1131
#define TRAINER_BIKER_HIDEO                                1132
#define TRAINER_BIKER_ISAAC                                1133
#define TRAINER_BIKER_JARED                                1134
#define TRAINER_BIKER_JAREN                                1135
#define TRAINER_BIKER_JAREN_2                              1136
#define TRAINER_BIKER_JAXON                                1137
#define TRAINER_BIKER_JAXON_2                              1138
#define TRAINER_BIKER_LAO                                  1139
#define TRAINER_BIKER_LUKAS                                1140
#define TRAINER_BIKER_LUKAS_2                              1141
#define TRAINER_BIKER_MALIK                                1142
#define TRAINER_BIKER_NIKOLAS                              1143
#define TRAINER_BIKER_RICARDO                              1144
#define TRAINER_BIKER_RUBEN                                1145
#define TRAINER_BIKER_RUBEN_2                              1146
#define TRAINER_BIKER_VIRGIL                               1147
#define TRAINER_BIKER_WILLIAM                              1148
#define TRAINER_BIRD_KEEPER_BECK                           1149
#define TRAINER_BIRD_KEEPER_BENNY                          1150
#define TRAINER_BIRD_KEEPER_BENNY_2                        1151
#define TRAINER_BIRD_KEEPER_BENNY_3                        1152
#define TRAINER_BIRD_KEEPER_CARTER                         1153
#define TRAINER_BIRD_KEEPER_CHAZ                           1154
#define TRAINER_BIRD_KEEPER_CHAZ_2                         1155
#define TRAINER_BIRD_KEEPER_CHESTER                        1156
#define TRAINER_BIRD_KEEPER_CHESTER_2                      1157
#define TRAINER_BIRD_KEEPER_CHESTER_3                      1158
#define TRAINER_BIRD_KEEPER_DONALD                         1159
#define TRAINER_BIRD_KEEPER_EDWIN                          1160
#define TRAINER_BIRD_KEEPER_HAROLD                         1161
#define TRAINER_BIRD_KEEPER_HAROLD_2                       1162
#define TRAINER_BIRD_KEEPER_JACOB                          1163
#define TRAINER_BIRD_KEEPER_JACOB_2                        1164
#define TRAINER_BIRD_KEEPER_JACOB_3                        1165
#define TRAINER_BIRD_KEEPER_KEITH                          1166
#define TRAINER_BIRD_KEEPER_MARLON                         1167
#define TRAINER_BIRD_KEEPER_MARLON_2                       1168
#define TRAINER_BIRD_KEEPER_MARLON_3                       1169
#define TRAINER_BIRD_KEEPER_MILO                           1170
#define TRAINER_BIRD_KEEPER_MILO_2                         1171
#define TRAINER_BIRD_KEEPER_MITCH                          1172
#define TRAINER_BIRD_KEEPER_PERRY                          1173
#define TRAINER_BIRD_KEEPER_RAMIRO                         1174
#define TRAINER_BIRD_KEEPER_REED                           1175
#define TRAINER_BIRD_KEEPER_ROBERT                         1176
#define TRAINER_BIRD_KEEPER_ROBERT_2                       1177
#define TRAINER_BIRD_KEEPER_ROBERT_3                       1178
#define TRAINER_BIRD_KEEPER_ROGER                          1179
#define TRAINER_BIRD_KEEPER_SEBASTIAN                      1180
#define TRAINER_BIRD_KEEPER_WILTON                         1181
#define TRAINER_BLACK_BELT_HUGH                            1182
#define TRAINER_BLACK_BELT_HUGH_2                          1183
#define TRAINER_BLACK_BELT_HUGH_3                          1184
#define TRAINER_BLACK_BELT_SHEA                            1185
#define TRAINER_BLACK_BELT_SHEA_2                          1186
#define TRAINER_BLACK_BELT_SHEA_3                          1187
#define TRAINER_BOARDER_F                                  1188
#define TRAINER_BOARDER_M                                  1189
#define TRAINER_BRENDAN                                    1190
#define TRAINER_BRENDAN_2                                  1191
#define TRAINER_BRENDAN_3                                  1192
#define TRAINER_BUG_CATCHER_2                              1193
#define TRAINER_BUG_CATCHER_3                              1194
#define TRAINER_BUG_CATCHER_4                              1195
#define TRAINER_BUG_CATCHER_5                              1196
#define TRAINER_BUG_CATCHER_6                              1197
#define TRAINER_BUG_CATCHER_7                              1198
#define TRAINER_BUG_CATCHER_8                              1199
#define TRAINER_BUG_CATCHER_BRENT                          1200
#define TRAINER_BUG_CATCHER_CALE                           1201
#define TRAINER_BUG_CATCHER_COLTON                         1202
#define TRAINER_BUG_CATCHER_COLTON_2                       1203
#define TRAINER_BUG_CATCHER_COLTON_3                       1204
#define TRAINER_BUG_CATCHER_COLTON_4                       1205
#define TRAINER_BUG_CATCHER_CONNER                         1206
#define TRAINER_BUG_CATCHER_ELIJAH                         1207
#define TRAINER_BUG_CATCHER_GREG                           1208
#define TRAINER_BUG_CATCHER_JAMES                          1209
#define TRAINER_BUG_CATCHER_KEIGO                          1210
#define TRAINER_BUG_MANIAC                                 1211
#define TRAINER_BURGLAR_1                                  1212
#define TRAINER_BURGLAR_2                                  1213
#define TRAINER_BURGLAR_3                                  1214
#define TRAINER_BURGLAR_4                                  1215
#define TRAINER_CAMPER_2                                   1216
#define TRAINER_CAMPER_BRYCE                               1217
#define TRAINER_CAMPER_CHRIS                               1218
#define TRAINER_CAMPER_CHRIS_2                             1219
#define TRAINER_CAMPER_CHRIS_3                             1220
#define TRAINER_CAMPER_CHRIS_4                             1221
#define TRAINER_CAMPER_DREW                                1222
#define TRAINER_CAMPER_ETHAN                               1223
#define TRAINER_CAMPER_FLINT                               1224
#define TRAINER_CAMPER_JEFF                                1225
#define TRAINER_CAMPER_JEFF_2                              1226
#define TRAINER_CAMPER_JEFF_3                              1227
#define TRAINER_CAMPER_JEFF_4                              1228
#define TRAINER_CAMPER_JUSTIN                              1229
#define TRAINER_CAMPER_RICKY                               1230
#define TRAINER_CAMPER_RICKY_2                             1231
#define TRAINER_CAMPER_RICKY_3                             1232
#define TRAINER_CAMPER_RICKY_4                             1233
#define TRAINER_CAMPER_SHANE                               1234
#define TRAINER_CHANNELER_1                                1235
#define TRAINER_CHANNELER_2                                1236
#define TRAINER_CHANNELER_3                                1237
#define TRAINER_CHANNELER_4                                1238
#define TRAINER_CHANNELER_5                                1239
#define TRAINER_CHANNELER_6                                1240
#define TRAINER_CHANNELER_7                                1241
#define TRAINER_CHANNELER_8                                1242
#define TRAINER_COLLECTOR                                  1243
#define TRAINER_COOLTRAINER_AUSTINA                        1244
#define TRAINER_COOLTRAINER_BERKE                          1245
#define TRAINER_COOLTRAINER_BROOKE                         1246
#define TRAINER_COOLTRAINER_GILBERT                        1247
#define TRAINER_COOLTRAINER_JULIE                          1248
#define TRAINER_COOLTRAINER_LEROY                          1249
#define TRAINER_COOLTRAINER_LEROY_2                        1250
#define TRAINER_COOLTRAINER_MICHELLE                       1251
#define TRAINER_COOLTRAINER_MICHELLE_2                     1252
#define TRAINER_COOLTRAINER_NAOMI                          1253
#define TRAINER_COOLTRAINER_OWEN                           1254
#define TRAINER_COOLTRAINER_PAUL                           1255
#define TRAINER_COOLTRAINER_ROLANDO                        1256
#define TRAINER_COOLTRAINER_SHANNON                        1257
#define TRAINER_COOL_COUPLE_LEX_NYA                        1258
#define TRAINER_COOL_COUPLE_LEX_NYA_2                      1259
#define TRAINER_CRUSH_GIRL_CYNDY                           1260
#define TRAINER_CRUSH_GIRL_CYNDY_2                         1261
#define TRAINER_CRUSH_GIRL_SHARON                          1262
#define TRAINER_CRUSH_GIRL_SHARON_2                        1263
#define TRAINER_CRUSH_GIRL_SHARON_3                        1264
#define TRAINER_CRUSH_GIRL_TANYA                           1265
#define TRAINER_CRUSH_GIRL_TANYA_2                         1266
#define TRAINER_CRUSH_GIRL_TANYA_3                         1267
#define TRAINER_CRUSH_KIN_MIK_KIA                          1268
#define TRAINER_CRUSH_KIN_MIK_KIA_2                        1269
#define TRAINER_CRUSH_KIN_MIK_KIA_3                        1270
#define TRAINER_CRUSH_KIN_RON_MYA                          1271
#define TRAINER_CRUSH_KIN_RON_MYA_2                        1272
#define TRAINER_CRUSH_KIN_RON_MYA_3                        1273
#define TRAINER_CRUSH_KIN_RON_MYA_4                        1274
#define TRAINER_CUE_BALL_CAMRON                            1275
#define TRAINER_CUE_BALL_CAMRON_2                          1276
#define TRAINER_CUE_BALL_CHASE                             1277
#define TRAINER_CUE_BALL_COREY                             1278
#define TRAINER_CUE_BALL_COREY_2                           1279
#define TRAINER_CUE_BALL_ISAIAH                            1280
#define TRAINER_CUE_BALL_ISAIAH_2                          1281
#define TRAINER_CUE_BALL_JAMAL                             1282
#define TRAINER_CUE_BALL_KOJI                              1283
#define TRAINER_CUE_BALL_LUKE                              1284
#define TRAINER_CUE_BALL_RAUL                              1285
#define TRAINER_CUE_BALL_ZEEK                              1286
#define TRAINER_CYCLING_TRIATHLETE_F                       1287
#define TRAINER_CYCLING_TRIATHLETE_M                       1288
#define TRAINER_DRAGON_TAMER                               1289
#define TRAINER_ELITE_FOUR_DRAKE                           1290
#define TRAINER_ELITE_FOUR_GLACIA                          1291
#define TRAINER_ELITE_FOUR_PHOEBE                          1292
#define TRAINER_ELITE_FOUR_SIDNEY                          1293
#define TRAINER_ENGINEER_BERNIE                            1294
#define TRAINER_ENGINEER_BERNIE_2                          1295
#define TRAINER_ENGINEER_BRAXTON                           1296
#define TRAINER_EXPERT_F                                   1297
#define TRAINER_EXPERT_M                                   1298
#define TRAINER_FISHERMAN_ANDREW                           1299
#define TRAINER_FISHERMAN_CHIP                             1300
#define TRAINER_FISHERMAN_CLAUDE                           1301
#define TRAINER_FISHERMAN_ELLIOT                           1302
#define TRAINER_FISHERMAN_ELLIOT_2                         1303
#define TRAINER_FISHERMAN_HANK                             1304
#define TRAINER_FISHERMAN_NED                              1305
#define TRAINER_FISHERMAN_NOLAN                            1306
#define TRAINER_FISHERMAN_RONALD                           1307
#define TRAINER_FISHERMAN_TOMMY                            1308
#define TRAINER_FISHERMAN_TYLOR                            1309
#define TRAINER_FISHERMAN_WADE                             1310
#define TRAINER_FISHERMAN_WADE_2                           1311
#define TRAINER_GAMER_1                                    1312
#define TRAINER_GAMER_DARIAN                               1313
#define TRAINER_GAMER_DARIAN_2                             1314
#define TRAINER_GAMER_DIRK                                 1315
#define TRAINER_GAMER_HUGO                                 1316
#define TRAINER_GAMER_JASPER                               1317
#define TRAINER_GAMER_RICH                                 1318
#define TRAINER_GAMER_RICH_2                               1319
#define TRAINER_GAMER_STAN                                 1320
#define TRAINER_GENTLEMAN_CLIFFORD                         1321
#define TRAINER_GENTLEMAN_NORTON                           1322
#define TRAINER_GENTLEMAN_WALTER                           1323
#define TRAINER_GUITARIST                                  1324
#define TRAINER_HEX_MANIAC                                 1325
#define TRAINER_HIKER_ALAN                                 1326
#define TRAINER_HIKER_BRICE                                1327
#define TRAINER_HIKER_CLARK                                1328
#define TRAINER_HIKER_DARYL                                1329
#define TRAINER_HIKER_EARL                                 1330
#define TRAINER_HIKER_EARL_2                               1331
#define TRAINER_HIKER_FRANKLIN                             1332
#define TRAINER_HIKER_FRANKLIN_2                           1333
#define TRAINER_HIKER_JEREMY                               1334
#define TRAINER_HIKER_JEREMY_2                             1335
#define TRAINER_HIKER_NOB                                  1336
#define TRAINER_HIKER_TRENT                                1337
#define TRAINER_HIKER_TRENT_2                              1338
#define TRAINER_HIKER_WAYNE                                1339
#define TRAINER_INTERVIEWER                                1340
#define TRAINER_JUGGLER_EDWARD                             1341
#define TRAINER_JUGGLER_MASON                              1342
#define TRAINER_JUGGLER_MASON_2                            1343
#define TRAINER_KINDLER                                    1344
#define TRAINER_LADY_GILLIAN                               1345
#define TRAINER_LADY_JACKI                                 1346
#define TRAINER_LASS_2                                     1347
#define TRAINER_LASS_ALI                                   1348
#define TRAINER_LASS_ANDREA                                1349
#define TRAINER_LASS_CRISSY                                1350
#define TRAINER_LASS_HALEY                                 1351
#define TRAINER_LASS_JANICE                                1352
#define TRAINER_LASS_JANICE_2                              1353
#define TRAINER_LASS_JANICE_3                              1354
#define TRAINER_LASS_JULIA                                 1355
#define TRAINER_LASS_MEGAN                                 1356
#define TRAINER_LASS_MEGAN_2                               1357
#define TRAINER_LASS_MEGAN_3                               1358
#define TRAINER_LASS_PAIGE                                 1359
#define TRAINER_LASS_RELI                                  1360
#define TRAINER_LASS_RELI_2                                1361
#define TRAINER_LASS_RELI_3                                1362
#define TRAINER_LASS_ROBIN                                 1363
#define TRAINER_LASS_SALLY                                 1364
#define TRAINER_LEADER_BRAWLY                              1365
#define TRAINER_LEADER_FLANNERY                            1366
#define TRAINER_LEADER_NORMAN                              1367
#define TRAINER_LEADER_ROXANNE                             1368
#define TRAINER_LEADER_TATE_LIZA                           1369
#define TRAINER_LEADER_WALLACE                             1370
#define TRAINER_LEADER_WATTSON                             1371
#define TRAINER_LEADER_WINONA                              1372
#define TRAINER_MAGMA_ADMIN_COURTNEY                       1373
#define TRAINER_MAGMA_ADMIN_TABITHA                        1374
#define TRAINER_MAGMA_GRUNT_M                              1375
#define TRAINER_MAGMA_LEADER                               1376
#define TRAINER_MAMGA_GRUNT_F                              1377
#define TRAINER_MAY                                        1378
#define TRAINER_MAY_2                                      1379
#define TRAINER_MAY_3                                      1380
#define TRAINER_NINJA_BOY                                  1381
#define TRAINER_OLD_COUPLE                                 1382
#define TRAINER_PAINTER_CELINA                             1383
#define TRAINER_PAINTER_DAISY                              1384
#define TRAINER_PAINTER_EDNA                               1385
#define TRAINER_PAINTER_RAYNA                              1386
#define TRAINER_PAINTER_RAYNA_2                            1387
#define TRAINER_PARASOL_LADY                               1388
#define TRAINER_PICNICKER_ALICIA                           1389
#define TRAINER_PICNICKER_ALICIA_2                         1390
#define TRAINER_PICNICKER_ALICIA_3                         1391
#define TRAINER_PICNICKER_ALICIA_4                         1392
#define TRAINER_PICNICKER_ALMA                             1393
#define TRAINER_PICNICKER_BECKY                            1394
#define TRAINER_PICNICKER_BECKY_2                          1395
#define TRAINER_PICNICKER_BECKY_3                          1396
#define TRAINER_PICNICKER_BECKY_4                          1397
#define TRAINER_PICNICKER_CAITLIN                          1398
#define TRAINER_PICNICKER_CAROL                            1399
#define TRAINER_PICNICKER_CELIA                            1400
#define TRAINER_PICNICKER_CLAIRE                           1401
#define TRAINER_PICNICKER_GWEN                             1402
#define TRAINER_PICNICKER_HANNAH                           1403
#define TRAINER_PICNICKER_HEIDI                            1404
#define TRAINER_PICNICKER_IRENE                            1405
#define TRAINER_PICNICKER_ISABELLE                         1406
#define TRAINER_PICNICKER_ISABELLE_2                       1407
#define TRAINER_PICNICKER_ISABELLE_3                       1408
#define TRAINER_PICNICKER_ISABELLE_4                       1409
#define TRAINER_PICNICKER_KELSEY                           1410
#define TRAINER_PICNICKER_KELSEY_2                         1411
#define TRAINER_PICNICKER_KELSEY_3                         1412
#define TRAINER_PICNICKER_KELSEY_4                         1413
#define TRAINER_PICNICKER_KINDRA                           1414
#define TRAINER_PICNICKER_MISSY                            1415
#define TRAINER_PICNICKER_MISSY_2                          1416
#define TRAINER_PICNICKER_MISSY_3                          1417
#define TRAINER_PICNICKER_NANCY                            1418
#define TRAINER_PICNICKER_SUSIE                            1419
#define TRAINER_PICNICKER_SUSIE_2                          1420
#define TRAINER_PICNICKER_SUSIE_3                          1421
#define TRAINER_PICNICKER_SUSIE_4                          1422
#define TRAINER_PICNICKER_VALERIE                          1423
#define TRAINER_PICNICKER_YAZMIN                           1424
#define TRAINER_PKMN_BREEDER_ALIZE                         1425
#define TRAINER_PKMN_BREEDER_ALIZE_2                       1426
#define TRAINER_PKMN_PROF_PROF_OAK                         1427
#define TRAINER_PKMN_RANGER_JACKSON                        1428
#define TRAINER_PKMN_RANGER_JACKSON_2                      1429
#define TRAINER_PKMN_RANGER_KATELYN                        1430
#define TRAINER_PKMN_RANGER_KATELYN_2                      1431
#define TRAINER_PKMN_RANGER_MADELINE                       1432
#define TRAINER_PKMN_RANGER_MADELINE_2                     1433
#define TRAINER_PKMN_RANGER_NICOLAS                        1434
#define TRAINER_PKMN_RANGER_NICOLAS_2                      1435
#define TRAINER_PLAYER_BRENDAN                             1436
#define TRAINER_PLAYER_LEAF                                1437
#define TRAINER_PLAYER_MAY                                 1438
#define TRAINER_PLAYER_RED                                 1439
#define TRAINER_POKEFAN_F                                  1440
#define TRAINER_POKEFAN_M                                  1441
#define TRAINER_POKEMANIAC_HECTOR                          1442
#define TRAINER_POKEMANIAC_HECTOR_2                        1443
#define TRAINER_POKEMANIAC_HERMAN                          1444
#define TRAINER_POKEMANIAC_HERMAN_2                        1445
#define TRAINER_POKEMANIAC_HERMAN_3                        1446
#define TRAINER_POKEMANIAC_MARK                            1447
#define TRAINER_POKEMANIAC_MARK_2                          1448
#define TRAINER_POKEMANIAC_MARK_3                          1449
#define TRAINER_PSYCHIC_DARIO                              1450
#define TRAINER_PSYCHIC_DARIO_2                            1451
#define TRAINER_PSYCHIC_JACLYN                             1452
#define TRAINER_PSYCHIC_JACLYN_2                           1453
#define TRAINER_PSYCHIC_RODETTE                            1454
#define TRAINER_PSYCHIC_RODETTE_2                          1455
#define TRAINER_RICH_BOY                                   1456
#define TRAINER_ROCKER_LUCA                                1457
#define TRAINER_ROCKER_LUCA_2                              1458
#define TRAINER_ROCKER_RANDALL                             1459
#define TRAINER_RS_AROMA_LADY                              1460
#define TRAINER_RS_BEAUTY                                  1461
#define TRAINER_RS_BIRD_KEEPER                             1462
#define TRAINER_RS_BLACK_BELT                              1463
#define TRAINER_RS_BUG_CATCHER                             1464
#define TRAINER_RS_CAMPER                                  1465
#define TRAINER_RS_CHAMPION                                1466
#define TRAINER_RS_COOLTRAINER_F                           1467
#define TRAINER_RS_COOLTRAINER_M                           1468
#define TRAINER_RS_FISHERMAN                               1469
#define TRAINER_RS_GENTLEMAN                               1470
#define TRAINER_RS_HIKER                                   1471
#define TRAINER_RS_LADY                                    1472
#define TRAINER_RS_LASS                                    1473
#define TRAINER_RS_PICNICKER                               1474
#define TRAINER_RS_PKMN_BREEDER_F                          1475
#define TRAINER_RS_PKMN_BREEDER_M                          1476
#define TRAINER_RS_PKMN_RANGER_F                           1477
#define TRAINER_RS_PKMN_RANGER_M                           1478
#define TRAINER_RS_POKEMANIAC                              1479
#define TRAINER_RS_PSYCHIC_F                               1480
#define TRAINER_RS_PSYCHIC_M                               1481
#define TRAINER_RS_RUIN_MANIAC                             1482
#define TRAINER_RS_SAILOR                                  1483
#define TRAINER_RS_SIS_AND_BRO                             1484
#define TRAINER_RS_SWIMMER_F                               1485
#define TRAINER_RS_SWIMMER_M                               1486
#define TRAINER_RS_TUBER_F                                 1487
#define TRAINER_RS_TUBER_M                                 1488
#define TRAINER_RS_TWINS                                   1489
#define TRAINER_RS_YOUNGSTER                               1490
#define TRAINER_RS_YOUNG_COUPLE                            1491
#define TRAINER_RUIN_MANIAC_BENJAMIN                       1492
#define TRAINER_RUIN_MANIAC_BRANDON                        1493
#define TRAINER_RUIN_MANIAC_FOSTER                         1494
#define TRAINER_RUIN_MANIAC_LARRY                          1495
#define TRAINER_RUIN_MANIAC_LARRY_2                        1496
#define TRAINER_RUIN_MANIAC_STANLY                         1497
#define TRAINER_RUNNING_TRIATHLETE_F                       1498
#define TRAINER_RUNNING_TRIATHLETE_M                       1499
#define TRAINER_SCHOOL_KID_F                               1500
#define TRAINER_SCHOOL_KID_M                               1501
#define TRAINER_SIS_AND_BRO_AVA_GEB                        1502
#define TRAINER_SIS_AND_BRO_LIA_LUC                        1503
#define TRAINER_SIS_AND_BRO_LIL_IAN                        1504
#define TRAINER_SIS_AND_BRO_LIL_IAN_2                      1505
#define TRAINER_SIS_AND_BRO_LIL_IAN_3                      1506
#define TRAINER_SR_AND_JR                                  1507
#define TRAINER_SUPER_NERD_1                               1508
#define TRAINER_SUPER_NERD_2                               1509
#define TRAINER_SUPER_NERD_3                               1510
#define TRAINER_SUPER_NERD_AIDAN                           1511
#define TRAINER_SUPER_NERD_GLENN                           1512
#define TRAINER_SUPER_NERD_GLENN_2                         1513
#define TRAINER_SUPER_NERD_LESLIE                          1514
#define TRAINER_SWIMMER_FEMALE_ABIGAIL                     1515
#define TRAINER_SWIMMER_FEMALE_ALICE                       1516
#define TRAINER_SWIMMER_FEMALE_ALICE_2                     1517
#define TRAINER_SWIMMER_FEMALE_AMARA                       1518
#define TRAINER_SWIMMER_FEMALE_ANYA                        1519
#define TRAINER_SWIMMER_FEMALE_CONNIE                      1520
#define TRAINER_SWIMMER_FEMALE_DENISE                      1521
#define TRAINER_SWIMMER_FEMALE_MARIA                       1522
#define TRAINER_SWIMMER_FEMALE_MELISSA                     1523
#define TRAINER_SWIMMER_FEMALE_MELISSA_2                   1524
#define TRAINER_SWIMMER_FEMALE_NICOLE                      1525
#define TRAINER_SWIMMER_FEMALE_NICOLE_2                    1526
#define TRAINER_SWIMMER_FEMALE_NORA                        1527
#define TRAINER_SWIMMER_FEMALE_SHIRLEY                     1528
#define TRAINER_SWIMMER_FEMALE_TIFFANY                     1529
#define TRAINER_SWIMMER_FEMALE_TISHA                       1530
#define TRAINER_SWIMMER_MALE_AXLE                          1531
#define TRAINER_SWIMMER_MALE_BARRY                         1532
#define TRAINER_SWIMMER_MALE_DARRIN                        1533
#define TRAINER_SWIMMER_MALE_DARRIN_2                      1534
#define TRAINER_SWIMMER_MALE_DAVID                         1535
#define TRAINER_SWIMMER_MALE_DEAN                          1536
#define TRAINER_SWIMMER_MALE_DOUGLAS                       1537
#define TRAINER_SWIMMER_MALE_FINN                          1538
#define TRAINER_SWIMMER_MALE_FINN_2                        1539
#define TRAINER_SWIMMER_MALE_GARRETT                       1540
#define TRAINER_SWIMMER_MALE_JACK                          1541
#define TRAINER_SWIMMER_MALE_JACK_2                        1542
#define TRAINER_SWIMMER_MALE_JEROME                        1543
#define TRAINER_SWIMMER_MALE_MATTHEW                       1544
#define TRAINER_SWIMMER_MALE_MATTHEW_2                     1545
#define TRAINER_SWIMMER_MALE_MYMO                          1546
#define TRAINER_SWIMMER_MALE_REECE                         1547
#define TRAINER_SWIMMER_MALE_RICHARD                       1548
#define TRAINER_SWIMMER_MALE_ROLAND                        1549
#define TRAINER_SWIMMER_MALE_SAMIR                         1550
#define TRAINER_SWIMMER_MALE_SAMIR_2                       1551
#define TRAINER_SWIMMER_MALE_SPENCER                       1552
#define TRAINER_SWIMMER_MALE_TOBY                          1553
#define TRAINER_SWIMMER_MALE_TONY                          1554
#define TRAINER_SWIMMER_MALE_TONY_2                        1555
#define TRAINER_SWIMMING_TRIATHLETE_F                      1556
#define TRAINER_SWIMMING_TRIATHLETE_M                      1557
#define TRAINER_TAMER_EVAN                                 1558
#define TRAINER_TAMER_EVAN_2                               1559
#define TRAINER_TAMER_JOHN                                 1560
#define TRAINER_TEAM_ROCKET_GRUNT_22                       1561
#define TRAINER_TUBER_ALEXIS                               1562
#define TRAINER_TUBER_AMIRA                                1563
#define TRAINER_TUBER_AMIRA_2                              1564
#define TRAINER_TWINS_ELI_ANNE                             1565
#define TRAINER_TWINS_ELI_ANNE_2                           1566
#define TRAINER_TWINS_JOY_MEG                              1567
#define TRAINER_TWINS_JOY_MEG_2                            1568
#define TRAINER_TWINS_KIRI_JAN                             1569
#define TRAINER_TWINS_MIU_MIA                              1570
#define TRAINER_WALLY                                      1571
#define TRAINER_YOUNGSTER_BEN                              1572
#define TRAINER_YOUNGSTER_BEN_2                            1573
#define TRAINER_YOUNGSTER_BEN_3                            1574
#define TRAINER_YOUNGSTER_BEN_4                            1575
#define TRAINER_YOUNGSTER_CALVIN                           1576
#define TRAINER_YOUNGSTER_CHAD                             1577
#define TRAINER_YOUNGSTER_CHAD_2                           1578
#define TRAINER_YOUNGSTER_CHAD_3                           1579
#define TRAINER_YOUNGSTER_CHAD_4                           1580
#define TRAINER_YOUNGSTER_DAN                              1581
#define TRAINER_YOUNGSTER_DAVE                             1582
#define TRAINER_YOUNGSTER_DESTIN                           1583
#define TRAINER_YOUNGSTER_DESTIN_2                         1584
#define TRAINER_YOUNGSTER_DILLON                           1585
#define TRAINER_YOUNGSTER_EDDIE                            1586
#define TRAINER_YOUNGSTER_JOEY                             1587
#define TRAINER_YOUNGSTER_TIMMY                            1588
#define TRAINER_YOUNGSTER_TIMMY_2                          1589
#define TRAINER_YOUNGSTER_TIMMY_3                          1590
#define TRAINER_YOUNGSTER_TIMMY_4                          1591
#define TRAINER_YOUNGSTER_YASU                             1592
#define TRAINER_YOUNGSTER_YASU_2                           1593
#define TRAINER_YOUNGSTER_YASU_3                           1594
#define TRAINER_YOUNG_COUPLE_EVE_JON                       1595
#define TRAINER_YOUNG_COUPLE_GIA_JES                       1596
#define TRAINER_YOUNG_COUPLE_GIA_JES_2                     1597
#define TRAINER_YOUNG_COUPLE_GIA_JES_3                     1598
#define TRAINER_YOUNG_COUPLE_LEA_JED                       1599
