#ifndef GUARD_CONSTANTS_MAP_TYPES_H
#define GUARD_CONSTANTS_MAP_TYPES_H

#define MAP_TYPE_NONE        0
#define MAP_TYPE_TOWN        1
#define MAP_TYPE_CITY        2
#define MAP_TYPE_ROUTE       3
#define MAP_TYPE_UNDERGROUND 4
#define MAP_TYPE_UNDERWATER  5
#define MAP_TYPE_OCEAN_ROUTE 6
#define MAP_TYPE_UNKNOWN     7 // Not used by any map.
#define MAP_TYPE_INDOOR      8
#define MAP_TYPE_SECRET_BASE 9

#define MAP_BATTLE_SCENE_NORMAL       0
#define MAP_BATTLE_SCENE_GYM          1
#define MAP_BATTLE_SCENE_MAGMA        2
#define MAP_BATTLE_SCENE_AQUA         3
#define MAP_BATTLE_SCENE_SIDNEY       4
#define MAP_BATTLE_SCENE_PHOEBE       5
#define MAP_BATTLE_SCENE_GLACIA       6
#define MAP_BATTLE_SCENE_DRAKE        7
#define MAP_BATTLE_SCENE_FRONTIER     8

// FRLG battle scene aliases
#define MAP_BATTLE_SCENE_LORELEI      MAP_BATTLE_SCENE_SIDNEY
#define MAP_BATTLE_SCENE_BRUNO        MAP_BATTLE_SCENE_PHOEBE
#define MAP_BATTLE_SCENE_AGATHA       MAP_BATTLE_SCENE_GLACIA
#define MAP_BATTLE_SCENE_LANCE        MAP_BATTLE_SCENE_DRAKE
#define MAP_BATTLE_SCENE_INDOOR_1     MAP_BATTLE_SCENE_NORMAL
#define MAP_BATTLE_SCENE_INDOOR_2     MAP_BATTLE_SCENE_NORMAL

#endif  // GUARD_CONSTANTS_MAP_TYPES_H
