gText_Elm_Welcome::
	.string "Hello! sorry to\n"
	.string "keep you waiting!\p"
	.string "Welcome to the\n"
	.string "world of POKéMON!\p"
	.string "My name is ELM.\p"
	.string "I am what is known as\n"
	.string "a POKéMON PROFESSOR.\p"
	.string "$"

gText_Elm_ThisIsAPokemon::
	.string "This world...{PAUSE 96}\p"
	.string "$"

gText_Elm_MainSpeech::
	.string "...is inhabited by creatures\n"
	.string "that we call POKéMON.\p"
	.string "People and POKéMON live together\n"
	.string "by supporting each other.\p"
	.string "Some people play with POKéMON,\n"
	.string "some battle with them.\p"
	.string "...but we don't know everything\n"
	.string "about POKéMON yet.\p"
	.string "There are still many mysteries\n"
	.string "to solve.\p"
	.string "That's why I study POKéMON\n"
	.string "everyday.\p"
	.string "$"

gText_Elm_AndYouAre::
	.string "Now, tell me a little\n"
	.string "more about yourself.$"

gText_Elm_YourePlayer::
	.string "Ah, I see!\p"
	.string "You're {PLAYER}{KUN} who's visiting my\n"
	.string "hometown of NEW BARK.\l"
	.string "Very good!\p"
	.string "$"

gText_Elm_AreYouReady::
	.string "{PLAYER},\n"
	.string "Are you ready?\p"
	.string "Your very own POKéMON story\n"
	.string "is about to unfold.\p"
	.string "You'll face fun times and\n"
	.string "tough challenges.\p"
	.string "A world of dreams and adventures\n"
	.string "with POKéMON awaits! Let's go!\p"
	.string "I'll be seeing you later!\p"
	.string "$"
