gText_Oak_Welcome::
	.string "Hello, there!\n"
	.string "Glad to meet you!\p"
	.string "Welcome to the world of POKéMON!\p"
    .string "My name is OAK.\p"
	.string "People affectionately refer to me\n"
	.string "as the POKéMON PROFESSOR.\p"
	.string "$"

gText_Oak_ThisIsAPokemon::
	.string "This world...{PAUSE 96}\p"
	.string "$"

gText_Oak_MainSpeech::
	.string "...is inhabited far and wide by\n"
	.string "creatures called POKéMON.\p"
	.string "For some people, POKéMON are pets.\n"
    .string "Others use them for battling.\p"
	.string "As for myself...\p"
    .string "I study POKéMON as a profession.\p"
	.string "$"

gText_Oak_AndYouAre::
	.string "But first, tell me a little about\n"
    .string "yourself.$"

gText_Oak_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's visiting\n"
	.string "my hometown of PALLET TOWN.\l"
	.string "I get it now!\p"
	.string "$"

gText_Oak_AreYouReady::
	.string "{PLAYER}!\p"
	.string "Your very own POKéMON legend is\n"
	.string "about to unfold!\p"
	.string "A world of dreams and adventures\n"
	.string "with POKéMON awaits! Let's go!\p"
	.string "$"
