@ FRLG misc data stubs

.equiv FLDEFF_SMILEY_FACE_ICON, 0

.equiv METATILE_Cave_Floor_Ledge_Bottom, 0

.equiv METATILE_Cave_Floor_Ledge_Top, 0

.equiv METATILE_Cave_RockBarrier_Bottom, 0

.equiv METATILE_Cave_RockBarrier_Top, 0

.equiv METATILE_CinnabarGym_Floor, 0

.equiv METATILE_CinnabarGym_Floor_ShadeDiagonal, 0

.equiv METATILE_CinnabarGym_Floor_ShadeFull, 0

.equiv METATILE_CinnabarGym_Floor_WallLeftCorner, 0

.equiv METATILE_CinnabarGym_Floor_WallLeftEdge, 0

.equiv METATILE_CinnabarGym_Floor_WallRightCorner, 0

.equiv METATILE_CinnabarGym_Floor_WallRightEdge, 0

.equiv METATILE_CinnabarGym_Wall_RetractedBarrier, 0

.equiv METATILE_GameCorner_Floor_ShadeFull, 0

.equiv METATILE_GameCorner_Floor_StairsTop, 0

.equiv METATILE_GameCorner_PurpleWall_Floor, 0

.equiv METATILE_GameCorner_PurpleWall_StairsTop, 0

.equiv METATILE_GameCorner_PurpleWall_stairsBottom, 0

.equiv METATILE_GameCorner_StairsBottom, 0

.equiv METATILE_GameCorner_StairsTop, 0

.equiv METATILE_MtEmber_CaveEntrance, 0

.equiv METATILE_PokemonCenter_NetworkMachine_Ruby, 0

.equiv METATILE_PokemonCenter_NetworkMachine_Sapphire, 0

.equiv METATILE_PokemonCenter_NetworkMachine_ScreenLeft_On, 0

.equiv METATILE_PokemonCenter_NetworkMachine_ScreenRight_On, 0

.equiv METATILE_PokemonLeague_Entry_BottomLeft_Closed, 0

.equiv METATILE_PokemonLeague_Entry_BottomMid_Closed, 0

.equiv METATILE_PokemonLeague_Entry_BottomRight_Closed, 0

.equiv METATILE_PokemonLeague_Entry_TopLeft_Closed, 0

.equiv METATILE_PokemonLeague_Entry_TopMid_Closed, 0

.equiv METATILE_PokemonLeague_Entry_TopRight_Closed, 0

.equiv METATILE_PokemonLeague_Floor_ShadeFull_Lance, 0

.equiv METATILE_SeviiIslands45_RocketWarehouseDoor_Unlocked, 0

.equiv METATILE_SeviiIslands67_DottedHoleDoor_Open, 0

.equiv METATILE_SilphCo_Arrow_Up, 0

.equiv METATILE_SilphCo_HideoutBarrier_BottomLeft, 0

.equiv METATILE_SilphCo_HideoutBarrier_BottomRight, 0

.equiv METATILE_SilphCo_HideoutBarrier_TopLeft_Floor, 0

.equiv METATILE_SilphCo_HideoutBarrier_TopRight_Floor, 0

.equiv METATILE_SilphCo_HideoutFloor, 0

.equiv METATILE_SilphCo_HideoutFloor_ShadeFull, 0

.equiv METATILE_TrainerTower_CounterBarrier, 0

.equiv METATILE_TrainerTower_Floor_ShadeBottomLeft, 0

.equiv METATILE_VermilionGym_Beam_MidBottom, 0

.equiv METATILE_VermilionGym_Beam_MidBottom_HalfOn, 0

.equiv METATILE_VermilionGym_Beam_MidTop, 0

.equiv METATILE_VermilionGym_Beam_MidTop_HalfOn, 0

.equiv METATILE_VermilionGym_Beam_Node_BottomLeft_Edge_HalfOn, 0

.equiv METATILE_VermilionGym_Beam_Node_BottomLeft_Edge_Off, 0

.equiv METATILE_VermilionGym_Beam_Node_BottomLeft_Edge_On, 0

.equiv METATILE_VermilionGym_Beam_Node_BottomLeft_HalfOn, 0

.equiv METATILE_VermilionGym_Beam_Node_BottomLeft_Off, 0

.equiv METATILE_VermilionGym_Beam_Node_BottomLeft_On, 0

.equiv METATILE_VermilionGym_Beam_Node_BottomRight_Edge_HalfOn, 0

.equiv METATILE_VermilionGym_Beam_Node_BottomRight_Edge_Off, 0

.equiv METATILE_VermilionGym_Beam_Node_BottomRight_Edge_On, 0

.equiv METATILE_VermilionGym_Beam_Node_BottomRight_HalfOn, 0

.equiv METATILE_VermilionGym_Beam_Node_BottomRight_Off, 0

.equiv METATILE_VermilionGym_Beam_Node_BottomRight_On, 0

.equiv METATILE_VermilionGym_Beam_Node_TopLeft_Edge_HalfOn, 0

.equiv METATILE_VermilionGym_Beam_Node_TopLeft_Edge_Off, 0

.equiv METATILE_VermilionGym_Beam_Node_TopLeft_Edge_On, 0

.equiv METATILE_VermilionGym_Beam_Node_TopLeft_HalfOn, 0

.equiv METATILE_VermilionGym_Beam_Node_TopLeft_Off, 0

.equiv METATILE_VermilionGym_Beam_Node_TopLeft_On, 0

.equiv METATILE_VermilionGym_Beam_Node_TopRight_Edge_HalfOn, 0

.equiv METATILE_VermilionGym_Beam_Node_TopRight_Edge_Off, 0

.equiv METATILE_VermilionGym_Beam_Node_TopRight_Edge_On, 0

.equiv METATILE_VermilionGym_Beam_Node_TopRight_HalfOn, 0

.equiv METATILE_VermilionGym_Beam_Node_TopRight_Off, 0

.equiv METATILE_VermilionGym_Beam_Node_TopRight_On, 0

.equiv METATILE_VermilionGym_Floor, 0

.equiv MULTICHOICE_AMBER, 0

.equiv MULTICHOICE_BIKE_SHOP, 0

.equiv MULTICHOICE_CELADON_VENDING_MACHINE, 0

.equiv MULTICHOICE_DEPT_STORE_ELEVATOR, 0

.equiv MULTICHOICE_DOME, 0

.equiv MULTICHOICE_DOME_AMBER, 0

.equiv MULTICHOICE_EEVEELUTIONS, 0

.equiv MULTICHOICE_GAME_CORNER_BATTLE_ITEM_PRIZES, 0

.equiv MULTICHOICE_GAME_CORNER_COIN_PURCHASE_COUNTER, 0

.equiv MULTICHOICE_GAME_CORNER_POKEMON_PRIZES, 0

.equiv MULTICHOICE_GAME_CORNER_TMPRIZES, 0

.equiv MULTICHOICE_HELIX, 0

.equiv MULTICHOICE_HELIX_AMBER, 0

.equiv MULTICHOICE_LINKED_DIRECT_UNION, 0

.equiv MULTICHOICE_MUSHROOMS, 0

.equiv MULTICHOICE_ROCKET_HIDEOUT_ELEVATOR, 0

.equiv MULTICHOICE_SEAGALLOP_123, 0

.equiv MULTICHOICE_SEVII_BIRTH, 0

.equiv MULTICHOICE_SEVII_NAVEL, 0

.equiv MULTICHOICE_SEVII_NAVEL_BIRTH, 0

.equiv MULTICHOICE_THIRSTY_GIRL_FRESH_WATER, 0

.equiv MULTICHOICE_THIRSTY_GIRL_FRESH_WATER_LEMONADE, 0

.equiv MULTICHOICE_THIRSTY_GIRL_FRESH_WATER_SODA_POP, 0

.equiv MULTICHOICE_THIRSTY_GIRL_FRESH_WATER_SODA_POP_LEMONADE, 0

.equiv MULTICHOICE_THIRSTY_GIRL_LEMONADE, 0

.equiv MULTICHOICE_THIRSTY_GIRL_SODA_POP, 0

.equiv MULTICHOICE_THIRSTY_GIRL_SODA_POP_LEMONADE, 0

.equiv MULTICHOICE_TRAINER_SCHOOL_WHITEBOARD, 0

.equiv SE_RS_DOOR, 0

.equiv SE_RS_SHOP, 0

.equiv SPECIAL_AnimateElevator, 0

.equiv SPECIAL_AnimatePcTurnOff, 0

.equiv SPECIAL_AnimatePcTurnOn, 0

.equiv SPECIAL_AnimateTeleporterCable, 0

.equiv SPECIAL_AnimateTeleporterHousing, 0

.equiv SPECIAL_BufferBigGuyOrBigGirlString, 0

.equiv SPECIAL_BufferEReaderTrainerGreeting, 0

.equiv SPECIAL_CloseElevatorCurrentFloorWindow, 0

.equiv SPECIAL_CloseMuseumFossilPic, 0

.equiv SPECIAL_CompareHeracrossSize, 0

.equiv SPECIAL_CompareMagikarpSize, 0

.equiv SPECIAL_DaisyMassageServices, 0

.equiv SPECIAL_DisableMsgBoxWalkaway, 0

.equiv SPECIAL_DoCredits, 0

.equiv SPECIAL_DoSSAnneDepartureCutscene, 0

.equiv SPECIAL_DoesPlayerPartyContainSpecies, 0

.equiv SPECIAL_DrawElevatorCurrentFloorWindow, 0

.equiv SPECIAL_EnterHallOfFame, 0

.equiv SPECIAL_ForcePlayerOntoBike, 0

.equiv SPECIAL_ForcePlayerToStartSurfing, 0

.equiv SPECIAL_GetHeracrossSizeRecordInfo, 0

.equiv SPECIAL_GetLeadMonFriendship, 0

.equiv SPECIAL_GetMagikarpSizeRecordInfo, 0

.equiv SPECIAL_GetPartyMonSpecies, 0

.equiv SPECIAL_GetPokedexCount, 0

.equiv SPECIAL_GetRandomSlotMachineId, 0

.equiv SPECIAL_GetStarterSpecies, 0

.equiv SPECIAL_HasAllKantoMons, 0

.equiv SPECIAL_InitElevatorFloorSelectMenuPos, 0

.equiv SPECIAL_IsMonOTNameNotPlayers, 0

.equiv SPECIAL_IsNationalPokedexEnabled, 0

.equiv SPECIAL_IsThereRoomInAnyBoxForMorePokemon, 0

.equiv SPECIAL_ListMenu, 0

.equiv SPECIAL_LoopWingFlapSound, 0

.equiv SPECIAL_NameRaterWasNicknameChanged, 0

.equiv SPECIAL_OpenMuseumFossilPic, 0

.equiv SPECIAL_PlayerPartyContainsSpeciesWithPlayerID, 0

.equiv SPECIAL_QuestLog_CutRecording, 0

.equiv SPECIAL_ReducePlayerPartyToThree, 0

.equiv SPECIAL_ReturnToListMenu, 0

.equiv SPECIAL_SampleResortGorgeousMonAndReward, 0

.equiv SPECIAL_Script_BufferFanClubTrainerName, 0

.equiv SPECIAL_Script_GetNumFansOfPlayerInTrainerFanClub, 0

.equiv SPECIAL_Script_HasEnoughBerryPowder, 0

.equiv SPECIAL_Script_IsFanClubMemberFanOfPlayer, 0

.equiv SPECIAL_Script_SetHelpContext, 0

.equiv SPECIAL_Script_TakeBerryPowder, 0

.equiv SPECIAL_Script_TryLoseFansFromPlayTime, 0

.equiv SPECIAL_SeafoamIslandsB4F_CurrentDumpsPlayerOnLand, 0

.equiv SPECIAL_SelectMoveDeleterMove, 0

.equiv SPECIAL_SetHelpContextForMap, 0

.equiv SPECIAL_SetIcefallCaveCrackedIceMetatiles, 0

.equiv SPECIAL_SetPostgameFlags, 0

.equiv SPECIAL_SetSeenMon, 0

.equiv SPECIAL_SetVermilionTrashCans, 0

.equiv SPECIAL_SetWalkingIntoSignVars, 0

.equiv SPECIAL_ShakeScreen, 0

.equiv SPECIAL_ShowBattleRecords, 0

.equiv SPECIAL_ShowDiploma, 0

.equiv SPECIAL_StartLegendaryBattle, 0

.equiv SPECIAL_StartMarowakBattle, 0

.equiv SPECIAL_StartOldManTutorialBattle, 0

.equiv SPECIAL_StartSpecialBattle, 0

.equiv SPECIAL_UpdateLoreleiDollCollection, 0

.equiv STDSTRING_BOULDER_BADGE, 0

.equiv STDSTRING_CASCADE_BADGE, 0

.equiv STDSTRING_EARTH_BADGE, 0

.equiv STDSTRING_MARSH_BADGE, 0

.equiv STDSTRING_RAINBOW_BADGE, 0

.equiv STDSTRING_SOUL_BADGE, 0

.equiv STDSTRING_THUNDER_BADGE, 0

.equiv STDSTRING_VOLCANO_BADGE, 0

.equiv STEP_CB_ICE, 0

.equiv TrainerTower_OnFrame, 0

.equiv TrainerTower_OnResume, 0

.equiv TrainerTower_OnTransition, 0
