@ FRLG common script stubs

Aide_EventScript_DeclineCheckMons::
	return

Aide_EventScript_HaventCaughtEnough::
	return

Aide_EventScript_NoRoomForItem::
	return

CeladonCity_Condominiums_2F_EventScript_PokemonJournalErika::
	return

CeladonCity_DepartmentStore_2F_EventScript_Woman::
	return

CeladonCity_GameCorner_EventScript_PhotoPrinter::
	return

CeruleanCity_PokemonCenter_1F_EventScript_PokemonJournalMisty::
	return

CinnabarIsland_Gym_EventScript_BlaineFujiPhoto::
	return

CinnabarIsland_PokemonCenter_1F_EventScript_PokemonJournalMrFuji::
	return

EventScript_AskSaveGame::
	return

EventScript_AwakenSnorlax::
	return

EventScript_BagIsFull::
	return

EventScript_CancelSail::
	return

EventScript_ChangePokemonNickname::
	return

EventScript_CheckTurnAttendant::
	return

EventScript_ChooseDestFromIsland::
	return

EventScript_ChooseDestFromOneIsland::
	return

EventScript_ChooseDestFromTwoIsland::
	return

EventScript_ChooseMonForInGameTrade::
	return

EventScript_Close10FDoor::
	return

EventScript_Close11FDoor::
	return

EventScript_Close2FDoor1::
	return

EventScript_Close2FDoor2::
	return

EventScript_Close3FDoor1::
	return

EventScript_Close3FDoor2::
	return

EventScript_Close4FDoor1::
	return

EventScript_Close4FDoor2::
	return

EventScript_Close5FDoor1::
	return

EventScript_Close5FDoor2::
	return

EventScript_Close5FDoor3::
	return

EventScript_Close6FDoor::
	return

EventScript_Close7FDoor1::
	return

EventScript_Close7FDoor2::
	return

EventScript_Close7FDoor3::
	return

EventScript_Close8FDoor::
	return

EventScript_Close9FDoor1::
	return

EventScript_Close9FDoor2::
	return

EventScript_Close9FDoor3::
	return

EventScript_Close9FDoor4::
	return

EventScript_CounterTutor::
	return

EventScript_DoInGameTrade::
	return

EventScript_DreamEaterTutor::
	return

EventScript_GetElevatorFloor::
	return

EventScript_GetGiftMonPartySlot::
	return

EventScript_GetInGameTradeSpecies::
	return

EventScript_GetInGameTradeSpeciesInfo::
	return

EventScript_MetronomeTutor::
	return

EventScript_MimicTutor::
	return

EventScript_MonFlewAway::
	return

EventScript_NameReceivedBoxMon::
	return

EventScript_NoMoreRoomForPokemon::
	return

EventScript_OutOfCenterPartyHeal::
	return

EventScript_PkmnCenterNurse::
	return

EventScript_RemoveStaticMon::
	return

EventScript_RestorePrevTextColor::
	return

EventScript_Return::
	return

EventScript_SailToOneIsland2::
	return

EventScript_SailToThreeIsland2::
	return

EventScript_SailToTwoIsland2::
	return

EventScript_SetDefeatedEliteFourFlagsVars::
	return

EventScript_SetEnteringCyclingRoad::
	return

EventScript_SetExitingCyclingRoad::
	return

EventScript_SetResultFalse::
	return

EventScript_SetResultTrue::
	return

EventScript_SetSail::
	return

EventScript_SeviiDestinationsPage1::
	return

EventScript_SoftboiledTutor::
	return

EventScript_ThunderWaveTutor::
	return

EventScript_TransferredToPC::
	return

EventScript_TryDarkenRuins::
	return

FiveIsland_MemorialPillar_EventScript_Chaz::
	return

FiveIsland_MemorialPillar_EventScript_Harold::
	return

FiveIsland_MemorialPillar_EventScript_Milo::
	return

FiveIsland_PokemonCenter_1F_EventScript_PokemonJournal::
	return

FiveIsland_ResortGorgeous_EventScript_Celina::
	return

FiveIsland_ResortGorgeous_EventScript_Daisy::
	return

FiveIsland_ResortGorgeous_EventScript_Destin::
	return

FiveIsland_ResortGorgeous_EventScript_Gillian::
	return

FiveIsland_ResortGorgeous_EventScript_Jacki::
	return

FiveIsland_ResortGorgeous_EventScript_Rayna::
	return

FiveIsland_ResortGorgeous_EventScript_Toby::
	return

FiveIsland_ResortGorgeous_House_EventScript_PokemonJournal::
	return

FiveIsland_WaterLabyrinth_EventScript_Alize::
	return

FourIsland_House1_EventScript_BodySlamTutor::
	return

FourIsland_House2_EventScript_StickerMan::
	return

FourIsland_Mart_EventScript_OldMan::
	return

FourIsland_PokemonCenter_1F_EventScript_PokemonJournal::
	return

FuchsiaCity_EventScript_SubstituteTutor::
	return

FuchsiaCity_WardensHouse_EventScript_PokemonJournalKoga::
	return

IndigoPlateau_PokemonCenter_1F_EventScript_BlackBelt::
	return

IndigoPlateau_PokemonCenter_1F_EventScript_CooltrainerM::
	return

IndigoPlateau_PokemonCenter_1F_EventScript_PokemonJournal::
	return

JoyfulGameCorner_EventScript_InfoMan2::
	return

JoyfulGameCorner_EventScript_MinigameAttendant::
	return

LavenderTown_PokemonCenter_1F_EventScript_BaldingMan::
	return

MtEmber_Exterior_EventScript_ExplosionTutor::
	return

MtMoon_1F_EventScript_BaldingMan::
	return

MysteryEventClub_EventScript_Woman::
	return

OneIsland_KindleRoad_EventScript_Abigail::
	return

OneIsland_KindleRoad_EventScript_Bryce::
	return

OneIsland_KindleRoad_EventScript_Claire::
	return

OneIsland_KindleRoad_EventScript_Finn::
	return

OneIsland_KindleRoad_EventScript_Garrett::
	return

OneIsland_KindleRoad_EventScript_Hugh::
	return

OneIsland_KindleRoad_EventScript_Kia::
	return

OneIsland_KindleRoad_EventScript_Maria::
	return

OneIsland_KindleRoad_EventScript_Mik::
	return

OneIsland_KindleRoad_EventScript_Sharon::
	return

OneIsland_KindleRoad_EventScript_Shea::
	return

OneIsland_KindleRoad_EventScript_Tanya::
	return

OneIsland_KindleRoad_EventScript_Tommy::
	return

OneIsland_TreasureBeach_EventScript_Amara::
	return

PewterCity_Museum_1F_EventScript_PokemonJournalBrock::
	return

PewterCity_Museum_1F_EventScript_SeismicTossTutor::
	return

PokedexRating_EventScript_RateInPerson::
	return

PokemonLeague_EventScript_CloseEntry::
	return

PokemonLeague_EventScript_DoLightingEffect::
	return

PokemonLeague_EventScript_EnterRoom::
	return

PokemonLeague_EventScript_OpenDoor::
	return

PokemonLeague_EventScript_OpenDoorLance::
	return

PokemonLeague_EventScript_SetDoorOpen::
	return

PokemonLeague_EventScript_SetDoorOpenLance::
	return

PokemonMansion_EventScript_PressSwitch_1F::
	return

PokemonMansion_EventScript_PressSwitch_2F::
	return

PokemonMansion_EventScript_PressSwitch_3F::
	return

PokemonMansion_EventScript_PressSwitch_B1F::
	return

PokemonMansion_EventScript_SecretSwitch::
	return

RockTunnel_B1F_EventScript_RockSlideTutor::
	return

Route10_EventScript_Carol::
	return

Route10_EventScript_Clark::
	return

Route10_EventScript_Heidi::
	return

Route10_EventScript_Herman::
	return

Route10_EventScript_Mark::
	return

Route10_EventScript_Trent::
	return

Route11_EventScript_Bernie::
	return

Route11_EventScript_Braxton::
	return

Route11_EventScript_Darian::
	return

Route11_EventScript_Dave::
	return

Route11_EventScript_Dillon::
	return

Route11_EventScript_Dirk::
	return

Route11_EventScript_Eddie::
	return

Route11_EventScript_Hugo::
	return

Route11_EventScript_Jasper::
	return

Route11_EventScript_Yasu::
	return

Route12_EventScript_Andrew::
	return

Route12_EventScript_Chip::
	return

Route12_EventScript_Elliot::
	return

Route12_EventScript_Gia::
	return

Route12_EventScript_Hank::
	return

Route12_EventScript_Jes::
	return

Route12_EventScript_Justin::
	return

Route12_EventScript_Luca::
	return

Route12_EventScript_Ned::
	return

Route13_EventScript_Alma::
	return

Route13_EventScript_Gwen::
	return

Route13_EventScript_Jared::
	return

Route13_EventScript_Lola::
	return

Route13_EventScript_Perry::
	return

Route13_EventScript_Robert::
	return

Route13_EventScript_Sebastian::
	return

Route13_EventScript_Sheila::
	return

Route13_EventScript_Susie::
	return

Route13_EventScript_Valerie::
	return

Route14_EventScript_Beck::
	return

Route14_EventScript_Benny::
	return

Route14_EventScript_Carter::
	return

Route14_EventScript_Donald::
	return

Route14_EventScript_Gerald::
	return

Route14_EventScript_Isaac::
	return

Route14_EventScript_Jan::
	return

Route14_EventScript_Kiri::
	return

Route14_EventScript_Lukas::
	return

Route14_EventScript_Malik::
	return

Route14_EventScript_Marlon::
	return

Route14_EventScript_Mitch::
	return

Route15_EventScript_Alex::
	return

Route15_EventScript_Becky::
	return

Route15_EventScript_Celia::
	return

Route15_EventScript_Chester::
	return

Route15_EventScript_Edwin::
	return

Route15_EventScript_Ernest::
	return

Route15_EventScript_Grace::
	return

Route15_EventScript_Kindra::
	return

Route15_EventScript_Mya::
	return

Route15_EventScript_Olivia::
	return

Route15_EventScript_Ron::
	return

Route15_EventScript_Yazmin::
	return

Route16_EventScript_Camron::
	return

Route16_EventScript_Hideo::
	return

Route16_EventScript_Jed::
	return

Route16_EventScript_Koji::
	return

Route16_EventScript_Lao::
	return

Route16_EventScript_Lea::
	return

Route16_EventScript_Luke::
	return

Route16_EventScript_Ruben::
	return

Route17_EventScript_Billy::
	return

Route17_EventScript_Corey::
	return

Route17_EventScript_Isaiah::
	return

Route17_EventScript_Jamal::
	return

Route17_EventScript_Jaxon::
	return

Route17_EventScript_Nikolas::
	return

Route17_EventScript_Raul::
	return

Route17_EventScript_Virgil::
	return

Route17_EventScript_William::
	return

Route17_EventScript_Zeek::
	return

Route18_EventScript_Jacob::
	return

Route18_EventScript_Ramiro::
	return

Route18_EventScript_Wilton::
	return

Route19_EventScript_Alice::
	return

Route19_EventScript_Anya::
	return

Route19_EventScript_Axle::
	return

Route19_EventScript_Connie::
	return

Route19_EventScript_David::
	return

Route19_EventScript_Douglas::
	return

Route19_EventScript_Lia::
	return

Route19_EventScript_Luc::
	return

Route19_EventScript_Matthew::
	return

Route19_EventScript_Reece::
	return

Route19_EventScript_Richard::
	return

Route19_EventScript_Tony::
	return

Route20_EventScript_Barry::
	return

Route20_EventScript_Camper::
	return

Route20_EventScript_Darrin::
	return

Route20_EventScript_Dean::
	return

Route20_EventScript_Irene::
	return

Route20_EventScript_Melissa::
	return

Route20_EventScript_Missy::
	return

Route20_EventScript_Nora::
	return

Route20_EventScript_Roger::
	return

Route20_EventScript_Shirley::
	return

Route20_EventScript_Tiffany::
	return

Route21_North_EventScript_Ian::
	return

Route21_North_EventScript_Lil::
	return

Route21_North_EventScript_Ronald::
	return

Route21_North_EventScript_Spencer::
	return

Route21_North_EventScript_Wade::
	return

Route21_South_EventScript_Claude::
	return

Route21_South_EventScript_Jack::
	return

Route21_South_EventScript_Jerome::
	return

Route21_South_EventScript_Nolan::
	return

Route21_South_EventScript_Roland::
	return

Route24_EventScript_Ali::
	return

Route24_EventScript_Cale::
	return

Route24_EventScript_Ethan::
	return

Route24_EventScript_Reli::
	return

Route24_EventScript_Shane::
	return

Route24_EventScript_Timmy::
	return

Route25_EventScript_Beauty::
	return

Route25_EventScript_Chad::
	return

Route25_EventScript_Dan::
	return

Route25_EventScript_Flint::
	return

Route25_EventScript_Franklin::
	return

Route25_EventScript_Haley::
	return

Route25_EventScript_Joey::
	return

Route25_EventScript_Kelsey::
	return

Route25_EventScript_Nob::
	return

Route25_EventScript_Wayne::
	return

Route3_EventScript_Ben::
	return

Route3_EventScript_Calvin::
	return

Route3_EventScript_Colton::
	return

Route3_EventScript_Greg::
	return

Route3_EventScript_James::
	return

Route3_EventScript_Janice::
	return

Route3_EventScript_Robin::
	return

Route3_EventScript_Sally::
	return

Route4_EventScript_Boy::
	return

Route4_EventScript_Crissy::
	return

Route4_EventScript_MegaKickTutor::
	return

Route4_EventScript_MegaPunchTutor::
	return

Route5_PokemonDayCare_EventScript_DaycareMan::
	return

Route6_EventScript_Elijah::
	return

Route6_EventScript_Isabelle::
	return

Route6_EventScript_Jeff::
	return

Route6_EventScript_Keigo::
	return

Route6_EventScript_Nancy::
	return

Route6_EventScript_Ricky::
	return

Route8_EventScript_Aidan::
	return

Route8_EventScript_Andrea::
	return

Route8_EventScript_Anne::
	return

Route8_EventScript_Eli::
	return

Route8_EventScript_Glenn::
	return

Route8_EventScript_Jaren::
	return

Route8_EventScript_Julia::
	return

Route8_EventScript_Leslie::
	return

Route8_EventScript_Megan::
	return

Route8_EventScript_Paige::
	return

Route8_EventScript_Ricardo::
	return

Route8_EventScript_Rich::
	return

Route8_EventScript_Stan::
	return

Route9_EventScript_Alan::
	return

Route9_EventScript_Alicia::
	return

Route9_EventScript_Brent::
	return

Route9_EventScript_Brice::
	return

Route9_EventScript_Caitlin::
	return

Route9_EventScript_Chris::
	return

Route9_EventScript_Conner::
	return

Route9_EventScript_Drew::
	return

Route9_EventScript_Jeremy::
	return

SafariZone_North_RestHouse_EventScript_BaldingMan::
	return

SaffronCity_EventScript_CrushGirl::
	return

SaffronCity_PokemonCenter_1F_EventScript_PokemonJournalSabrina::
	return

SaffronCity_PokemonTrainerFanClub_EventScript_PokemonJournalBruno::
	return

SevenIsland_EventScript_SwordsDanceTutor::
	return

SevenIsland_PokemonCenter_1F_EventScript_PokemonJournal::
	return

SevenIsland_SevaultCanyon_Entrance_EventScript_Eve::
	return

SevenIsland_SevaultCanyon_Entrance_EventScript_Jon::
	return

SevenIsland_SevaultCanyon_Entrance_EventScript_Madeline::
	return

SevenIsland_SevaultCanyon_Entrance_EventScript_Mason::
	return

SevenIsland_SevaultCanyon_Entrance_EventScript_Miah::
	return

SevenIsland_SevaultCanyon_Entrance_EventScript_Nicolas::
	return

SevenIsland_SevaultCanyon_EventScript_BlackBelt::
	return

SevenIsland_SevaultCanyon_EventScript_Cyndy::
	return

SevenIsland_SevaultCanyon_EventScript_Evan::
	return

SevenIsland_SevaultCanyon_EventScript_Jackson::
	return

SevenIsland_SevaultCanyon_EventScript_Katelyn::
	return

SevenIsland_SevaultCanyon_EventScript_Leroy::
	return

SevenIsland_SevaultCanyon_EventScript_Lex::
	return

SevenIsland_SevaultCanyon_EventScript_Michelle::
	return

SevenIsland_SevaultCanyon_EventScript_Nya::
	return

SevenIsland_TanobyRuins_EventScript_Benjamin::
	return

SevenIsland_TanobyRuins_EventScript_Brandon::
	return

SevenIsland_TanobyRuins_EventScript_Clifford::
	return

SevenIsland_TanobyRuins_EventScript_Edna::
	return

SevenIsland_TrainerTower_EventScript_Dario::
	return

SevenIsland_TrainerTower_EventScript_Rodette::
	return

SilphCo_10F_EventScript_Door::
	return

SilphCo_11F_EventScript_Door::
	return

SilphCo_2F_EventScript_Door1::
	return

SilphCo_2F_EventScript_Door2::
	return

SilphCo_3F_EventScript_Door1::
	return

SilphCo_3F_EventScript_Door2::
	return

SilphCo_4F_EventScript_Door1::
	return

SilphCo_4F_EventScript_Door2::
	return

SilphCo_5F_EventScript_Door1::
	return

SilphCo_5F_EventScript_Door2::
	return

SilphCo_5F_EventScript_Door3::
	return

SilphCo_5F_EventScript_Scientist::
	return

SilphCo_6F_EventScript_Door::
	return

SilphCo_7F_EventScript_Door1::
	return

SilphCo_7F_EventScript_Door2::
	return

SilphCo_7F_EventScript_Door3::
	return

SilphCo_8F_EventScript_Door::
	return

SilphCo_8F_EventScript_Scientist::
	return

SilphCo_9F_EventScript_Door1::
	return

SilphCo_9F_EventScript_Door2::
	return

SilphCo_9F_EventScript_Door3::
	return

SilphCo_9F_EventScript_Door4::
	return

SixIsland_GreenPath_EventScript_Jaclyn::
	return

SixIsland_Mart_EventScript_OldWoman::
	return

SixIsland_OutcastIsland_EventScript_Ava::
	return

SixIsland_OutcastIsland_EventScript_Geb::
	return

SixIsland_OutcastIsland_EventScript_Mymo::
	return

SixIsland_OutcastIsland_EventScript_Nicole::
	return

SixIsland_OutcastIsland_EventScript_Tylor::
	return

SixIsland_RuinValley_EventScript_Daryl::
	return

SixIsland_RuinValley_EventScript_Foster::
	return

SixIsland_RuinValley_EventScript_Hector::
	return

SixIsland_RuinValley_EventScript_Larry::
	return

SixIsland_RuinValley_EventScript_Stanly::
	return

SixIsland_WaterPath_EventScript_Denise::
	return

SixIsland_WaterPath_EventScript_Earl::
	return

SixIsland_WaterPath_EventScript_Edward::
	return

SixIsland_WaterPath_EventScript_Mia::
	return

SixIsland_WaterPath_EventScript_Miu::
	return

SixIsland_WaterPath_EventScript_Rose::
	return

SixIsland_WaterPath_EventScript_Samir::
	return

ThreeIsland_BondBridge_EventScript_Alexis::
	return

ThreeIsland_BondBridge_EventScript_Amira::
	return

ThreeIsland_BondBridge_EventScript_Joy::
	return

ThreeIsland_BondBridge_EventScript_Meg::
	return

ThreeIsland_BondBridge_EventScript_Nikki::
	return

ThreeIsland_BondBridge_EventScript_Tisha::
	return

ThreeIsland_BondBridge_EventScript_Violet::
	return

TrainerTower_EventScript_DoubleBattleTriggerBottom::
	return

TrainerTower_EventScript_DoubleBattleTriggerTop::
	return

TrainerTower_EventScript_SingleBattleTrigger::
	return

TrainerTower_EventScript_SpeakToDoublesTrainer1::
	return

TrainerTower_EventScript_SpeakToDoublesTrainer2::
	return

TrainerTower_EventScript_SpeakToKnockoutTrainer::
	return

TrainerTower_EventScript_SpeakToOwner::
	return

TrainerTower_EventScript_SpeakToSinglesTrainer::
	return

TwoIsland_CapeBrink_House_EventScript_StarterTutor::
	return

TwoIsland_JoyfulGameCorner_EventScript_ShowDodrioBerryPickingRecords::
	return

TwoIsland_JoyfulGameCorner_EventScript_ShowPokemonJumpRecords::
	return

VermilionCity_EventScript_WalkUpPier::
	return

VermilionCity_PokemonCenter_1F_EventScript_PokemonJournalLtSurge::
	return

VermilionCity_PokemonCenter_1F_EventScript_VSSeekerWoman::
	return

VictoryRoad_2F_EventScript_DoubleEdgeTutor::
	return

ViridianCity_School_EventScript_PokemonJournal::
	lockall
	textcolor NPC_TEXT_COLOR_NEUTRAL
	msgbox PokemonJournal_Text_SpecialFeatureProfOak
	releaseall
	end

PokemonJournal_Text_SpecialFeatureProfOak::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: PROF. OAK,\n"
	.string "the POKéMON Researcher!\p"
	.string "PROF. OAK reportedly lives with his\n"
	.string "grandchildren DAISY and {RIVALK}.$"

SilphCo_5F_EventScript_ItemCardKey::
	return

SafariZone_West_EventScript_ItemGoldTeeth::
	return

PokemonMansion_B1F_EventScript_ItemSecretKey::
	return

SilphCo_5F_EventScript_ItemTM01::
	return

Route4_EventScript_ItemTM05::
	return

VictoryRoad_2F_EventScript_ItemTM07::
	return

SilphCo_7F_EventScript_ItemTM08::
	return

MtMoon_1F_EventScript_ItemTM09::
	return

SafariZone_East_EventScript_ItemTM11::
	return

RocketHideout_B2F_EventScript_ItemTM12::
	return

PokemonMansion_B1F_EventScript_ItemTM14::
	return

PowerPlant_EventScript_ItemTM17::
	return

Route15_EventScript_ItemTM18::
	return

RocketHideout_B3F_EventScript_ItemTM21::
	return

PokemonMansion_B1F_EventScript_ItemTM22::
	return

PowerPlant_EventScript_ItemTM25::
	return

SSAnne_1F_Room2_EventScript_ItemTM31::
	return

SafariZone_West_EventScript_ItemTM32::
	return

FiveIsland_RocketWarehouse_EventScript_ItemTM36::
	return

VictoryRoad_2F_EventScript_ItemTM37::
	return

Route9_EventScript_ItemTM40::
	return

SilphCo_4F_EventScript_ItemTM41::
	return

Route25_EventScript_ItemTM43::
	return

SSAnne_B1F_Room2_EventScript_ItemTM44::
	return

Route24_EventScript_ItemTM45::
	return

MtMoon_B2F_EventScript_ItemTM46::
	return

Route12_EventScript_ItemTM48::
	return

RocketHideout_B4F_EventScript_ItemTM49::
	return

VictoryRoad_3F_EventScript_ItemTM50::
	return

FourIsland_IcefallCave_1F_EventScript_ItemHM07::
	return