// Auto-generated by python/find_method2_6iv.py
// Method 2 PID/IV pairs with near-perfect IVs
// Sorted: egg-safe (all 30-31) first, then ATK 0/1 entries

struct WishEggPidIvs {
    u32 pid;
    u16 iv1; // HP(0-4), ATK(5-9), DEF(10-14)
    u16 iv2; // SPD(0-4), SPATK(5-9), SPDEF(10-14)
};

#define WISH_EGG_PID_IV_EGG_COUNT 260
#define WISH_EGG_PID_IV_TABLE_COUNT 520

const struct WishEggPidIvs sWishEggPidIvTable[] =
{
    { 0x008B7BFE, 0x7BFE, 0x7BFE }, // Gentle, 30/31/30/30/31/30
    { 0x00F4F993, 0x7BDF, 0x7FDF }, // Hardy, 31/30/30/31/30/31
    { 0x012B2209, 0x7FDF, 0x7BDE }, // Brave, 31/30/31/30/30/30
    { 0x015C04B1, 0x7FDE, 0x7FDE }, // Naughty, 30/30/31/30/30/31
    { 0x0246BFF5, 0x7BFE, 0x7BDF }, // Bashful, 30/31/30/31/30/30
    { 0x04BE6EC5, 0x7BFF, 0x7BFE }, // Hasty, 31/31/30/30/31/30
    { 0x04EF516D, 0x7BFF, 0x7FFE }, // Jolly, 31/31/30/30/31/31
    { 0x06AB9565, 0x7BFF, 0x7FDF }, // Sassy, 31/31/30/31/30/31
    { 0x06E1BDDB, 0x7FFE, 0x7BDE }, // Quirky, 30/31/31/30/30/30
    { 0x0713A083, 0x7FFE, 0x7FDE }, // Serious, 30/31/31/30/30/31
    { 0x078E09C3, 0x7FDF, 0x7BFF }, // Careful, 31/30/31/31/31/30
    { 0x07BFEC6A, 0x7FDE, 0x7FFE }, // Timid, 30/30/31/30/31/31
    { 0x099C687D, 0x7BDF, 0x7BDE }, // Lax, 31/30/30/30/30/30
    { 0x0B46934A, 0x7FFF, 0x7FDE }, // Brave, 31/31/31/30/30/31
    { 0x0BF2DF32, 0x7FDF, 0x7FFF }, // Lonely, 31/30/31/31/31/31
    { 0x0D44A595, 0x7FFE, 0x7BFF }, // Calm, 30/31/31/31/31/30
    { 0x0E003DEC, 0x7BDF, 0x7FDE }, // Lonely, 31/30/30/30/30/31
    { 0x0F52044F, 0x7BFE, 0x7BDE }, // Calm, 30/31/30/30/30/30
    { 0x0FFE5037, 0x7BDE, 0x7BFE }, // Rash, 30/30/30/30/31/30
    { 0x11A97B04, 0x7FFF, 0x7FFF }, // Careful, 31/31/31/31/31/31
    { 0x1385F716, 0x7BFF, 0x7BDE }, // Gentle, 31/31/30/30/30/30
    { 0x13B7D9BE, 0x7BFF, 0x7FDE }, // Lax, 31/31/30/30/30/31
    { 0x146325A6, 0x7BDF, 0x7FFF }, // Sassy, 31/30/30/31/31/31
    { 0x16559214, 0x7FDF, 0x7BDF }, // Impish, 31/30/31/31/30/30
    { 0x168674BC, 0x7FDE, 0x7FDE }, // Timid, 30/30/31/30/30/31
    { 0x18FE238B, 0x7FDF, 0x7FFE }, // Brave, 31/30/31/30/31/31
    { 0x19E8DED0, 0x7BFF, 0x7BFF }, // Quiet, 31/31/30/31/31/30
    { 0x1A19C178, 0x7BFE, 0x7FFF }, // Rash, 30/31/30/31/31/31
    { 0x1C0C2DE6, 0x7FFE, 0x7BDF }, // Bold, 30/31/31/31/30/30
    { 0x1CB879CE, 0x7FDE, 0x7BFF }, // Naughty, 30/30/31/31/31/30
    { 0x1E83DCB6, 0x7FFF, 0x7BFE }, // Careful, 31/31/31/30/31/30
    { 0x1EB4BF5D, 0x7FFF, 0x7FFE }, // Quirky, 31/31/31/30/31/31
    { 0x1EC6D888, 0x7BDE, 0x7BDE }, // Modest, 30/30/30/30/30/30
    { 0x20700355, 0x7FFF, 0x7FDF }, // Sassy, 31/31/31/31/30/31
    { 0x226F159F, 0x7FFE, 0x7BFF }, // Hardy, 30/31/31/31/31/30
    { 0x232AADF7, 0x7BDF, 0x7FDF }, // Relaxed, 31/30/30/31/30/31
    { 0x2361D66E, 0x7FDF, 0x7BDE }, // Gentle, 31/30/31/30/30/30
    { 0x2529C042, 0x7BDE, 0x7BFF }, // Hasty, 30/30/30/31/31/30
    { 0x26F4232A, 0x7BFF, 0x7BFE }, // Rash, 31/31/30/30/31/30
    { 0x28B06721, 0x7BFF, 0x7BDF }, // Brave, 31/31/30/31/30/30
    { 0x28E149C9, 0x7BFE, 0x7FDF }, // Naughty, 30/31/30/31/30/31
    { 0x2918723F, 0x7FFE, 0x7BDE }, // Quiet, 30/31/31/30/30/30
    { 0x298D95B1, 0x7BDF, 0x7FFF }, // Adamant, 31/30/30/31/31/31
    { 0x29C4BE27, 0x7FDE, 0x7BFE }, // Mild, 30/30/31/30/31/30
    { 0x2BB1E4C7, 0x7FDE, 0x7FDF }, // Brave, 30/30/31/31/30/31
    { 0x2D7C47AF, 0x7FFF, 0x7FDE }, // Timid, 31/31/31/30/30/31
    { 0x2E289396, 0x7FDF, 0x7FFE }, // Impish, 31/30/31/30/31/31
    { 0x2F443183, 0x7BFE, 0x7FFF }, // Hardy, 30/31/30/31/31/31
    { 0x2F7A59F9, 0x7FFE, 0x7BFE }, // Brave, 30/31/31/30/31/30
    { 0x3235049B, 0x7BDE, 0x7BFE }, // Serious, 30/30/30/30/31/30
    { 0x33AD4CC0, 0x7FFF, 0x7BFF }, // Quiet, 31/31/31/31/31/30
    { 0x33DF2F68, 0x7FFE, 0x7FFE }, // Bold, 30/31/31/30/31/31
    { 0x33F04893, 0x7BDE, 0x7BDF }, // Timid, 30/30/30/31/30/30
    { 0x35BCAB7B, 0x7BFF, 0x7BDE }, // Modest, 31/31/30/30/30/30
    { 0x3668F763, 0x7BDF, 0x7BFF }, // Naive, 31/30/30/31/31/30
    { 0x3699DA0B, 0x7BDE, 0x7FFE }, // Mild, 30/30/30/30/31/31
    { 0x38551E02, 0x7BDF, 0x7FDF }, // Jolly, 31/30/30/31/30/31
    { 0x388B4678, 0x7FDE, 0x7BDE }, // Modest, 30/30/31/30/30/30
    { 0x38BD2920, 0x7FDE, 0x7FDE }, // Adamant, 30/30/31/30/30/31
    { 0x3C1E9335, 0x7BFF, 0x7BFF }, // Hardy, 31/31/30/31/31/30
    { 0x3C5075DD, 0x7BFE, 0x7FFE }, // Jolly, 30/31/30/30/31/31
    { 0x3CF01BE8, 0x7FDF, 0x7FDF }, // Rash, 31/30/31/31/30/31
    { 0x3E0BB9D4, 0x7BFE, 0x7FDF }, // Timid, 30/31/30/31/30/31
    { 0x3E42E24A, 0x7FFE, 0x7BDE }, // Careful, 30/31/31/30/30/30
    { 0x3EEE2E32, 0x7FDE, 0x7BFF }, // Hasty, 30/30/31/31/31/30
    { 0x408368A4, 0x7BFF, 0x7FFF }, // Adamant, 31/31/30/31/31/31
    { 0x40B9911A, 0x7FFF, 0x7BFE }, // Bold, 31/31/31/30/31/30
    { 0x40FC8CED, 0x7BDE, 0x7BDE }, // Careful, 30/30/30/30/30/30
    { 0x4275D512, 0x7FFF, 0x7BDF }, // Naive, 31/31/31/31/30/30
    { 0x42A6B7BA, 0x7FFE, 0x7FDF }, // Mild, 30/31/31/31/30/31
    { 0x435203A1, 0x7FDF, 0x7FFF }, // Adamant, 31/30/31/31/31/31
    { 0x452F7FB4, 0x7BDF, 0x7BDF }, // Jolly, 31/30/30/31/30/30
    { 0x4561625C, 0x7BDF, 0x7FDE }, // Lonely, 31/30/30/30/30/31
    { 0x49099F73, 0x7FFE, 0x7FFF }, // Hasty, 30/31/31/31/31/31
    { 0x4AE61B86, 0x7BFF, 0x7BDF }, // Timid, 31/31/30/31/30/30
    { 0x4B17FE2E, 0x7BFE, 0x7FDE }, // Careful, 30/31/30/30/30/31
    { 0x4B92676E, 0x7BDF, 0x7BFF }, // Lax, 31/30/30/31/31/30
    { 0x4BC34A16, 0x7BDE, 0x7FFF }, // Hasty, 30/30/30/31/31/31
    { 0x4BFA728C, 0x7FDE, 0x7BFE }, // Quirky, 30/30/31/30/31/30
    { 0x4D8FACFE, 0x7BFF, 0x7FFE }, // Mild, 31/31/30/30/31/31
    { 0x4DB6B683, 0x7FDE, 0x7BDF }, // Relaxed, 30/30/31/31/30/30
    { 0x4F4AF0F5, 0x7BFF, 0x7FDF }, // Jolly, 31/31/30/31/30/31
    { 0x4F81196B, 0x7FFF, 0x7BDE }, // Modest, 31/31/31/30/30/30
    { 0x502D6553, 0x7FDF, 0x7BFE }, // Naive, 31/30/31/30/31/30
    { 0x505E47FB, 0x7FDF, 0x7FFE }, // Mild, 31/30/31/30/31/31
    { 0x51490340, 0x7BFE, 0x7BFF }, // Docile, 30/31/30/31/31/30
    { 0x521A8BF3, 0x7FDF, 0x7FDF }, // Hardy, 31/30/31/31/30/31
    { 0x55E40125, 0x7FFF, 0x7BFE }, // Hasty, 31/31/31/30/31/30
    { 0x5615E3CD, 0x7FFE, 0x7FFE }, // Quirky, 30/31/31/30/31/31
    { 0x57D127C5, 0x7FFE, 0x7FDF }, // Sassy, 30/31/31/31/30/31
    { 0x589EABC7, 0x7BDF, 0x7BFE }, // Gentle, 31/30/30/30/31/30
    { 0x58CF8E6F, 0x7BDE, 0x7FFE }, // Careful, 30/30/30/30/31/31
    { 0x5A48D694, 0x7FFF, 0x7FFF }, // Naive, 31/31/31/31/31/31
    { 0x5A5AEFBF, 0x7BDF, 0x7BDF }, // Bold, 31/30/30/31/30/30
    { 0x5A8BD267, 0x7BDE, 0x7FDF }, // Relaxed, 30/30/30/31/30/31
    { 0x5AC2FADD, 0x7FDE, 0x7BDE }, // Calm, 30/30/31/30/30/30
    { 0x5C56354F, 0x7BFF, 0x7FDE }, // Modest, 31/31/30/30/30/31
    { 0x5E554799, 0x7BFE, 0x7BFE }, // Bashful, 30/31/30/30/31/30
    { 0x5F26D04C, 0x7FDF, 0x7FDE }, // Serious, 31/30/31/30/30/31
    { 0x60108B91, 0x7BFE, 0x7BDF }, // Mild, 30/31/30/31/30/30
    { 0x62B91D08, 0x7BFF, 0x7FFE }, // Timid, 31/31/30/30/31/31
    { 0x64AB8976, 0x7FFF, 0x7BDF }, // Gentle, 31/31/31/31/30/30
    { 0x64DD6C1E, 0x7FFE, 0x7FDE }, // Lax, 30/31/31/30/30/31
    { 0x6557D55E, 0x7FDF, 0x7BFF }, // Calm, 31/30/31/31/31/30
    { 0x6589B806, 0x7FDE, 0x7FFF }, // Impish, 30/30/31/31/31/31
    { 0x67663419, 0x7BDF, 0x7BDE }, // Relaxed, 31/30/30/30/30/30
    { 0x679716C0, 0x7BDE, 0x7FDE }, // Impish, 30/30/30/30/30/31
    { 0x6B0E7130, 0x7FFE, 0x7BFF }, // Quiet, 30/31/31/31/31/30
    { 0x6D1CCFEB, 0x7BFE, 0x7BDE }, // Naughty, 30/31/30/30/30/30
    { 0x6DC81BD2, 0x7BDF, 0x7BFF }, // Mild, 31/30/30/31/31/30
    { 0x6DF9FE7A, 0x7BDE, 0x7FFE }, // Naughty, 30/30/30/30/31/31
    { 0x6F72469F, 0x7FFF, 0x7FFF }, // Lax, 31/31/31/31/31/31
    { 0x6FEC6AE8, 0x7FDE, 0x7BDF }, // Modest, 30/30/31/31/30/30
    { 0x7180A55A, 0x7BFF, 0x7FDE }, // Gentle, 31/31/30/30/30/31
    { 0x722DF141, 0x7BDF, 0x7FFF }, // Bold, 31/30/30/31/31/31
    { 0x726319B8, 0x7FDF, 0x7BFE }, // Sassy, 31/30/31/30/31/30
    { 0x737FB7A4, 0x7BFE, 0x7BFF }, // Quirky, 30/31/30/31/31/30
    { 0x741F5DAF, 0x7FDF, 0x7BDF }, // Bold, 31/30/31/31/30/30
    { 0x74504057, 0x7FDE, 0x7FDF }, // Relaxed, 30/30/31/31/30/31
    { 0x77E38D13, 0x7BFF, 0x7FFF }, // Mild, 31/31/30/31/31/31
    { 0x781AB58A, 0x7FFE, 0x7BFE }, // Bold, 30/31/31/30/31/30
    { 0x79D6F981, 0x7FFE, 0x7BDF }, // Jolly, 30/31/31/31/30/30
    { 0x7A07DC29, 0x7FFE, 0x7FDF }, // Modest, 30/31/31/31/30/31
    { 0x7AB32811, 0x7FDE, 0x7FFF }, // Adamant, 30/30/31/31/31/31
    { 0x7AD4602C, 0x7BDE, 0x7BFE }, // Naughty, 30/30/30/30/31/30
    { 0x7C7E8AF9, 0x7FFF, 0x7FFE }, // Sassy, 31/31/31/30/31/31
    { 0x7C90A424, 0x7BDF, 0x7BDF }, // Jolly, 31/30/30/31/30/30
    { 0x7CC186CB, 0x7BDE, 0x7FDE }, // Naive, 30/30/30/30/30/31
    { 0x7E3ACEF0, 0x7FFF, 0x7FDF }, // Bold, 31/31/31/31/30/31
    { 0x7F38359B, 0x7BDF, 0x7FFE }, // Gentle, 31/30/30/30/31/31
    { 0x808BFBFE, 0x7BFE, 0x7BFE }, // Serious, 30/31/30/30/31/30
    { 0x80F47993, 0x7BDF, 0x7FDF }, // Bold, 31/30/30/31/30/31
    { 0x812BA209, 0x7FDF, 0x7BDE }, // Bashful, 31/30/31/30/30/30
    { 0x815C84B1, 0x7FDE, 0x7FDE }, // Calm, 30/30/31/30/30/31
    { 0x82463FF5, 0x7BFE, 0x7BDF }, // Careful, 30/31/30/31/30/30
    { 0x84BEEEC5, 0x7BFF, 0x7BFE }, // Brave, 31/31/30/30/31/30
    { 0x84EFD16D, 0x7BFF, 0x7FFE }, // Naughty, 31/31/30/30/31/31
    { 0x86AB1565, 0x7BFF, 0x7FDF }, // Brave, 31/31/30/31/30/31
    { 0x86E13DDB, 0x7FFE, 0x7BDE }, // Naughty, 30/31/31/30/30/30
    { 0x87132083, 0x7FFE, 0x7FDE }, // Quiet, 30/31/31/30/30/31
    { 0x878E89C3, 0x7FDF, 0x7BFF }, // Naive, 31/30/31/31/31/30
    { 0x87BF6C6A, 0x7FDE, 0x7FFE }, // Modest, 30/30/31/30/31/31
    { 0x899CE87D, 0x7BDF, 0x7BDE }, // Hardy, 31/30/30/30/30/30
    { 0x8B46134A, 0x7FFF, 0x7FDE }, // Relaxed, 31/31/31/30/30/31
    { 0x8BF25F32, 0x7FDF, 0x7FFF }, // Docile, 31/30/31/31/31/31
    { 0x8D442595, 0x7FFE, 0x7BFF }, // Hardy, 30/31/31/31/31/30
    { 0x8E00BDEC, 0x7BDF, 0x7FDE }, // Quiet, 31/30/30/30/30/31
    { 0x8F52844F, 0x7BFE, 0x7BDE }, // Hasty, 30/31/30/30/30/30
    { 0x8FFED037, 0x7BDE, 0x7BFE }, // Timid, 30/30/30/30/31/30
    { 0x91A9FB04, 0x7FFF, 0x7FFF }, // Naive, 31/31/31/31/31/31
    { 0x93857716, 0x7BFF, 0x7BDE }, // Lonely, 31/31/30/30/30/30
    { 0x93B759BE, 0x7BFF, 0x7FDE }, // Naive, 31/31/30/30/30/31
    { 0x9463A5A6, 0x7BDF, 0x7FFF }, // Jolly, 31/30/30/31/31/31
    { 0x96551214, 0x7FDF, 0x7BDF }, // Jolly, 31/30/31/31/30/30
    { 0x9686F4BC, 0x7FDE, 0x7FDE }, // Lonely, 30/30/31/30/30/31
    { 0x98FEA38B, 0x7FDF, 0x7FFE }, // Bashful, 31/30/31/30/31/31
    { 0x99E85ED0, 0x7BFF, 0x7BFF }, // Sassy, 31/31/30/31/31/30
    { 0x9A194178, 0x7BFE, 0x7FFF }, // Quirky, 30/31/30/31/31/31
    { 0x9C0CADE6, 0x7FFE, 0x7BDF }, // Gentle, 30/31/31/31/30/30
    { 0x9CB8F9CE, 0x7FDE, 0x7BFF }, // Calm, 30/30/31/31/31/30
    { 0x9E835CB6, 0x7FFF, 0x7BFE }, // Adamant, 31/31/31/30/31/30
    { 0x9EB43F5D, 0x7FFF, 0x7FFE }, // Naughty, 31/31/31/30/31/31
    { 0x9EC65888, 0x7BDE, 0x7BDE }, // Calm, 30/30/30/30/30/30
    { 0xA0708355, 0x7FFF, 0x7FDF }, // Jolly, 31/31/31/31/30/31
    { 0xA26F959F, 0x7FFE, 0x7BFF }, // Mild, 30/31/31/31/31/30
    { 0xA32A2DF7, 0x7BDF, 0x7FDF }, // Serious, 31/30/30/31/30/31
    { 0xA361566E, 0x7FDF, 0x7BDE }, // Lonely, 31/30/31/30/30/30
    { 0xA5294042, 0x7BDE, 0x7BFF }, // Mild, 30/30/30/31/31/30
    { 0xA6F4A32A, 0x7BFF, 0x7BFE }, // Timid, 31/31/30/30/31/30
    { 0xA8B0E721, 0x7BFF, 0x7BDF }, // Bashful, 31/31/30/31/30/30
    { 0xA8E1C9C9, 0x7BFE, 0x7FDF }, // Calm, 30/31/30/31/30/31
    { 0xA918F23F, 0x7FFE, 0x7BDE }, // Impish, 30/31/31/30/30/30
    { 0xA98D15B1, 0x7BDF, 0x7FFF }, // Impish, 31/30/30/31/31/31
    { 0xA9C43E27, 0x7FDE, 0x7BFE }, // Gentle, 30/30/31/30/31/30
    { 0xABB164C7, 0x7FDE, 0x7FDF }, // Relaxed, 30/30/31/31/30/31
    { 0xAD7CC7AF, 0x7FFF, 0x7FDE }, // Lonely, 31/31/31/30/30/31
    { 0xAE281396, 0x7FDF, 0x7FFE }, // Jolly, 31/30/31/30/31/31
    { 0xAF44B183, 0x7BFE, 0x7FFF }, // Mild, 30/31/30/31/31/31
    { 0xAF7AD9F9, 0x7FFE, 0x7BFE }, // Bashful, 30/31/31/30/31/30
    { 0xB235849B, 0x7BDE, 0x7BFE }, // Adamant, 30/30/30/30/31/30
    { 0xB3ADCCC0, 0x7FFF, 0x7BFF }, // Impish, 31/31/31/31/31/30
    { 0xB3DFAF68, 0x7FFE, 0x7FFE }, // Gentle, 30/31/31/30/31/31
    { 0xB3F0C893, 0x7BDE, 0x7BDF }, // Lonely, 30/30/30/31/30/30
    { 0xB5BC2B7B, 0x7BFF, 0x7BDE }, // Calm, 31/31/30/30/30/30
    { 0xB6687763, 0x7BDF, 0x7BFF }, // Rash, 31/30/30/31/31/30
    { 0xB6995A0B, 0x7BDE, 0x7FFE }, // Gentle, 30/30/30/30/31/31
    { 0xB8559E02, 0x7BDF, 0x7FDF }, // Naughty, 31/30/30/31/30/31
    { 0xB88BC678, 0x7FDE, 0x7BDE }, // Docile, 30/30/31/30/30/30
    { 0xB8BDA920, 0x7FDE, 0x7FDE }, // Rash, 30/30/31/30/30/31
    { 0xBC1E1335, 0x7BFF, 0x7BFF }, // Bold, 31/31/30/31/31/30
    { 0xBC50F5DD, 0x7BFE, 0x7FFE }, // Naughty, 30/31/30/30/31/31
    { 0xBCF09BE8, 0x7FDF, 0x7FDF }, // Timid, 31/30/31/31/30/31
    { 0xBE0B39D4, 0x7BFE, 0x7FDF }, // Modest, 30/31/30/31/30/31
    { 0xBE42624A, 0x7FFE, 0x7BDE }, // Adamant, 30/31/31/30/30/30
    { 0xBEEEAE32, 0x7FDE, 0x7BFF }, // Brave, 30/30/31/31/31/30
    { 0xC083E8A4, 0x7BFF, 0x7FFF }, // Rash, 31/31/30/31/31/31
    { 0xC0B9111A, 0x7FFF, 0x7BFE }, // Timid, 31/31/31/30/31/30
    { 0xC0FC0CED, 0x7BDE, 0x7BDE }, // Adamant, 30/30/30/30/30/30
    { 0xC2755512, 0x7FFF, 0x7BDF }, // Rash, 31/31/31/31/30/30
    { 0xC2A637BA, 0x7FFE, 0x7FDF }, // Gentle, 30/31/31/31/30/31
    { 0xC35283A1, 0x7FDF, 0x7FFF }, // Rash, 31/30/31/31/31/31
    { 0xC52FFFB4, 0x7BDF, 0x7BDF }, // Naughty, 31/30/30/31/30/30
    { 0xC561E25C, 0x7BDF, 0x7FDE }, // Quiet, 31/30/30/30/30/31
    { 0xC9091F73, 0x7FFE, 0x7FFF }, // Mild, 30/31/31/31/31/31
    { 0xCAE69B86, 0x7BFF, 0x7BDF }, // Lonely, 31/31/30/31/30/30
    { 0xCB177E2E, 0x7BFE, 0x7FDE }, // Adamant, 30/31/30/30/30/31
    { 0xCB92E76E, 0x7BDF, 0x7BFF }, // Hardy, 31/30/30/31/31/30
    { 0xCBC3CA16, 0x7BDE, 0x7FFF }, // Brave, 30/30/30/31/31/31
    { 0xCBFAF28C, 0x7FDE, 0x7BFE }, // Modest, 30/30/31/30/31/30
    { 0xCD8F2CFE, 0x7BFF, 0x7FFE }, // Gentle, 31/31/30/30/31/31
    { 0xCDB63683, 0x7FDE, 0x7BDF }, // Serious, 30/30/31/31/30/30
    { 0xCF4A70F5, 0x7BFF, 0x7FDF }, // Bashful, 31/31/30/31/30/31
    { 0xCF81996B, 0x7FFF, 0x7BDE }, // Docile, 31/31/31/30/30/30
    { 0xD02DE553, 0x7FDF, 0x7BFE }, // Bold, 31/30/31/30/31/30
    { 0xD05EC7FB, 0x7FDF, 0x7FFE }, // Relaxed, 31/30/31/30/31/31
    { 0xD1498340, 0x7BFE, 0x7BFF }, // Sassy, 30/31/30/31/31/30
    { 0xD21A0BF3, 0x7FDF, 0x7FDF }, // Bold, 31/30/31/31/30/31
    { 0xD5E48125, 0x7FFF, 0x7BFE }, // Brave, 31/31/31/30/31/30
    { 0xD61563CD, 0x7FFE, 0x7FFE }, // Naughty, 30/31/31/30/31/31
    { 0xD7D1A7C5, 0x7FFE, 0x7FDF }, // Jolly, 30/31/31/31/30/31
    { 0xD89E2BC7, 0x7BDF, 0x7BFE }, // Lonely, 31/30/30/30/31/30
    { 0xD8CF0E6F, 0x7BDE, 0x7FFE }, // Adamant, 30/30/30/30/31/31
    { 0xDA485694, 0x7FFF, 0x7FFF }, // Rash, 31/31/31/31/31/31
    { 0xDA5A6FBF, 0x7BDF, 0x7BDF }, // Timid, 31/30/30/31/30/30
    { 0xDA8B5267, 0x7BDE, 0x7FDF }, // Serious, 30/30/30/31/30/31
    { 0xDAC27ADD, 0x7FDE, 0x7BDE }, // Hardy, 30/30/31/30/30/30
    { 0xDC56B54F, 0x7BFF, 0x7FDE }, // Docile, 31/31/30/30/30/31
    { 0xDE55C799, 0x7BFE, 0x7BFE }, // Lax, 30/31/30/30/31/30
    { 0xDF26504C, 0x7FDF, 0x7FDE }, // Quiet, 31/30/31/30/30/31
    { 0xE0100B91, 0x7BFE, 0x7BDF }, // Gentle, 30/31/30/31/30/30
    { 0xE2B99D08, 0x7BFF, 0x7FFE }, // Lonely, 31/31/30/30/31/31
    { 0xE4AB0976, 0x7FFF, 0x7BDF }, // Lonely, 31/31/31/31/30/30
    { 0xE4DDEC1E, 0x7FFE, 0x7FDE }, // Hardy, 30/31/31/30/30/31
    { 0xE557555E, 0x7FDF, 0x7BFF }, // Hardy, 31/30/31/31/31/30
    { 0xE5893806, 0x7FDE, 0x7FFF }, // Jolly, 30/30/31/31/31/31
    { 0xE766B419, 0x7BDF, 0x7BDE }, // Careful, 31/30/30/30/30/30
    { 0xE79796C0, 0x7BDE, 0x7FDE }, // Quirky, 30/30/30/30/30/31
    { 0xEB0EF130, 0x7FFE, 0x7BFF }, // Impish, 30/31/31/31/31/30
    { 0xED1C4FEB, 0x7BFE, 0x7BDE }, // Lax, 30/31/30/30/30/30
    { 0xEDC89BD2, 0x7BDF, 0x7BFF }, // Relaxed, 31/30/30/31/31/30
    { 0xEDF97E7A, 0x7BDE, 0x7FFE }, // Lax, 30/30/30/30/31/31
    { 0xEF72C69F, 0x7FFF, 0x7FFF }, // Hardy, 31/31/31/31/31/31
    { 0xEFECEAE8, 0x7FDE, 0x7BDF }, // Docile, 30/30/31/31/30/30
    { 0xF180255A, 0x7BFF, 0x7FDE }, // Lonely, 31/31/30/30/30/31
    { 0xF22D7141, 0x7BDF, 0x7FFF }, // Timid, 31/30/30/31/31/31
    { 0xF26399B8, 0x7FDF, 0x7BFE }, // Jolly, 31/30/31/30/31/30
    { 0xF37F37A4, 0x7BFE, 0x7BFF }, // Naughty, 30/31/30/31/31/30
    { 0xF41FDDAF, 0x7FDF, 0x7BDF }, // Gentle, 31/30/31/31/30/30
    { 0xF450C057, 0x7FDE, 0x7FDF }, // Careful, 30/30/31/31/30/31
    { 0xF7E30D13, 0x7BFF, 0x7FFF }, // Gentle, 31/31/30/31/31/31
    { 0xF81A358A, 0x7FFE, 0x7BFE }, // Timid, 30/31/31/30/31/30
    { 0xF9D67981, 0x7FFE, 0x7BDF }, // Bashful, 30/31/31/31/30/30
    { 0xFA075C29, 0x7FFE, 0x7FDF }, // Calm, 30/31/31/31/30/31
    { 0xFAB3A811, 0x7FDE, 0x7FFF }, // Rash, 30/30/31/31/31/31
    { 0xFAD4E02C, 0x7BDE, 0x7BFE }, // Calm, 30/30/30/30/31/30
    { 0xFC7E0AF9, 0x7FFF, 0x7FFE }, // Brave, 31/31/31/30/31/31
    { 0xFC902424, 0x7BDF, 0x7BDF }, // Bashful, 31/30/30/31/30/30
    { 0xFCC106CB, 0x7BDE, 0x7FDE }, // Rash, 30/30/30/30/30/31
    { 0xFE3A4EF0, 0x7FFF, 0x7FDF }, // Timid, 31/31/31/31/30/31
    { 0xFF38B59B, 0x7BDF, 0x7FFE }, // Serious, 31/30/30/30/31/31
    { 0x01214FC5, 0x7C3F, 0x7FDF }, // Hardy, 31/1/31/31/30/31 [NPC]
    { 0x031F620F, 0x7C3E, 0x7BFF }, // Quiet, 30/1/31/31/31/30 [NPC]
    { 0x03DBFA67, 0x781F, 0x7FDF }, // Timid, 31/0/30/31/30/31 [NPC]
    { 0x041222DD, 0x7C1F, 0x7BDE }, // Serious, 31/0/31/30/30/30 [NPC]
    { 0x052DC0CA, 0x783E, 0x7BDE }, // Naughty, 30/1/30/30/30/30 [NPC]
    { 0x05D90CB2, 0x781E, 0x7BFF }, // Quiet, 30/0/30/31/31/30 [NPC]
    { 0x07A56F9A, 0x783F, 0x7BFE }, // Sassy, 31/1/30/30/31/30 [NPC]
    { 0x0960B391, 0x783F, 0x7BDF }, // Rash, 31/1/30/31/30/30 [NPC]
    { 0x09929639, 0x783F, 0x7FDF }, // Relaxed, 31/1/30/31/30/31 [NPC]
    { 0x09C8BEAF, 0x7C3E, 0x7BDE }, // Lax, 30/1/31/30/30/30 [NPC]
    { 0x0A3EE221, 0x781F, 0x7FFF }, // Docile, 31/0/30/31/31/31 [NPC]
    { 0x0A740A97, 0x7C1F, 0x7BFE }, // Sassy, 31/0/31/30/31/30 [NPC]
    { 0x0AA6ED3F, 0x7C1E, 0x7FFE }, // Gentle, 30/0/31/30/31/31 [NPC]
    { 0x0C613137, 0x7C1E, 0x7FDF }, // Impish, 30/0/31/31/30/31 [NPC]
    { 0x0E2D941F, 0x7C3F, 0x7FDE }, // Jolly, 31/1/31/30/30/31 [NPC]
    { 0x0ED9E006, 0x7C1F, 0x7FFE }, // Hasty, 31/0/31/30/31/31 [NPC]
    { 0x0FF47DF3, 0x783E, 0x7FFF }, // Quiet, 30/1/30/31/31/31 [NPC]
    { 0x102BA669, 0x7C3E, 0x7BFE }, // Bold, 30/1/31/30/31/30 [NPC]
    { 0x12E5510B, 0x781E, 0x7BFE }, // Naughty, 30/0/30/30/31/30 [NPC]
    { 0x145E9930, 0x7C3F, 0x7BFF }, // Calm, 31/1/31/31/31/30 [NPC]
    { 0x148F7BD8, 0x7C3F, 0x7FFE }, // Sassy, 31/1/31/30/31/31 [NPC]
    { 0x14A19503, 0x781E, 0x7BDF }, // Jolly, 30/0/30/31/30/30 [NPC]
    { 0x166CF7EB, 0x783F, 0x7BDE }, // Relaxed, 31/1/30/30/30/30 [NPC]
    { 0x174A267B, 0x781F, 0x7FFE }, // Impish, 31/0/30/30/31/31 [NPC]
    { 0x19056A72, 0x781F, 0x7FDF }, // Bold, 31/0/30/31/30/31 [NPC]
    { 0x193C92E8, 0x7C1F, 0x7BDE }, // Bashful, 31/0/31/30/30/30 [NPC]
    { 0x196D7590, 0x7C1E, 0x7FDE }, // Calm, 30/0/31/30/30/31 [NPC]
    { 0x1CCFDFA5, 0x783F, 0x7BFF }, // Adamant, 31/1/30/31/31/30 [NPC]
    { 0x1D00C24D, 0x783E, 0x7FFE }, // Bold, 30/1/30/30/31/31 [NPC]
    { 0x1DA06858, 0x7C1F, 0x7FDF }, // Hasty, 31/0/31/31/30/31 [NPC]
    { 0x1EBC0644, 0x783E, 0x7FDF }, // Brave, 30/1/30/31/30/31 [NPC]
    { 0x1EF32EBA, 0x7C3E, 0x7BDE }, // Modest, 30/1/31/30/30/30 [NPC]
    { 0x1F9F7AA2, 0x7C1E, 0x7BFF }, // Naive, 30/0/31/31/31/30 [NPC]
    { 0x216ADD8A, 0x7C3F, 0x7BFE }, // Impish, 31/1/31/30/31/30 [NPC]
    { 0x21ADD95D, 0x781E, 0x7BDE }, // Lonely, 30/0/30/30/30/30 [NPC]
    { 0x2357042A, 0x7C3F, 0x7FDE }, // Impish, 31/1/31/30/30/31 [NPC]
    { 0x24035011, 0x7C1F, 0x7FFF }, // Docile, 31/0/31/31/31/31 [NPC]
    { 0x2611AECC, 0x781F, 0x7FDE }, // Bashful, 31/0/30/30/30/31 [NPC]
    { 0x2810C116, 0x781E, 0x7BFF }, // Gentle, 30/0/30/31/31/30 [NPC]
    { 0x29BAEBE3, 0x7C3E, 0x7FFF }, // Naive, 30/1/31/31/31/31 [NPC]
    { 0x2B9767F6, 0x783F, 0x7BDF }, // Jolly, 31/1/30/31/30/30 [NPC]
    { 0x2BC84A9E, 0x783E, 0x7FDE }, // Modest, 30/1/30/30/30/31 [NPC]
    { 0x2C43B3DE, 0x781F, 0x7BFF }, // Serious, 31/0/30/31/31/30 [NPC]
    { 0x2C749686, 0x781E, 0x7FFF }, // Naive, 30/0/30/31/31/31 [NPC]
    { 0x2CABBEFC, 0x7C1E, 0x7BFE }, // Brave, 30/0/31/30/31/30 [NPC]
    { 0x2E6602F3, 0x7C1E, 0x7BDF }, // Jolly, 30/0/31/31/30/30 [NPC]
    { 0x2E98E59B, 0x7C1E, 0x7FDF }, // Serious, 30/0/31/31/30/31 [NPC]
    { 0x310F946B, 0x7C1F, 0x7FFE }, // Rash, 31/0/31/30/31/31 [NPC]
    { 0x31F94FB0, 0x783E, 0x7BFF }, // Careful, 30/1/30/31/31/30 [NPC]
    { 0x322B3257, 0x783E, 0x7FFF }, // Timid, 30/1/30/31/31/31 [NPC]
    { 0x32CBD863, 0x7C1F, 0x7FDF }, // Adamant, 31/0/31/31/30/31 [NPC]
    { 0x341D9EC5, 0x7C3E, 0x7BDF }, // Gentle, 30/1/31/31/30/30 [NPC]
    { 0x36944D95, 0x7C3F, 0x7BFE }, // Adamant, 31/1/31/30/31/30 [NPC]
    { 0x36C6303D, 0x7C3E, 0x7FFE }, // Mild, 30/1/31/30/31/31 [NPC]
    { 0x36D74968, 0x781E, 0x7BDF }, // Gentle, 30/0/30/31/30/30 [NPC]
    { 0x38817435, 0x7C3E, 0x7FDF }, // Naive, 30/1/31/31/30/31 [NPC]
    { 0x394FF837, 0x781F, 0x7BFE }, // Quirky, 31/0/30/30/31/30 [NPC]
    { 0x3980DADF, 0x781E, 0x7FFE }, // Lonely, 30/0/30/30/31/31 [NPC]
    { 0x3B0A3C2F, 0x781F, 0x7BDF }, // Hasty, 31/0/30/31/30/30 [NPC]
    { 0x3B3C1ED7, 0x781F, 0x7FDF }, // Quirky, 31/0/30/31/30/31 [NPC]
    { 0x3B72474D, 0x7C1E, 0x7BDE }, // Lonely, 30/0/31/30/30/30 [NPC]
    { 0x3F059409, 0x783E, 0x7BFE }, // Timid, 30/1/30/30/31/30 [NPC]
    { 0x3F3776B1, 0x783E, 0x7FFE }, // Careful, 30/1/30/30/31/31 [NPC]
    { 0x3FD71CBC, 0x7C1F, 0x7FDE }, // Naughty, 31/0/31/30/30/31 [NPC]
    { 0x40C1D801, 0x783F, 0x7BDF }, // Rash, 31/1/30/31/30/30 [NPC]
    { 0x40F2BAA9, 0x783E, 0x7FDF }, // Gentle, 30/1/30/31/30/31 [NPC]
    { 0x4129E31F, 0x7C3E, 0x7BDE }, // Lax, 30/1/31/30/30/30 [NPC]
    { 0x41D52F07, 0x7C1E, 0x7BFE }, // Sassy, 30/0/31/30/31/30 [NPC]
    { 0x436A6978, 0x783F, 0x7FFE }, // Jolly, 31/1/30/30/31/31 [NPC]
    { 0x455CD5E6, 0x7C3F, 0x7BDE }, // Quirky, 31/1/31/30/30/30 [NPC]
    { 0x458DB88E, 0x7C3E, 0x7FDE }, // Lonely, 30/1/31/30/30/31 [NPC]
    { 0x460821CE, 0x7C1F, 0x7BFF }, // Serious, 31/0/31/31/31/30 [NPC]
    { 0x46390476, 0x7C1F, 0x7FFF }, // Naive, 31/0/31/31/31/31 [NPC]
    { 0x48168089, 0x781F, 0x7BDE }, // Quirky, 31/0/30/30/30/30 [NPC]
    { 0x48476330, 0x781F, 0x7FDE }, // Hardy, 31/0/30/30/30/31 [NPC]
    { 0x4BBFBDA0, 0x7C3F, 0x7BFF }, // Calm, 31/1/31/31/31/30 [NPC]
    { 0x4BF0A048, 0x7C3E, 0x7FFF }, // Sassy, 30/1/31/31/31/31 [NPC]
    { 0x4DCD1C5A, 0x783F, 0x7BDE }, // Calm, 31/1/30/30/30/30 [NPC]
    { 0x4DFEFF02, 0x783E, 0x7FDE }, // Impish, 30/1/30/30/30/31 [NPC]
    { 0x4E796842, 0x781F, 0x7BFF }, // Rash, 31/0/30/31/31/30 [NPC]
    { 0x4EAA4AEA, 0x781E, 0x7FFE }, // Gentle, 30/0/30/30/31/31 [NPC]
    { 0x5023930F, 0x7C3F, 0x7FFF }, // Serious, 31/1/31/31/31/31 [NPC]
    { 0x509DB758, 0x7C1E, 0x7BDF }, // Bashful, 30/0/31/31/30/30 [NPC]
    { 0x5231F1CA, 0x783F, 0x7FDE }, // Quirky, 31/1/30/30/30/31 [NPC]
    { 0x53146628, 0x7C1F, 0x7BFE }, // Hardy, 31/0/31/30/31/30 [NPC]
    { 0x54300414, 0x783E, 0x7BFF }, // Mild, 30/1/30/31/31/30 [NPC]
    { 0x55018CC7, 0x7C1F, 0x7FDF }, // Timid, 31/0/31/31/30/31 [NPC]
    { 0x5894D983, 0x783F, 0x7FFF }, // Rash, 31/1/30/31/31/31 [NPC]
    { 0x58CB01FA, 0x7C3F, 0x7BFE }, // Sassy, 31/1/31/30/31/30 [NPC]
    { 0x5A8645F1, 0x7C3F, 0x7BDF }, // Rash, 31/1/31/31/30/30 [NPC]
    { 0x5AB82899, 0x7C3E, 0x7FDF }, // Relaxed, 30/1/31/31/30/31 [NPC]
    { 0x5B647481, 0x7C1E, 0x7FFF }, // Docile, 30/0/31/31/31/31 [NPC]
    { 0x5B85AC9C, 0x781F, 0x7BFE }, // Relaxed, 31/0/30/30/31/30 [NPC]
    { 0x5D2FD769, 0x7C3F, 0x7FFE }, // Hardy, 31/1/31/30/31/31 [NPC]
    { 0x5D41F093, 0x781F, 0x7BDF }, // Modest, 31/0/30/31/30/30 [NPC]
    { 0x5D72D33B, 0x781E, 0x7FDE }, // Quiet, 30/0/30/30/30/31 [NPC]
    { 0x613B486E, 0x783E, 0x7BFE }, // Bashful, 30/1/30/30/31/30 [NPC]
    { 0x61DCEE79, 0x7C1F, 0x7BDE }, // Gentle, 31/0/31/30/30/30 [NPC]
    { 0x620DD121, 0x7C1F, 0x7FDE }, // Careful, 31/0/31/30/30/31 [NPC]
    { 0x62F78C65, 0x783E, 0x7BDF }, // Lonely, 30/1/30/31/30/30 [NPC]
    { 0x63D5BAF5, 0x781E, 0x7FFF }, // Jolly, 30/0/30/31/31/31 [NPC]
    { 0x65A01DDD, 0x783F, 0x7FFE }, // Gentle, 31/1/30/30/31/31 [NPC]
    { 0x65C72763, 0x7C1E, 0x7BDF }, // Jolly, 30/0/31/31/30/30 [NPC]
    { 0x675C61D5, 0x783F, 0x7FDF }, // Bold, 31/1/30/31/30/31 [NPC]
    { 0x67928A4B, 0x7C3F, 0x7BDE }, // Relaxed, 31/1/31/30/30/30 [NPC]
    { 0x67C36CF3, 0x7C3E, 0x7FDE }, // Lax, 30/1/31/30/30/31 [NPC]
    { 0x683ED633, 0x7C1F, 0x7BFF }, // Docile, 31/0/31/31/31/30 [NPC]
    { 0x6870B8DA, 0x7C1E, 0x7FFE }, // Bashful, 30/0/31/30/31/31 [NPC]
    { 0x6A4C34ED, 0x781F, 0x7BDE }, // Docile, 31/0/30/30/30/30 [NPC]
    { 0x6DF57205, 0x7C3E, 0x7BFF }, // Adamant, 30/1/31/31/31/30 [NPC]
    { 0x7003D0BF, 0x783E, 0x7BDE }, // Naive, 30/1/30/30/30/30 [NPC]
    { 0x70AF1CA7, 0x781E, 0x7BFE }, // Brave, 30/0/30/30/31/30 [NPC]
    { 0x70E0FF4F, 0x781E, 0x7FFE }, // Modest, 30/0/30/30/31/31 [NPC]
    { 0x72594774, 0x7C3F, 0x7FFF }, // Calm, 31/1/31/31/31/31 [NPC]
    { 0x729C4346, 0x781E, 0x7FDF }, // Serious, 30/0/30/31/30/31 [NPC]
    { 0x72D36BBC, 0x7C1E, 0x7BDE }, // Hardy, 30/0/31/30/30/30 [NPC]
    { 0x7467A62E, 0x783F, 0x7FDE }, // Docile, 31/1/30/30/30/31 [NPC]
    { 0x7514F216, 0x781F, 0x7FFF }, // Mild, 31/0/30/31/31/31 [NPC]
    { 0x7666B879, 0x783E, 0x7BFE }, // Timid, 30/1/30/30/31/30 [NPC]
    { 0x77065E84, 0x7C1F, 0x7BDF }, // Mild, 31/0/31/31/30/30 [NPC]
    { 0x7737412C, 0x7C1E, 0x7FDE }, // Bashful, 30/0/31/30/30/31 [NPC]
    { 0x7A99AB40, 0x783F, 0x7BFF }, // Hardy, 31/1/30/31/31/30 [NPC]
    { 0x7ACA8DE8, 0x783E, 0x7FFF }, // Brave, 30/1/30/31/31/31 [NPC]
    { 0x7CBDFA56, 0x7C3E, 0x7BDF }, // Quirky, 30/1/31/31/30/30 [NPC]
    { 0x7CEEDCFE, 0x7C3E, 0x7FDE }, // Lonely, 30/1/31/30/30/31 [NPC]
    { 0x7D69463E, 0x7C1F, 0x7BFF }, // Serious, 31/0/31/31/31/30 [NPC]
    { 0x7D9A28E5, 0x7C1E, 0x7FFF }, // Jolly, 30/0/31/31/31/31 [NPC]
    { 0x7F658BCD, 0x7C3F, 0x7FFE }, // Relaxed, 31/1/31/30/31/31 [NPC]
    { 0x7F77A4F8, 0x781F, 0x7BDE }, // Careful, 31/0/30/30/30/30 [NPC]
    { 0x7FA887A0, 0x781E, 0x7FDE }, // Hardy, 30/0/30/30/30/31 [NPC]
    { 0x8121CFC5, 0x7C3F, 0x7FDF }, // Mild, 31/1/31/31/30/31 [NPC]
    { 0x831FE20F, 0x7C3E, 0x7BFF }, // Impish, 30/1/31/31/31/30 [NPC]
    { 0x83DB7A67, 0x781F, 0x7FDF }, // Modest, 31/0/30/31/30/31 [NPC]
    { 0x8412A2DD, 0x7C1F, 0x7BDE }, // Adamant, 31/0/31/30/30/30 [NPC]
    { 0x852D40CA, 0x783E, 0x7BDE }, // Lax, 30/1/30/30/30/30 [NPC]
    { 0x85D98CB2, 0x781E, 0x7BFF }, // Impish, 30/0/30/31/31/30 [NPC]
    { 0x87A5EF9A, 0x783F, 0x7BFE }, // Jolly, 31/1/30/30/31/30 [NPC]
    { 0x89603391, 0x783F, 0x7BDF }, // Quirky, 31/1/30/31/30/30 [NPC]
    { 0x89921639, 0x783F, 0x7FDF }, // Serious, 31/1/30/31/30/31 [NPC]
    { 0x89C83EAF, 0x7C3E, 0x7BDE }, // Naive, 30/1/31/30/30/30 [NPC]
    { 0x8A3E6221, 0x781F, 0x7FFF }, // Hasty, 31/0/30/31/31/31 [NPC]
    { 0x8A748A97, 0x7C1F, 0x7BFE }, // Jolly, 31/0/31/30/31/30 [NPC]
    { 0x8AA66D3F, 0x7C1E, 0x7FFE }, // Lonely, 30/0/31/30/31/31 [NPC]
    { 0x8C61B137, 0x7C1E, 0x7FDF }, // Quirky, 30/0/31/31/30/31 [NPC]
    { 0x8E2D141F, 0x7C3F, 0x7FDE }, // Bashful, 31/1/31/30/30/31 [NPC]
    { 0x8ED96006, 0x7C1F, 0x7FFE }, // Mild, 31/0/31/30/31/31 [NPC]
    { 0x8FF4FDF3, 0x783E, 0x7FFF }, // Impish, 30/1/30/31/31/31 [NPC]
    { 0x902B2669, 0x7C3E, 0x7BFE }, // Timid, 30/1/31/30/31/30 [NPC]
    { 0x92E5D10B, 0x781E, 0x7BFE }, // Calm, 30/0/30/30/31/30 [NPC]
    { 0x945E1930, 0x7C3F, 0x7BFF }, // Hardy, 31/1/31/31/31/30 [NPC]
    { 0x948FFBD8, 0x7C3F, 0x7FFE }, // Jolly, 31/1/31/30/31/31 [NPC]
    { 0x94A11503, 0x781E, 0x7BDF }, // Bashful, 30/0/30/31/30/30 [NPC]
    { 0x966C77EB, 0x783F, 0x7BDE }, // Serious, 31/1/30/30/30/30 [NPC]
    { 0x974AA67B, 0x781F, 0x7FFE }, // Quirky, 31/0/30/30/31/31 [NPC]
    { 0x9905EA72, 0x781F, 0x7FDF }, // Gentle, 31/0/30/31/30/31 [NPC]
    { 0x993C12E8, 0x7C1F, 0x7BDE }, // Careful, 31/0/31/30/30/30 [NPC]
    { 0x996DF590, 0x7C1E, 0x7FDE }, // Hasty, 30/0/31/30/30/31 [NPC]
    { 0x9CCF5FA5, 0x783F, 0x7BFF }, // Impish, 31/1/30/31/31/30 [NPC]
    { 0x9D00424D, 0x783E, 0x7FFE }, // Timid, 30/1/30/30/31/31 [NPC]
    { 0x9DA0E858, 0x7C1F, 0x7FDF }, // Brave, 31/0/31/31/30/31 [NPC]
    { 0x9EBC8644, 0x783E, 0x7FDF }, // Bashful, 30/1/30/31/30/31 [NPC]
    { 0x9EF3AEBA, 0x7C3E, 0x7BDE }, // Docile, 30/1/31/30/30/30 [NPC]
    { 0x9F9FFAA2, 0x7C1E, 0x7BFF }, // Bold, 30/0/31/31/31/30 [NPC]
    { 0xA16A5D8A, 0x7C3F, 0x7BFE }, // Jolly, 31/1/31/30/31/30 [NPC]
    { 0xA1AD595D, 0x781E, 0x7BDE }, // Docile, 30/0/30/30/30/30 [NPC]
    { 0xA357842A, 0x7C3F, 0x7FDE }, // Quirky, 31/1/31/30/30/31 [NPC]
    { 0xA403D011, 0x7C1F, 0x7FFF }, // Sassy, 31/0/31/31/31/31 [NPC]
    { 0xA6112ECC, 0x781F, 0x7FDE }, // Careful, 31/0/30/30/30/31 [NPC]
    { 0xA8104116, 0x781E, 0x7BFF }, // Lonely, 30/0/30/31/31/30 [NPC]
    { 0xA9BA6BE3, 0x7C3E, 0x7FFF }, // Rash, 30/1/31/31/31/31 [NPC]
    { 0xAB97E7F6, 0x783F, 0x7BDF }, // Naughty, 31/1/30/31/30/30 [NPC]
    { 0xABC8CA9E, 0x783E, 0x7FDE }, // Docile, 30/1/30/30/30/31 [NPC]
    { 0xAC4333DE, 0x781F, 0x7BFF }, // Quiet, 31/0/30/31/31/30 [NPC]
    { 0xAC741686, 0x781E, 0x7FFF }, // Rash, 30/0/30/31/31/31 [NPC]
    { 0xACAB3EFC, 0x7C1E, 0x7BFE }, // Relaxed, 30/0/31/30/31/30 [NPC]
    { 0xAE6682F3, 0x7C1E, 0x7BDF }, // Naughty, 30/0/31/31/30/30 [NPC]
    { 0xAE98659B, 0x7C1E, 0x7FDF }, // Quiet, 30/0/31/31/30/31 [NPC]
    { 0xB10F146B, 0x7C1F, 0x7FFE }, // Quirky, 31/0/31/30/31/31 [NPC]
    { 0xB1F9CFB0, 0x783E, 0x7BFF }, // Naive, 30/1/30/31/31/30 [NPC]
    { 0xB22BB257, 0x783E, 0x7FFF }, // Lonely, 30/1/30/31/31/31 [NPC]
    { 0xB2CB5863, 0x7C1F, 0x7FDF }, // Impish, 31/0/31/31/30/31 [NPC]
    { 0xB41D1EC5, 0x7C3E, 0x7BDF }, // Lonely, 30/1/31/31/30/30 [NPC]
    { 0xB694CD95, 0x7C3F, 0x7BFE }, // Rash, 31/1/31/30/31/30 [NPC]
    { 0xB6C6B03D, 0x7C3E, 0x7FFE }, // Relaxed, 30/1/31/30/31/31 [NPC]
    { 0xB6D7C968, 0x781E, 0x7BDF }, // Serious, 30/0/30/31/30/30 [NPC]
    { 0xB881F435, 0x7C3E, 0x7FDF }, // Bold, 30/1/31/31/30/31 [NPC]
    { 0xB94F7837, 0x781F, 0x7BFE }, // Naughty, 31/0/30/30/31/30 [NPC]
    { 0xB9805ADF, 0x781E, 0x7FFE }, // Docile, 30/0/30/30/31/31 [NPC]
    { 0xBB0ABC2F, 0x781F, 0x7BDF }, // Brave, 31/0/30/31/30/30 [NPC]
    { 0xBB3C9ED7, 0x781F, 0x7FDF }, // Modest, 31/0/30/31/30/31 [NPC]
    { 0xBB72C74D, 0x7C1E, 0x7BDE }, // Quiet, 30/0/31/30/30/30 [NPC]
    { 0xBF051409, 0x783E, 0x7BFE }, // Modest, 30/1/30/30/31/30 [NPC]
    { 0xBF37F6B1, 0x783E, 0x7FFE }, // Naive, 30/1/30/30/31/31 [NPC]
    { 0xBFD79CBC, 0x7C1F, 0x7FDE }, // Calm, 31/0/31/30/30/31 [NPC]
    { 0xC0C15801, 0x783F, 0x7BDF }, // Quirky, 31/1/30/31/30/30 [NPC]
    { 0xC0F23AA9, 0x783E, 0x7FDF }, // Lonely, 30/1/30/31/30/31 [NPC]
    { 0xC129631F, 0x7C3E, 0x7BDE }, // Naive, 30/1/31/30/30/30 [NPC]
    { 0xC1D5AF07, 0x7C1E, 0x7BFE }, // Jolly, 30/0/31/30/31/30 [NPC]
    { 0xC36AE978, 0x783F, 0x7FFE }, // Naughty, 31/1/30/30/31/31 [NPC]
    { 0xC55C55E6, 0x7C3F, 0x7BDE }, // Naughty, 31/1/31/30/30/30 [NPC]
    { 0xC58D388E, 0x7C3E, 0x7FDE }, // Docile, 30/1/31/30/30/31 [NPC]
    { 0xC608A1CE, 0x7C1F, 0x7BFF }, // Adamant, 31/0/31/31/31/30 [NPC]
    { 0xC6398476, 0x7C1F, 0x7FFF }, // Bold, 31/0/31/31/31/31 [NPC]
    { 0xC8160089, 0x781F, 0x7BDE }, // Naughty, 31/0/30/30/30/30 [NPC]
    { 0xC847E330, 0x781F, 0x7FDE }, // Mild, 31/0/30/30/30/31 [NPC]
    { 0xCBBF3DA0, 0x7C3F, 0x7BFF }, // Hardy, 31/1/31/31/31/30 [NPC]
    { 0xCBF02048, 0x7C3E, 0x7FFF }, // Brave, 30/1/31/31/31/31 [NPC]
    { 0xCDCD9C5A, 0x783F, 0x7BDE }, // Hasty, 31/1/30/30/30/30 [NPC]
    { 0xCDFE7F02, 0x783E, 0x7FDE }, // Jolly, 30/1/30/30/30/31 [NPC]
    { 0xCE79E842, 0x781F, 0x7BFF }, // Timid, 31/0/30/31/31/30 [NPC]
    { 0xCEAACAEA, 0x781E, 0x7FFE }, // Serious, 30/0/30/30/31/31 [NPC]
    { 0xD023130F, 0x7C3F, 0x7FFF }, // Quiet, 31/1/31/31/31/31 [NPC]
    { 0xD09D3758, 0x7C1E, 0x7BDF }, // Careful, 30/0/31/31/30/30 [NPC]
    { 0xD23171CA, 0x783F, 0x7FDE }, // Naughty, 31/1/30/30/30/31 [NPC]
    { 0xD314E628, 0x7C1F, 0x7BFE }, // Mild, 31/0/31/30/31/30 [NPC]
    { 0xD4308414, 0x783E, 0x7BFF }, // Relaxed, 30/1/30/31/31/30 [NPC]
    { 0xD5010CC7, 0x7C1F, 0x7FDF }, // Modest, 31/0/31/31/30/31 [NPC]
    { 0xD8945983, 0x783F, 0x7FFF }, // Quirky, 31/1/30/31/31/31 [NPC]
    { 0xD8CB81FA, 0x7C3F, 0x7BFE }, // Jolly, 31/1/31/30/31/30 [NPC]
    { 0xDA86C5F1, 0x7C3F, 0x7BDF }, // Timid, 31/1/31/31/30/30 [NPC]
    { 0xDAB8A899, 0x7C3E, 0x7FDF }, // Careful, 30/1/31/31/30/31 [NPC]
    { 0xDB64F481, 0x7C1E, 0x7FFF }, // Sassy, 30/0/31/31/31/31 [NPC]
    { 0xDB852C9C, 0x781F, 0x7BFE }, // Serious, 31/0/30/30/31/30 [NPC]
    { 0xDD2F5769, 0x7C3F, 0x7FFE }, // Bold, 31/1/31/30/31/31 [NPC]
    { 0xDD417093, 0x781F, 0x7BDF }, // Calm, 31/0/30/31/30/30 [NPC]
    { 0xDD72533B, 0x781E, 0x7FDE }, // Sassy, 30/0/30/30/30/31 [NPC]
    { 0xE13BC86E, 0x783E, 0x7BFE }, // Lax, 30/1/30/30/31/30 [NPC]
    { 0xE1DC6E79, 0x7C1F, 0x7BDE }, // Lonely, 31/0/31/30/30/30 [NPC]
    { 0xE20D5121, 0x7C1F, 0x7FDE }, // Adamant, 31/0/31/30/30/31 [NPC]
    { 0xE2F70C65, 0x783E, 0x7BDF }, // Docile, 30/1/30/31/30/30 [NPC]
    { 0xE3D53AF5, 0x781E, 0x7FFF }, // Bashful, 30/0/30/31/31/31 [NPC]
    { 0xE5A09DDD, 0x783F, 0x7FFE }, // Serious, 31/1/30/30/31/31 [NPC]
    { 0xE5C7A763, 0x7C1E, 0x7BDF }, // Naughty, 30/0/31/31/30/30 [NPC]
    { 0xE75CE1D5, 0x783F, 0x7FDF }, // Gentle, 31/1/30/31/30/31 [NPC]
    { 0xE7920A4B, 0x7C3F, 0x7BDE }, // Serious, 31/1/31/30/30/30 [NPC]
    { 0xE7C3ECF3, 0x7C3E, 0x7FDE }, // Hardy, 30/1/31/30/30/31 [NPC]
    { 0xE83E5633, 0x7C1F, 0x7BFF }, // Hasty, 31/0/31/31/31/30 [NPC]
    { 0xE87038DA, 0x7C1E, 0x7FFE }, // Careful, 30/0/31/30/31/31 [NPC]
    { 0xEA4CB4ED, 0x781F, 0x7BDE }, // Sassy, 31/0/30/30/30/30 [NPC]
    { 0xEDF5F205, 0x7C3E, 0x7BFF }, // Rash, 30/1/31/31/31/30 [NPC]
    { 0xF00350BF, 0x783E, 0x7BDE }, // Rash, 30/1/30/30/30/30 [NPC]
    { 0xF0AF9CA7, 0x781E, 0x7BFE }, // Bashful, 30/0/30/30/31/30 [NPC]
    { 0xF0E07F4F, 0x781E, 0x7FFE }, // Calm, 30/0/30/30/31/31 [NPC]
    { 0xF259C774, 0x7C3F, 0x7FFF }, // Hasty, 31/1/31/31/31/31 [NPC]
    { 0xF29CC346, 0x781E, 0x7FDF }, // Adamant, 30/0/30/31/30/31 [NPC]
    { 0xF2D3EBBC, 0x7C1E, 0x7BDE }, // Mild, 30/0/31/30/30/30 [NPC]
    { 0xF467262E, 0x783F, 0x7FDE }, // Hasty, 31/1/30/30/30/31 [NPC]
    { 0xF5147216, 0x781F, 0x7FFF }, // Gentle, 31/0/30/31/31/31 [NPC]
    { 0xF6663879, 0x783E, 0x7BFE }, // Modest, 30/1/30/30/31/30 [NPC]
    { 0xF706DE84, 0x7C1F, 0x7BDF }, // Relaxed, 31/0/31/31/30/30 [NPC]
    { 0xF737C12C, 0x7C1E, 0x7FDE }, // Lax, 30/0/31/30/30/31 [NPC]
    { 0xFA992B40, 0x783F, 0x7BFF }, // Bold, 31/1/30/31/31/30 [NPC]
    { 0xFACA0DE8, 0x783E, 0x7FFF }, // Relaxed, 30/1/30/31/31/31 [NPC]
    { 0xFCBD7A56, 0x7C3E, 0x7BDF }, // Naughty, 30/1/31/31/30/30 [NPC]
    { 0xFCEE5CFE, 0x7C3E, 0x7FDE }, // Docile, 30/1/31/30/30/31 [NPC]
    { 0xFD69C63E, 0x7C1F, 0x7BFF }, // Adamant, 31/0/31/31/31/30 [NPC]
    { 0xFD9AA8E5, 0x7C1E, 0x7FFF }, // Naughty, 30/0/31/31/31/31 [NPC]
    { 0xFF650BCD, 0x7C3F, 0x7FFE }, // Serious, 31/1/31/30/31/31 [NPC]
    { 0xFF7724F8, 0x781F, 0x7BDE }, // Adamant, 31/0/30/30/30/30 [NPC]
    { 0xFFA807A0, 0x781E, 0x7FDE } // Bold, 30/0/30/30/30/31 [NPC]
};
